// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/iProxy/iProxyMxN.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using System;
using System.Runtime.InteropServices;


namespace LinearAlgebra
{

    // A m x n matrix
    // m = rows
    // n = cols
    //
    // Sequential layout pins the trailing padding hole `_gen` (below) relies on.
    [StructLayout(LayoutKind.Sequential)]
    public partial struct longMxN : IDisposable, IUnsafelongArray {

        public int M_Rows;
        public int N_Cols;

        // Arena-tracked path: a stable pointer into the arena's ChunkedRecordTable<longMatRecord>.
        // null for a standalone (non-arena) matrix, in which case Data resolves to _inlineData
        // instead -- see the Data property.
        [NativeDisableUnsafePtrRestriction] private unsafe longMatRecord* _rec;

        // Standalone-path backing store. Stays default(UnsafeList<long>) whenever _rec != null.
        private UnsafeList<long> _inlineData;

        public unsafe UnsafeList<long> Data
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                AssertRecordValid();
#endif
                return _rec != null ? _rec->Data : _inlineData;
            }
            private set { if (_rec != null) _rec->Data = value; else _inlineData = value; }
        }

        // Reconstructs a live Arena handle from this record's owner core; used by Copy()/
        // TempCopy() and the cross-type allocation shortcuts. Only meaningful when _rec != null --
        // callers must only call this on an arena-backed instance.
        private unsafe Arena OwnerArena => new Arena(_rec->Owner);

        public readonly int Length;

        // Generation stamp (packed into existing struct padding) for detecting a stale handle into
        // a since-recycled slot; 0/unused on the standalone path. AssertRecordValid() compares it
        // against the table's current GetGeneration(SelfIndex) -- Alive alone cannot tell "still
        // the same allocation" from "a new one that reused this slot number".
        private readonly int _gen;

        public bool IsSquare => M_Rows == N_Cols;

        /// <summary>True while this matrix has a live allocation (arena-tracked or standalone,
        /// including views); false for default(longMxN) and after Dispose().</summary>
        public unsafe bool IsCreated
        {
            get
            {
                if (_rec == null) return _inlineData.IsCreated;
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if (!ChunkedRecordTable<longMatRecord>.IsAliveFast(_rec) || ChunkedRecordTable<longMatRecord>.GenerationFast(_rec) != _gen)
                    return false;
#endif
                return _rec->Data.IsCreated;
            }
        }

        /// <summary>
        /// Creates a standalone VIEW over <paramref name="viewOf"/>'s memory as a row-major
        /// M_rows x N_cols matrix (viewOf.Length must equal M_rows*N_cols) -- no copy, no
        /// ownership. Element reads/writes go straight to the array. Valid only while the source
        /// array is alive; Dispose() releases nothing (the array keeps ownership). The view is
        /// outside the job-safety system: it does not carry the array's safety handle, so the
        /// caller owns the aliasing/race discipline.
        /// </summary>
        public unsafe longMxN(int M_rows, int N_cols, NativeArray<long> viewOf)
        {
            if (M_rows * N_cols != viewOf.Length)
                throw new ArgumentException("longMxN view: viewOf.Length must equal M_rows * N_cols");

            _rec = null;
            _gen = 0; // standalone (non-arena): never read (AssertRecordValid short-circuits on _rec == null)
            M_Rows = M_rows;
            N_Cols = N_cols;
            Length = viewOf.Length;
            _inlineData = new UnsafeList<long>((long*)viewOf.GetUnsafePtr(), viewOf.Length);
        }

        public unsafe longMxN(int M_rows, int N_cols, Allocator allocator, bool uninit = false)
        {
            _rec = null;
            _inlineData = default;
            _gen = 0; // standalone (non-arena): never read (AssertRecordValid short-circuits on _rec == null)
            M_Rows = M_rows;
            N_Cols = N_cols;
            Length = M_Rows * N_Cols;
            var data = new UnsafeList<long>(Length, allocator, uninit ? NativeArrayOptions.UninitializedMemory : NativeArrayOptions.ClearMemory);
            data.Resize(Length, NativeArrayOptions.UninitializedMemory);
            Data = data;
        }

        /// <summary>
        /// Arena-tracked constructor. <paramref name="rec"/> is a slot already carved from the
        /// arena's record table by the caller (Arena.longMat/longTempMat) -- this ctor only
        /// fills in the record's Data, it does not allocate or own the slot itself.
        /// </summary>
        internal unsafe longMxN(int M_rows, int N_cols, longMatRecord* rec, Allocator allocator, bool uninit = false)
        {
            _rec = rec;
            _inlineData = default;
            _gen = rec->Table->GetGeneration(rec->SelfIndex); // stamp this fresh allocation's generation

            M_Rows = M_rows;
            N_Cols = N_cols;
            Length = M_Rows * N_Cols;
            var data = new UnsafeList<long>(Length, allocator, uninit? NativeArrayOptions.UninitializedMemory : NativeArrayOptions.ClearMemory );
            data.Resize(Length, NativeArrayOptions.UninitializedMemory);
            Data = data;
        }

        /// <summary>
        /// Creates a standalone copy of the matrix with a new allocation.
        /// </summary>
        public unsafe longMxN(in longMxN orig, Allocator allocator = Allocator.Invalid)
        {
            _rec = null;
            _inlineData = default;
            _gen = 0; // standalone (non-arena): never read (AssertRecordValid short-circuits on _rec == null)

            // guard a standalone (null-record) source: fall back to Temp if no allocator is given
            if (allocator == Allocator.Invalid)
                allocator = orig._rec != null ? orig._rec->Owner->Allocator : Allocator.Temp;

            M_Rows = orig.M_Rows;
            N_Cols = orig.N_Cols;
            Length = orig.Length;
            var data = new UnsafeList<long>(Length, allocator, NativeArrayOptions.UninitializedMemory);
            data.Resize(Length, NativeArrayOptions.UninitializedMemory);
            data.CopyFrom(orig.Data);
            Data = data;
        }

        /// <summary>Arena-tracked copy constructor -- same pre-allocated-record contract as above.</summary>
        internal unsafe longMxN(in longMxN orig, longMatRecord* rec, Allocator allocator)
        {
            _rec = rec;
            _inlineData = default;
            _gen = rec->Table->GetGeneration(rec->SelfIndex); // stamp this fresh allocation's generation (NOT orig's)

            M_Rows = orig.M_Rows;
            N_Cols = orig.N_Cols;
            Length = orig.Length;
            var data = new UnsafeList<long>(Length, allocator, NativeArrayOptions.UninitializedMemory);
            data.Resize(Length, NativeArrayOptions.UninitializedMemory);
            data.CopyFrom(orig.Data);
            Data = data;
        }

#if ENABLE_UNITY_COLLECTIONS_CHECKS
        // Debug-only liveness+generation check (compiles out of player builds). Throws on a read
        // after Dispose()/Clear()/ClearTemp() on this record, and also on a stale handle into a
        // slot that was freed and later recycled by a fresh Allocate() for a different allocation
        // (Alive is true again, but the generation moved on). Uses the direct pointer-cast
        // IsAliveFast/GenerationFast to avoid a per-element chunk-scan cost, since this getter runs
        // on every read.
        private unsafe void AssertRecordValid()
        {
            if (_rec != null && (!ChunkedRecordTable<longMatRecord>.IsAliveFast(_rec) || ChunkedRecordTable<longMatRecord>.GenerationFast(_rec) != _gen))
                throw new InvalidOperationException("longMxN.Data: use of disposed/cleared arena allocation");
        }
#endif

        public unsafe longMxN Copy()
        {
            if (_rec == null)
                throw new System.InvalidOperationException("Copy()/TempCopy() require an arena-backed matrix/vector; use new <T>(in this, allocator) for a standalone copy.");

            return OwnerArena.longMat(in this);
        }

        public unsafe longMxN TempCopy()
        {
            if (_rec == null)
                throw new System.InvalidOperationException("Copy()/TempCopy() require an arena-backed matrix/vector; use new <T>(in this, allocator) for a standalone copy.");

            return OwnerArena.longTempMat(in this);
        }

        /// <summary>Copies every element into <paramref name="mat"/> (dimensions must match).</summary>
        public void CopyTo(in longMxN mat)
        {
            if (M_Rows != mat.M_Rows || N_Cols != mat.N_Cols)
                throw new ArgumentException("CopyTo: dimensions do not match!");

            mat.Data.CopyFrom(Data);
        }

        /// <summary>Copies every element from <paramref name="mat"/> (dimensions must match).</summary>
        public void CopyFrom(in longMxN mat)
        {
            if (M_Rows != mat.M_Rows || N_Cols != mat.N_Cols)
                throw new ArgumentException("CopyFrom: dimensions do not match!");

            Data.CopyFrom(mat.Data);
        }

        /// <summary>Copies every element (row-major) into <paramref name="dst"/> (dst.Length must equal M_Rows*N_Cols).</summary>
        public unsafe void CopyTo(NativeArray<long> dst)
        {
            if (Length != dst.Length)
                throw new ArgumentException("CopyTo: dst.Length must equal M_Rows * N_Cols");

            UnsafeUtility.MemCpy(dst.GetUnsafePtr(), Data.Ptr, (long)Length * sizeof(long));
        }

        /// <summary>Copies every element (row-major) from <paramref name="src"/> (src.Length must equal M_Rows*N_Cols).</summary>
        public unsafe void CopyFrom(NativeArray<long> src)
        {
            if (Length != src.Length)
                throw new ArgumentException("CopyFrom: src.Length must equal M_Rows * N_Cols");

            UnsafeUtility.MemCpy(Data.Ptr, src.GetUnsafeReadOnlyPtr(), (long)Length * sizeof(long));
        }

        public unsafe void Dispose() {

            if (_rec != null)
            {
                // Cache Data before Free(): Free() marks the slot dead without clearing the
                // payload. Free() runs before the native Dispose() call, so an aliased
                // double-dispose (a different struct copy sharing this record) throws here, via
                // the table's double-Free guard, before any native memory is touched a second
                // time. Disposing the SAME variable twice is a safe no-op: this call nulls _rec,
                // so a second call takes the standalone branch instead.
                var data = _rec->Data;
                _rec->Table->Free(_rec->SelfIndex);
                data.Dispose();
                _rec = null;
            }
            else
            {
                _inlineData.Dispose();
            }
        }

        public override string ToString()
        {
            var sb = new System.Text.StringBuilder();
            for (int r = 0; r < M_Rows; r++)
            {
                sb.Append("[ ");
                for (int c = 0; c < N_Cols; c++)
                {
                    if (c > 0) sb.Append("  ");
                    sb.Append(this[r, c]);
                }
                sb.Append(" ]");
                if (r < M_Rows - 1) sb.AppendLine();
            }
            return sb.ToString();
        }
    }
}
