// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/iProxy/iProxyN.Indexing.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using System.Runtime.CompilerServices;


namespace LinearAlgebra
{

    public partial struct longN {

        // Direct array accessor (both int and System.Index, from-end supported).
        public ref long this[int index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                Assume.IndexInsideBounds(Data.Length, index);
#endif
                return ref Data.ElementAt(index);
            }
        }

        public ref long this[System.Index index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                var i = index.IsFromEnd ? Data.Length - index.Value : index.Value;
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                Assume.IndexInsideBounds(Data.Length, i);
#endif
                return ref Data.ElementAt(i);
            }
        }

        /// <summary>Handle identity: true iff both views wrap the SAME buffer. NOT elementwise —
        /// use the == operator for an elementwise mask.</summary>
        public override unsafe bool Equals(object obj) =>
            obj is longN other && Data.Ptr == other.Data.Ptr && Data.Length == other.Data.Length;

        public override unsafe int GetHashCode() =>
            unchecked(((int)(long)Data.Ptr * 397) ^ Data.Length);
    }
}