// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/Interfaces/PredicateQuery.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
namespace LinearAlgebra
{
    /// <summary>
    /// Row predicate for struct-functor predicate queries. Reads A[row, 0..N_Cols-1]
    /// directly — zero-alloc, no row extraction. Implement on a blittable struct;
    /// pass by <c>ref</c> to preserve any mutable state across calls.
    /// </summary>
    public interface IdoubleRowPredicate {
        bool Test(in doubleMxN A, int row);
    }

    /// <summary>
    /// Column predicate: symmetric twin of <see cref="IdoubleRowPredicate"/>.
    /// Reads A[0..M_Rows-1, col] with stride. Zero-alloc, no column extraction.
    /// </summary>
    public interface IdoubleColPredicate {
        bool Test(in doubleMxN A, int col);
    }

    /// <summary>
    /// Scalar / elementwise predicate for flat <see cref="IUnsafedoubleArray"/> data.
    /// Used by the generic Group-A ops: findFirst, count, any, all, findAll.
    /// </summary>
    public interface IdoublePredicate {
        bool Test(double x);
    }

    /// <summary>
    /// Row-score functor: returns a scalar score for row r of A.
    /// Used by Group-D score-based selection: argMaxRowBy, argMinRowBy, topKRowsBy.
    /// Higher score = better for argMaxRowBy / topKRowsBy.
    /// </summary>
    public interface IdoubleRowScore {
        double Score(in doubleMxN A, int row);
    }

    /// <summary>
    /// Column-score functor: symmetric twin of <see cref="IdoubleRowScore"/>.
    /// Used by argMaxColBy, argMinColBy, topKColsBy.
    /// </summary>
    public interface IdoubleColScore {
        double Score(in doubleMxN A, int col);
    }
}
