// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/Control.Info.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
//singularFile//
using Unity.Collections;

namespace BULA.Control
{
    /// <summary>
    /// Result of <see cref="LQR.lqg"/>: the two independent DARE solves it runs, one per gain.
    /// Type-agnostic (CS0102), same reasoning as <see cref="RiccatiInfo"/>. Deliberately a thin pair
    /// rather than a merged/averaged diagnostic -- the two Riccati solves are unrelated problems
    /// (control cost vs. process/measurement noise) that only happen to share A and the DARE engine.
    /// </summary>
    public struct LQGInfo
    {
        /// <summary>Terminal state of the LQR (control) DARE solve.</summary>
        public RiccatiInfo lqrInfo;

        /// <summary>Terminal state of the filter (Kalman) DARE solve.</summary>
        public RiccatiInfo kfInfo;

        /// <summary>True iff BOTH solves converged.</summary>
        public bool Solved => lqrInfo.Solved && kfInfo.Solved;

        /// <summary>Implicit success test, so <c>if (LQR.lqg(...))</c> reads as "did both converge".</summary>
        public static implicit operator bool(LQGInfo info) => info.Solved;

        /// <summary>Burst-safe compact summary, e.g. <c>LQGInfo(lqr=Converged/iters=14, kf=Converged/iters=9)</c>.
        /// Never allocates managed memory.</summary>
        public FixedString128Bytes ToFixedString()
        {
            FixedString128Bytes str = "LQGInfo(lqr=";
            str.Append(lqrInfo.status.Name());
            FixedString128Bytes mid = $"/iters={lqrInfo.iterations}, kf=";
            str.Append(mid);
            str.Append(kfInfo.status.Name());
            FixedString128Bytes tail = $"/iters={kfInfo.iterations})";
            str.Append(tail);
            return str;
        }

        /// <summary>Managed wrapper -- do not call from inside a [BurstCompile] job.</summary>
        public override string ToString() => ToFixedString().ToString();
    }

    // Type-agnostic tuning constant for LQR's warm recursion (Control.fProxy.cs); lives here
    // (singularFile) to avoid a duplicate-member collision across the float/double generated
    // fragments, same reasoning as LP.Info.cs's REFACTOR_INTERVAL / MIP.Info.cs's ABS_GAP etc.
    // (The cold-solve budget SDA_MAX_ITER and the blowup factor now live on Riccati.)
    public static partial class LQR
    {
        // Warm-start (plain Riccati recursion, linear-ish convergence from an already-close S) and
        // Riccati.dare-oracle iteration cap. A slightly re-linearized A/B (the per-frame warm-start use
        // case) converges in a handful of steps; 500 is a safety net for a materially-changed system
        // that still happens to be stabilizable, not a target.
        internal const int WARM_MAX_ITER = 500;
    }
}
