// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/Control.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;

using Unity.Collections;
using Unity.Mathematics;

namespace LinearAlgebra.Control
{
    // ================================================================================================
    // Discrete-time LQR. x_{k+1} = A x_k + B u_k, cost Σ(xᵀQx + uᵀRu), optimal feedback u = -Kx via the
    // discrete algebraic Riccati equation (DARE)
    //     S = Q + AᵀSA - AᵀSB(R+BᵀSB)⁻¹BᵀSA,   K = (R+BᵀSB)⁻¹BᵀSA.
    //
    // The DARE itself (the cold infinite-horizon S) is solved by Riccati.dare (structure-preserving
    // doubling); this file is the control facade on top of it. One shared Riccati-step kernel
    // (RiccatiStep below) turns a given S into the gain K = (R+BᵀSB)⁻¹BᵀSA and the next S iterate, and
    // is reused by every entry point: the finite-horizon schedule (backward recursion from Qf), the warm
    // path (plain fixed-point iteration from a carried S), and the cold path's finalization (Riccati.dare
    // converges S, then one RiccatiStep call turns it into K). The m x m (R+BᵀSB) solve always uses CHOP
    // so a semidefinite R degrades to a usable minimum-norm K instead of hard-failing like plain CHO.
    //
    // Numerical hygiene (symmetrize / double-accumulate Frobenius convergence / data-scaled blowup guard)
    // lives in Riccati and is shared verbatim by the warm recursion and the schedule here. Convergence is
    // the relative Frobenius change ‖S_new-S_old‖_F / max(1,‖S_new‖_F) <= Consts.doubleSqrtEps.
    //
    // double storage throughout; double is used only for local scalar control math, never stored back
    // into an double buffer. All scratch is Allocator.Temp (job-safe) except doubleLQRState's own
    // carried S buffer.
    // ================================================================================================
    public static partial class LQR
    {
        // ---- validation (managed-thread throws, house pattern) ----

        // A square (n x n), B (n x m), Q (n x n), R (m x m); R's diagonal must be finite and
        // non-negative (cheap to check, and a NaN/negative weight is always a caller bug) -- Q/R
        // symmetry itself is NOT validated (documented caller contract, consistent with how the
        // library treats SPD/SPSD inputs elsewhere, e.g. CHO/CHOP).
        static void ValidateLQRDims(in doubleMxN A, in doubleMxN B, in doubleMxN Q, in doubleMxN R,
                                    string ctx, out int n, out int m)
        {
            if (!A.IsSquare)
                throw new ArgumentException(ctx + ": A must be square");
            n = A.M_Rows;

            if (B.M_Rows != n)
                throw new ArgumentException(ctx + ": B.M_Rows must equal A's dimension");
            m = B.N_Cols;

            if (!Q.IsSquare || Q.M_Rows != n)
                throw new ArgumentException(ctx + ": Q must be n x n");

            if (!R.IsSquare || R.M_Rows != m)
                throw new ArgumentException(ctx + ": R must be m x m");

            for (int i = 0; i < m; i++)
            {
                double rd = R[i, i];
                if (!math.isfinite(rd) || rd < (double)0)
                    throw new ArgumentException(ctx + ": R diagonal must be finite and non-negative");
            }
        }

        // ---- shared Riccati step kernel ----
        // S⁻ = Q + AᵀSA - AᵀSB(R+BᵀSB)⁻¹BᵀSA,  K = (R+BᵀSB)⁻¹BᵀSA. The m x m solve is CHOP
        // unconditionally (see file header). On a hard CHOP failure (Indefinite -- R+BᵀSB is not even
        // PSD, only reachable from a numerically broken S) Snext/K are left UNTOUCHED (caller must
        // check .Solved before reading them); on RankDeficient the minimum-norm K/S⁻ are still
        // produced, and the caller is responsible for surfacing rankDeficient.
        internal static RankInfo RiccatiStep(in doubleMxN A, in doubleMxN B, in doubleMxN Q, in doubleMxN R,
                                             in doubleMxN S, ref doubleMxN Snext, ref doubleMxN K)
        {
            int n = A.M_Rows, m = B.N_Cols;

            var SB = new doubleMxN(n, m, Allocator.Temp);
            Blas.dot(in S, in B, ref SB);                          // SB = S*B

            var Rbar = new doubleMxN(m, m, Allocator.Temp);
            Blas.dotSym(in B, in SB, ref Rbar);                    // Rbar = Bᵀ(SB), symmetric since S is
            for (int i = 0; i < m; i++)
                for (int j = 0; j < m; j++)
                    Rbar[i, j] += R[i, j];                         // Rbar = R + BᵀSB

            var BSA = new doubleMxN(m, n, Allocator.Temp);
            Blas.dot(in SB, in A, ref BSA, transposeA: true);      // BSA = (SB)ᵀA = BᵀSA

            var L = new doubleMxN(m, m, Allocator.Temp);
            var P = new Pivot(m, Allocator.Temp);
            RankInfo rinfo = CHOP.decomp(in Rbar, ref L, ref P);

            if (rinfo.Solved)
            {
                for (int i = 0; i < m; i++)
                    for (int j = 0; j < n; j++)
                        K[i, j] = BSA[i, j];
                CHOP.decompSolve(ref L, in P, rinfo.rank, ref K);  // K := Rbar⁻¹ BSA

                var SA = new doubleMxN(n, n, Allocator.Temp);
                Blas.dot(in S, in A, ref SA);                      // SA = S*A
                var AtSA = new doubleMxN(n, n, Allocator.Temp);
                Blas.dotSym(in A, in SA, ref AtSA);                // AtSA = Aᵀ(SA), symmetric since S is
                var BSATK = new doubleMxN(n, n, Allocator.Temp);
                Blas.dotSym(in BSA, in K, ref BSATK);              // BSAᵀK = BSAᵀ R̄⁻¹ BSA, symmetric since R̄ is

                for (int i = 0; i < n; i++)
                    for (int j = 0; j < n; j++)
                        Snext[i, j] = Q[i, j] + AtSA[i, j] - BSATK[i, j];

                SA.Dispose(); AtSA.Dispose(); BSATK.Dispose();
            }

            SB.Dispose(); Rbar.Dispose(); BSA.Dispose(); L.Dispose(); P.Dispose();
            return rinfo;
        }

        // Cold solve: Riccati.dare for S, then ONE RiccatiStep call (the shared kernel) at the converged S to
        // produce K -- shared by the plain cold overload (lqr) and the warm-state overload's cold
        // fallback (lqr with a not-yet-populated doubleLQRState).
        static RiccatiInfo SolveCold(in doubleMxN A, in doubleMxN B, in doubleMxN Q, in doubleMxN R,
                                 ref doubleMxN K, ref doubleMxN S, int maxIter)
        {
            var info = Riccati.dare(in A, in B, in Q, in R, ref S, maxIter);

            var Snext = new doubleMxN(A.M_Rows, A.M_Rows, Allocator.Temp);
            var kinfo = RiccatiStep(in A, in B, in Q, in R, in S, ref Snext, ref K);
            if (kinfo.Solved)
                info.rankDeficient |= kinfo.status == DirectSolveStatus.RankDeficient;
            else
                info.status = RiccatiStatus.Diverged;
            Snext.Dispose();

            return info;
        }

        // ---- plain Riccati recursion (warm path + SDA oracle) ----
        // Iterates the shared kernel from S0 until convergence/divergence, then ONE more RiccatiStep
        // call at the converged S produces the authoritative K (same "finalize once" shape as
        // SolveCold, so mid-recursion K's -- one step behind their own S -- never leak out).
        // Sresult is written whenever status != Diverged (last-iterate convention); untouched on
        // Diverged. internal (not private): exposed for direct testing with a large maxIter.
        internal static RiccatiInfo RiccatiIterate(in doubleMxN A, in doubleMxN B, in doubleMxN Q, in doubleMxN R,
                                               in doubleMxN S0, ref doubleMxN Sresult, ref doubleMxN K, int maxIter)
        {
            var Scur = new doubleMxN(in S0, Allocator.Temp);
            var Snext = new doubleMxN(A.M_Rows, A.M_Rows, Allocator.Temp);
            var Kscratch = new doubleMxN(K.M_Rows, K.N_Cols, Allocator.Temp);

            double tol = (double)Consts.doubleSqrtEps;
            double blowup = Riccati.BlowupThreshold(in Q, in R);
            int budget = maxIter > 0 ? maxIter : WARM_MAX_ITER;

            int iters = 0;
            RiccatiStatus status = RiccatiStatus.MaxIterations;
            double residual = double.PositiveInfinity;

            while (iters < budget)
            {
                var rinfo = RiccatiStep(in A, in B, in Q, in R, in Scur, ref Snext, ref Kscratch);
                iters++;
                if (!rinfo.Solved) { status = RiccatiStatus.Diverged; residual = double.PositiveInfinity; break; }

                Riccati.SymmetrizeInPlace(ref Snext);
                double newNorm = Riccati.FrobeniusNorm(in Snext);
                if (!(newNorm <= blowup)) { status = RiccatiStatus.Diverged; residual = double.PositiveInfinity; break; }

                double diffNorm = Riccati.FrobeniusNormDiff(in Snext, in Scur);
                residual = diffNorm / math.max(1.0, newNorm);
                Scur.CopyFrom(in Snext);

                if (residual <= tol) { status = RiccatiStatus.Converged; break; }
            }

            bool rankDeficient = false;
            if (status != RiccatiStatus.Diverged)
            {
                var kinfo = RiccatiStep(in A, in B, in Q, in R, in Scur, ref Snext, ref K);
                if (kinfo.Solved)
                {
                    rankDeficient = kinfo.status == DirectSolveStatus.RankDeficient;
                    Sresult.CopyFrom(in Scur);
                }
                else
                {
                    status = RiccatiStatus.Diverged;
                }
            }

            Scur.Dispose(); Snext.Dispose(); Kscratch.Dispose();

            return new RiccatiInfo { iterations = iters, residual = residual, status = status, rankDeficient = rankDeficient };
        }

        // ---- public entry points ----

        /// <summary>
        /// Infinite-horizon discrete LQR, cold solve: computes the stabilizing feedback gain K (m x n,
        /// caller-allocated) so u = -Kx minimizes Σ(xᵀQx + uᵀRu) for x_{k+1} = Ax_k + Bu_k, via the
        /// discrete algebraic Riccati equation solved by SDA (structure-preserving doubling, port of
        /// Chiang-Fan-Lin Algorithm 2.1; quadratic convergence, ~10-25 steps typically). Use the
        /// <c>ref doubleLQRState</c> overload instead when K
        /// will be re-solved repeatedly for a slightly-changing A/B (e.g. per-frame re-linearization).
        /// </summary>
        /// <param name="A">Dynamics, n x n.</param>
        /// <param name="B">Control input, n x m.</param>
        /// <param name="Q">State cost, n x n (assumed symmetric PSD; not numerically validated).</param>
        /// <param name="R">Control cost, m x m (assumed symmetric PSD; not numerically validated --
        /// only its diagonal's finiteness/non-negativity is checked).</param>
        /// <param name="K">Output feedback gain, m x n (overwritten).</param>
        /// <param name="maxIter">SDA doubling-step budget; &lt;=0 picks the library default (50).</param>
        public static RiccatiInfo lqr(in doubleMxN A, in doubleMxN B, in doubleMxN Q, in doubleMxN R,
                                  ref doubleMxN K, int maxIter = 0)
        {
            ValidateLQRDims(in A, in B, in Q, in R, "LQR.lqr", out int n, out int m);
            if (K.M_Rows != m || K.N_Cols != n)
                throw new ArgumentException("LQR.lqr: K must be m x n");

            var S = new doubleMxN(n, n, Allocator.Temp);
            var info = SolveCold(in A, in B, in Q, in R, ref K, ref S, maxIter);
            S.Dispose();
            return info;
        }

        /// <summary>
        /// Infinite-horizon discrete LQR, warm-started: same problem as the cold overload, but reuses
        /// <paramref name="state"/>'s carried Riccati solution S across calls -- the per-frame re-
        /// linearization use case (A/B change slightly every call). If <paramref name="state"/> is
        /// already <c>populated</c> (from a prior call on a matching-shape problem), a cheap plain
        /// Riccati recursion (not SDA) iterates from the carried S; a slightly-changed A/B typically
        /// converges in a handful of steps. Otherwise runs the same cold SDA solve as the plain
        /// overload. The terminal S is written back into <paramref name="state"/> (and
        /// <c>populated</c> set true) ONLY on a <see cref="RiccatiStatus.Converged"/> exit, so a non-
        /// converged call never corrupts a future warm seed.
        /// </summary>
        /// <param name="state">Must be constructed via <c>new doubleLQRState(n, allocator)</c> before
        /// the first call (job-safe: this overload never allocates). Dimension mismatch against A/Q
        /// throws.</param>
        /// <param name="maxIter">Iteration budget for whichever path runs (SDA if cold, the plain
        /// recursion if warm); &lt;=0 picks that path's own library default (50 cold / 500 warm).</param>
        public static RiccatiInfo lqr(in doubleMxN A, in doubleMxN B, in doubleMxN Q, in doubleMxN R,
                                  ref doubleMxN K, ref doubleLQRState state, int maxIter = 0)
        {
            ValidateLQRDims(in A, in B, in Q, in R, "LQR.lqr", out int n, out int m);
            if (K.M_Rows != m || K.N_Cols != n)
                throw new ArgumentException("LQR.lqr: K must be m x n");

            if (!state.IsCreated)
                throw new ArgumentException("LQR.lqr: state must be constructed via new doubleLQRState(n, allocator) before use");
            if (!state.IsValid(n))
                throw new ArgumentException("LQR.lqr: state dimensions do not match A");

            RiccatiInfo info;
            if (state.populated)
            {
                var Snew = new doubleMxN(n, n, Allocator.Temp);
                info = RiccatiIterate(in A, in B, in Q, in R, in state.S, ref Snew, ref K, maxIter);
                if (info.status == RiccatiStatus.Converged)
                    state.S.CopyFrom(in Snew);
                Snew.Dispose();
            }
            else
            {
                var Scold = new doubleMxN(n, n, Allocator.Temp);
                info = SolveCold(in A, in B, in Q, in R, ref K, ref Scold, maxIter);
                if (info.status == RiccatiStatus.Converged)
                    state.S.CopyFrom(in Scold);
                Scold.Dispose();
            }

            if (info.status == RiccatiStatus.Converged)
                state.populated = true;

            return info;
        }

        /// <summary>
        /// Finite-horizon discrete LQR: backward Riccati recursion from the terminal cost
        /// <paramref name="Qf"/> over <paramref name="N"/> steps, using the SAME shared Riccati-step
        /// kernel as the infinite-horizon paths. <paramref name="Kschedule"/> is (N*m) x n; the gain
        /// for step k lives in rows [k*m, (k+1)*m). For large N with <c>Qf == Q</c>, row block 0
        /// approaches the infinite-horizon K.
        /// </summary>
        /// <param name="N">Horizon length, &gt;= 1.</param>
        /// <param name="Kschedule">Output, (N*m) x n (overwritten row-block by row-block).</param>
        public static RiccatiInfo lqrSchedule(in doubleMxN A, in doubleMxN B, in doubleMxN Q, in doubleMxN R,
                                          in doubleMxN Qf, int N, ref doubleMxN Kschedule)
        {
            ValidateLQRDims(in A, in B, in Q, in R, "LQR.lqrSchedule", out int n, out int m);
            if (!Qf.IsSquare || Qf.M_Rows != n)
                throw new ArgumentException("LQR.lqrSchedule: Qf must be n x n");
            if (N < 1)
                throw new ArgumentException("LQR.lqrSchedule: N must be >= 1");
            if (Kschedule.M_Rows != N * m || Kschedule.N_Cols != n)
                throw new ArgumentException("LQR.lqrSchedule: Kschedule must be (N*m) x n");

            var Sk = new doubleMxN(in Qf, Allocator.Temp);
            var Snext = new doubleMxN(n, n, Allocator.Temp);
            var Kstep = new doubleMxN(m, n, Allocator.Temp);

            double blowup = Riccati.BlowupThreshold(in Q, in Qf);
            bool rankDeficient = false;
            RiccatiStatus status = RiccatiStatus.Converged;
            int steps = 0;
            double residual = double.PositiveInfinity;

            for (int k = N - 1; k >= 0; k--)
            {
                var rinfo = RiccatiStep(in A, in B, in Q, in R, in Sk, ref Snext, ref Kstep);
                steps++;
                if (!rinfo.Solved) { status = RiccatiStatus.Diverged; residual = double.PositiveInfinity; break; }
                if (rinfo.status == DirectSolveStatus.RankDeficient) rankDeficient = true;

                Riccati.SymmetrizeInPlace(ref Snext);
                double newNorm = Riccati.FrobeniusNorm(in Snext);
                if (!(newNorm <= blowup)) { status = RiccatiStatus.Diverged; residual = double.PositiveInfinity; break; }

                for (int r = 0; r < m; r++)
                    for (int c = 0; c < n; c++)
                        Kschedule[k * m + r, c] = Kstep[r, c];

                residual = Riccati.FrobeniusNormDiff(in Snext, in Sk) / math.max(1.0, newNorm);

                Sk.CopyFrom(in Snext);
            }

            Sk.Dispose(); Snext.Dispose(); Kstep.Dispose();

            return new RiccatiInfo { iterations = steps, residual = residual, status = status, rankDeficient = rankDeficient };
        }

        /// <summary>
        /// Linear-Quadratic-Gaussian convenience: solves the control DARE (via <see cref="lqr"/>)
        /// and the filter DARE (via <see cref="Kalman.steadyStateGain"/>) for the SAME dynamics A --
        /// both are the same SDA (structure-preserving doubling) engine, the filter side reached
        /// through the LQR/KF duality mapping (see Kalman.double.cs's file header). The separation
        /// principle means Klqr and Kkf can be designed independently and combined (estimate with
        /// Kkf, then feed the estimate to u=-Klqr·x̂) -- this call does not couple them beyond solving
        /// both from the same A.
        /// </summary>
        /// <param name="A">Dynamics, n x n (shared by both DAREs).</param>
        /// <param name="B">Control input, n x p.</param>
        /// <param name="H">Measurement matrix, m x n.</param>
        /// <param name="Qlqr">LQR state cost, n x n.</param>
        /// <param name="Rlqr">LQR control cost, p x p.</param>
        /// <param name="Qkf">Filter process noise covariance, n x n.</param>
        /// <param name="Rkf">Filter measurement noise covariance, m x m.</param>
        /// <param name="Klqr">Output LQR feedback gain, p x n.</param>
        /// <param name="Kkf">Output steady-state Kalman gain, n x m.</param>
        /// <param name="maxIter">SDA doubling-step budget for BOTH solves; &lt;=0 picks the
        /// library default.</param>
        public static LQGInfo lqg(in doubleMxN A, in doubleMxN B, in doubleMxN H,
                                  in doubleMxN Qlqr, in doubleMxN Rlqr,
                                  in doubleMxN Qkf, in doubleMxN Rkf,
                                  ref doubleMxN Klqr, ref doubleMxN Kkf, int maxIter = 0)
        {
            var lqrInfo = lqr(in A, in B, in Qlqr, in Rlqr, ref Klqr, maxIter);
            var kfInfo = Kalman.steadyStateGain(in A, in H, in Qkf, in Rkf, ref Kkf, maxIter);
            return new LQGInfo { lqrInfo = lqrInfo, kfInfo = kfInfo };
        }
    }

    /// <summary>
    /// Buffer-carrying warm-start state for <see cref="LQR.lqr(in doubleMxN, in doubleMxN, in doubleMxN, in doubleMxN, ref doubleMxN, ref doubleLQRState, int)"/>:
    /// carries the n x n Riccati solution S across separate top-level calls, for LQR's per-frame
    /// re-linearization use case. Standalone, user-allocated, since it must persist across separate
    /// solve calls. MUST be constructed via <c>(n, Allocator)</c> before being
    /// passed to the warm <c>lqr</c> overload -- an uncreated instance is a caller error and <c>lqr</c>
    /// throws rather than silently falling back to a cold solve.
    /// </summary>
    public struct doubleLQRState
    {
        /// <summary>Carried Riccati solution, n x n. Meaningful only when <see cref="populated"/>.</summary>
        public doubleMxN S;

        NativeReference<int> _populated;

        /// <summary>False on a freshly-constructed instance. <c>lqr(..., ref state)</c> sets this true
        /// (and writes the terminal S) ONLY on a <see cref="RiccatiStatus.Converged"/> exit -- a non-
        /// converged call never corrupts a future warm seed. Native-backed: a plain field would not
        /// survive an <c>IJob</c> by-value copy (silently forcing every warm call back onto the cold
        /// path), so this lives behind a shared handle that writes persist through -- no rehydrate or
        /// copy-back needed.</summary>
        public bool populated
        {
            get => _populated.IsCreated && _populated.Value != 0;
            set => _populated.Value = value ? 1 : 0;
        }

        /// <summary>Allocates a state sized for an n x n Riccati solution. <see cref="populated"/>
        /// starts false, so the first <c>lqr(..., ref state)</c> call using this instance always takes
        /// the cold SDA path.</summary>
        public doubleLQRState(int n, Allocator allocator)
        {
            S = new doubleMxN(n, n, allocator);
            _populated = new NativeReference<int>(allocator);   // zero-initialised => not populated
        }

        /// <summary>True once <see cref="S"/> is allocated (regardless of <see cref="populated"/>).</summary>
        public bool IsCreated => S.Data.IsCreated;

        /// <summary>True iff created AND sized for exactly <paramref name="n"/>.</summary>
        public bool IsValid(int n) => IsCreated && S.M_Rows == n && S.N_Cols == n;

        /// <summary>Releases <see cref="S"/>. Safe to call on an empty/already-disposed instance.</summary>
        public void Dispose()
        {
            if (S.Data.IsCreated) S.Dispose();
            if (_populated.IsCreated) _populated.Dispose();
        }
    }
}
