// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/FFT.Workspace.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using System.Runtime.CompilerServices;
using Unity.Burst;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Mathematics;
using LinearAlgebra.Internal;   // doubleW (8-lane AVX helper) for the wide radix-4 butterfly

namespace LinearAlgebra
{
    /// <summary>
    /// Precomputed twiddle table for FFT. One size-n table serves every radix-2 transform of
    /// length ≤ n: the stage-len butterfly twiddle W_len^k is indexed as twReFull[k*(n/len)],
    /// twImFull[k*(n/len)], eliminating per-element cos/sin from the hot loop. Build once via
    /// Arena.doubleFFTCache(n) and reuse across many transforms of the same size.
    ///
    /// The table is computed at double precision and cast to the element type (float or double),
    /// so accuracy is maximized regardless of the transform element type.
    ///
    /// The full-circle table (twReFull/twImFull, length n) is required by the auto-dispatch
    /// radix-4 paths inside fft/ifft: radix-4 twiddles reach index 3n/4, past the half-table
    /// boundary.
    /// </summary>
    public struct doubleFFTCache
    {
        public doubleN twReFull;   // length n:   cos(-2π·m/n), m = 0..n-1    (full circle)
        public doubleN twImFull;   // length n:   sin(-2π·m/n); the half-circle uses (rfft/irfft
                                   //             unpack) read the first n/2 entries directly.
        public int n;              // the FFT size this table is built for (must be a power of two, >= 2)

        // Scratch buffers — allocated once in the factory, reused on every call.
        // Single-use-at-a-time: one workspace per concurrent transform (FFTW-plan semantics).
        public doubleN cz;         // length n/2: even-sample packing scratch for rfft/irfft
        public doubleN sz;         // length n/2: odd-sample  packing scratch for rfft/irfft
        public doubleN visited;    // length n:   cycle-following scratch for FftCoreRadix4Mixed
                                   //             (stores 0/1 flags via double; [0,size) used per call)

        // Contiguous per-stage W^1 twiddle table for the wide (doubleW) radix-4 butterfly: stages
        // with quarter-stride q >= doubleW.Width (8 float / 4 double lanes), concatenated in stage
        // order (total length swLen). W^2 and W^3 are derived from W^1 in-register (W^2=W^1·W^1,
        // W^3=W^1·W^2), so only W^1 is stored. Serves both the top-level pow-4 butterfly and the
        // pow-4 radix-4 sub-transforms of the mixed-radix / rfft / irfft paths (same tableN).
        public doubleN sw1re, sw1im;
        public int swLen;

        // Contiguous combine-twiddle table for the mixed-radix radix-2 combine (Step 3 of
        // FftCoreRadix4Mixed): cw1re[k] = T_n[k*(n/size)], cw1im[k] = ... for k = 0..size/2-1,
        // where `size` is the single mixed-transform size this n produces (n itself when n = 2·4^k,
        // or n/2 via the rfft/irfft inner FFT when n = 4^k). Gathering the strided combine twiddle
        // into a contiguous run lets the radix-2 combine wide-load twiddles and E/O data together.
        // For the combineStep==1 case these fields simply alias twReFull/twImFull (already contiguous).
        public doubleN cw1re, cw1im;
    }

    public static partial class ArenaExtensions
    {
        /// <summary>
        /// Allocates a twiddle-table FFT workspace for an n-point transform (n must be a power of two,
        /// n ≥ 2). Entries are computed via direct per-entry cos/sin at double precision (no recurrence
        /// drift); see <see cref="doubleFFTCache"/> for the table layout and full-circle-table rationale.
        ///
        /// The buffers are persistent in this arena (disposed with it), so create the workspace once
        /// outside a hot loop and pass it to the table overloads. One table serves fft/ifft of length
        /// exactly n and rfft/irfft of real signal length exactly n.
        /// </summary>
        public static unsafe doubleFFTCache doubleFFTCache(this ref Arena arena, int n)
        {
            if (n < 2 || (n & (n - 1)) != 0)
                throw new ArgumentException("doubleFFTCache: n must be a power of two and >= 2");

            int half = n >> 1;
            var twReFull = arena.doubleVec(n);
            var twImFull = arena.doubleVec(n);

            // Twiddle table = Nth roots of unity W_N^m = exp(-2πi·m/n), generated at double precision
            // with only +,-,*,sqrt (cross-arch deterministic under FloatMode.Strict; no sin/cos). The
            // binary generator roots B_k = exp(-2πi·2^k/n) come from stable unit-circle half-angle
            // square roots; each W_N^m is the product of B_k over m's set bits, then cast to double.
            int P = 0;
            for (int t = n; t > 1; t >>= 1) P++;   // log2(n)
            double* bkr = stackalloc double[32];
            double* bki = stackalloc double[32];
            bkr[P - 1] = -1.0; bki[P - 1] = 0.0;                    // B_{P-1} = exp(-πi)
            if (P >= 2) { bkr[P - 2] = 0.0; bki[P - 2] = -1.0; }    // B_{P-2} = exp(-πi/2)
            for (int k = P - 3; k >= 0; k--)
            {
                double a = bkr[k + 1];                    // cos(angle_{k+1})
                double c = math.sqrt((1.0 + a) * 0.5);    // cos(angle_k), angle_k = angle_{k+1}/2
                bkr[k] = c;
                bki[k] = bki[k + 1] / (2.0 * c);          // -sin(angle_k), cancellation-free
            }
            // Recursive-doubling fill: W^0 = 1, then for each bit k, W^(2^k + j) = W^j · B_k for
            // j < 2^k. One complex-mult per entry (O(n) total vs O(n·log n) for per-entry
            // bit-decomposition). Each entry is still <= log2(n) mults deep in the dependency chain,
            // so error stays O(log n · ε). Kept in a double scratch and cast to double once, so the
            // accuracy model is identical to the per-entry form.
            var dre = (double*)UnsafeUtility.Malloc((long)n * sizeof(double), 16, Allocator.Persistent);
            var dim = (double*)UnsafeUtility.Malloc((long)n * sizeof(double), 16, Allocator.Persistent);
            dre[0] = 1.0; dim[0] = 0.0;
            for (int k = 0; k < P; k++)
            {
                int block = 1 << k;
                double br = bkr[k], bi = bki[k];
                for (int j = 0; j < block; j++)
                {
                    double ar = dre[j], ai = dim[j];
                    dre[block + j] = ar * br - ai * bi;
                    dim[block + j] = ar * bi + ai * br;
                }
            }
            for (int m = 0; m < n; m++)
            {
                twReFull[m] = (double)dre[m];
                twImFull[m] = (double)dim[m];
            }
            UnsafeUtility.Free(dre, Allocator.Persistent);
            UnsafeUtility.Free(dim, Allocator.Persistent);

            // Scratch buffers — persistent in this arena (disposed with the arena).
            // cz/sz are the two-for-one packing temporaries for rfft/irfft (length n/2 = M).
            // visited is the cycle-following scratch for FftCoreRadix4Mixed (length n; [0,M) used
            // when called from the rfft/irfft inner M-point sub-FFT, still within bounds).
            var cz      = arena.doubleVec(half, uninit: true);
            var sz      = arena.doubleVec(half, uninit: true);
            var visited = arena.doubleVec(n,    uninit: true);

            // Wide-butterfly stage twiddles: the contiguous per-stage W^1 table used by the wide
            // (doubleW) radix-4 butterfly. Every power-of-two n gets one: the wide butterfly drives
            // the pow-4 top-level path AND the pow-4 radix-4 sub-transforms of the mixed-radix
            // (2·4^k) and rfft/irfft paths, which share this same table (they index the same
            // full-circle tableN = n at stage quarter-stride qq, step = n/(4·qq)). The largest wide
            // stage over all sub-transforms has 4·qq <= n; that is the loop bound. Stages with
            // qq < doubleW.Width stay scalar and are skipped here.
            int swLen = 0;
            for (int qq = 1; 4 * qq <= n; qq <<= 2)
                if (qq >= doubleW.Width) swLen += qq;
            int swAlloc = swLen > 0 ? swLen : 1;
            var sw1re = arena.doubleVec(swAlloc, uninit: true);
            var sw1im = arena.doubleVec(swAlloc, uninit: true);
            {
                int off = 0;
                for (int qq = 1; 4 * qq <= n; qq <<= 2)
                {
                    if (qq < doubleW.Width) continue;
                    int len  = qq << 2;
                    int step = n / len;
                    for (int j = 0; j < qq; j++)
                    {
                        int t1 = j * step;
                        sw1re[off + j] = twReFull[t1]; sw1im[off + j] = twImFull[t1];
                    }
                    off += qq;
                }
            }

            // Combine-twiddle table for the mixed-radix radix-2 combine (Step 3). This n triggers the
            // mixed path at exactly one size/step:
            //   n = 2·4^k (P odd)  → fft/ifft mixed at size = n,   combineStep = 1  (already contiguous)
            //   n = 4^k    (P even) → rfft/irfft inner mixed at size = n/2, combineStep = 2  (strided)
            // The step-1 layout is the first n/2 entries of the full-circle table — share the buffer,
            // no copy. The step-2 layout is gathered into a contiguous length-n/4 run.
            doubleN cw1re, cw1im;
            if ((P & 1) == 0)
            {
                int cwLen = n >> 2;   // n/4 = mixed inner M for n = 4^k (>= 1 since n >= 4 here)
                cw1re = arena.doubleVec(cwLen, uninit: true);
                cw1im = arena.doubleVec(cwLen, uninit: true);
                for (int k = 0; k < cwLen; k++)
                {
                    cw1re[k] = twReFull[2 * k];
                    cw1im[k] = twImFull[2 * k];
                }
            }
            else
            {
                cw1re = twReFull;   // combineStep == 1: full-circle table is already the combine table
                cw1im = twImFull;
            }

            return new doubleFFTCache
            {
                twReFull = twReFull,
                twImFull = twImFull,
                n        = n,
                cz       = cz,
                sz       = sz,
                visited  = visited,
                sw1re = sw1re, sw1im = sw1im,
                swLen = swLen,
                cw1re = cw1re, cw1im = cw1im,
            };
        }
    }

    public static partial class FFT
    {
        // ---- workspace guard ----

        /// <summary>
        /// Throws if <paramref name="ws"/> is not sized for an n-point FFT. Matches the layout
        /// produced by Arena.doubleFFTCache(n): ws.n == n and table lengths == n/2.
        /// </summary>
        static void RequireFftWorkspace(in doubleFFTCache ws, int n, string who)
        {
            if (ws.n != n ||
                ws.cz.N != n >> 1 || ws.sz.N != n >> 1 || ws.visited.N != n)
                throw new ArgumentException(
                    who + ": workspace must be sized for an n-point FFT (use Arena.doubleFFTCache(n))");
        }

        /// <summary>
        /// Throws if the workspace is missing the full-circle twiddle table required by the
        /// radix-4 dispatch paths. Extends <see cref="RequireFftWorkspace"/>.
        /// </summary>
        static void RequireRadix4Workspace(in doubleFFTCache ws, int n, string who)
        {
            RequireFftWorkspace(in ws, n, who);
            if (ws.twReFull.N != n || ws.twImFull.N != n)
                throw new ArgumentException(
                    who + ": workspace must have full-circle twiddle table (use Arena.doubleFFTCache(n))");
        }

        // ---- table-indexed overloads ----

        /// <summary>
        /// In-place forward FFT for any power-of-two length, using a precomputed twiddle table;
        /// throws for a non-power-of-two length (use dft for arbitrary N). ws must be sized for re.N
        /// (build via Arena.doubleFFTCache(N)); it must contain the full-circle twiddle table required
        /// by the radix-4 dispatch. Both arrays must have the same length, which must be a power of two.
        /// </summary>
        public static void fft(ref doubleN re, ref doubleN im, in doubleFFTCache ws)
        {
            int n = re.N;
            RequireRadix4Workspace(in ws, n, "fft");

            var twReFull    = ws.twReFull;
            var twImFull    = ws.twImFull;
            var sw1re       = ws.sw1re;
            var sw1im       = ws.sw1im;
            var cw1re       = ws.cw1re;
            var cw1im       = ws.cw1im;
            if (IsPowerOf4(n))
            {
                FftCoreRadix4(ref re, ref im, ref twReFull, ref twImFull, ref sw1re, ref sw1im, n, false);
            }
            else if ((n & (n - 1)) == 0)   // power-of-2, not power-of-4 → 2·4^k mixed-radix path
            {
                var visitedScratch = ws.visited;
                FftCoreRadix4Mixed(ref re, ref im, ref twReFull, ref twImFull, ref sw1re, ref sw1im, ref cw1re, ref cw1im, visitedScratch, n, false);
            }
            else
            {
                // radix-4 ∪ mixed cover every power of two, so this is reached only by a
                // non-power-of-two length, which Cooley-Tukey cannot handle.
                throw new ArgumentException("fft: length must be a power of two (use dft for arbitrary N)");
            }
        }

        /// <summary>
        /// In-place inverse FFT, same dispatch as fft. Divides by N so that ifft(fft(x, ws), ws) == x.
        /// ws must be sized for re.N.
        /// </summary>
        public static void ifft(ref doubleN re, ref doubleN im, in doubleFFTCache ws)
        {
            int n = re.N;
            RequireRadix4Workspace(in ws, n, "ifft");

            var twReFull    = ws.twReFull;
            var twImFull    = ws.twImFull;
            var sw1re       = ws.sw1re;
            var sw1im       = ws.sw1im;
            var cw1re       = ws.cw1re;
            var cw1im       = ws.cw1im;
            if (IsPowerOf4(n))
            {
                FftCoreRadix4(ref re, ref im, ref twReFull, ref twImFull, ref sw1re, ref sw1im, n, true);
            }
            else if ((n & (n - 1)) == 0)   // power-of-2, not power-of-4 → 2·4^k mixed-radix path
            {
                var visitedScratch = ws.visited;
                FftCoreRadix4Mixed(ref re, ref im, ref twReFull, ref twImFull, ref sw1re, ref sw1im, ref cw1re, ref cw1im, visitedScratch, n, true);
            }
            else
            {
                // radix-4 ∪ mixed cover every power of two, so this is reached only by a
                // non-power-of-two length, which Cooley-Tukey cannot handle.
                throw new ArgumentException("ifft: length must be a power of two (use idft for arbitrary N)");
            }
        }

        /// <summary>
        /// Real-input forward FFT using a precomputed twiddle table. ws must be sized for real.N
        /// (the full real signal length N — not the half-spectrum length N/2+1).
        /// Identical two-for-one packing as the recurrence rfft, but the inner M-point FFT uses
        /// the radix-4/mixed dispatch and the unpack twiddle W_N^k = (ws.twReFull[k], ws.twImFull[k]) is
        /// read directly — no cos/sin in the hot loop.
        /// </summary>
        public static void rfft(in doubleN real, ref doubleN re, ref doubleN im, in doubleFFTCache ws)
        {
            int n = real.N;
            RequireRadix4Workspace(in ws, n, "rfft");

            if (!IsPow2(n))
                throw new ArgumentException("rfft: length must be a power of two");

            int halfSpec = (n >> 1) + 1;
            if (re.N != halfSpec || im.N != halfSpec)
                throw new ArgumentException("rfft: re and im must have length N/2+1");

            unsafe
            {
                if (im.Data.Ptr == real.Data.Ptr || im.Data.Ptr == re.Data.Ptr)
                    throw new ArgumentException("rfft: im must not alias real or re");
            }

            if (n == 1)
            {
                re[0] = real[0];
                im[0] = (double)0;
                return;
            }

            int M = n >> 1;   // N/2

            // Step 1: Pack even and odd samples into a length-M complex sequence.
            // Use workspace scratch (no per-call allocation).
            var cz = ws.cz;   // doubleN of length n/2 = M
            var sz = ws.sz;   // doubleN of length n/2 = M
            for (int j = 0; j < M; j++)
            {
                cz[j] = real[2 * j];
                sz[j] = real[2 * j + 1];
            }

            // Step 2: Inner M-point FFT via radix-4 (with full-circle table, tableN = ws.n = N).
            // IsPowerOf4(M) → pure radix-4 (M = 4^k); else → mixed 2·4^k path (M = 2·4^k).
            // Both paths index into twReFull/twImFull at step ws.n/len — no sub-table copy.
            var twReFull = ws.twReFull;
            var twImFull = ws.twImFull;
            var sw1re    = ws.sw1re;
            var sw1im    = ws.sw1im;
            var cw1re    = ws.cw1re;
            var cw1im    = ws.cw1im;
            var visitedScratch = ws.visited;
            if (IsPowerOf4(M))
                FftCoreRadix4(ref cz, ref sz, ref twReFull, ref twImFull, ref sw1re, ref sw1im, ws.n, false);
            else
                FftCoreRadix4Mixed(ref cz, ref sz, ref twReFull, ref twImFull, ref sw1re, ref sw1im, ref cw1re, ref cw1im, visitedScratch, ws.n, false);

            // Step 3: Unpack. DC and Nyquist are always real for a real input.
            re[0] = cz[0] + sz[0];
            im[0] = (double)0;
            re[M] = cz[0] - sz[0];
            im[M] = (double)0;

            // General bins k = 1..M-1.
            // W_N^k = exp(-2πi·k/N) = (ws.twReFull[k], ws.twImFull[k]) — read directly, no cos/sin.
            for (int k = 1; k < M; k++)
            {
                int kr = M - k;
                double E_re = (cz[k] + cz[kr]) * (double)0.5;
                double E_im = (sz[k] - sz[kr]) * (double)0.5;
                double O_re = (sz[k] + sz[kr]) * (double)0.5;
                double O_im = (cz[kr] - cz[k]) * (double)0.5;

                double curRe = twReFull[k];   // W_N^k real part (first half of full table)
                double curIm = twImFull[k];   // W_N^k imaginary part

                re[k] = E_re + (curRe * O_re - curIm * O_im);
                im[k] = E_im + (curRe * O_im + curIm * O_re);
            }

        }

        /// <summary>
        /// Inverse real FFT using a precomputed twiddle table. ws must be sized for the real signal
        /// length N = 2*(re.N-1) (= real.N). The re-pack conjugate twiddle conj(W_N^k) is read as
        /// (ws.twReFull[k], -ws.twImFull[k]) — no cos/sin in the hot loop.
        /// irfft(rfft(x, ws), ws) == x to floating-point precision.
        /// </summary>
        public static void irfft(in doubleN re, in doubleN im, ref doubleN real, in doubleFFTCache ws)
        {
            int halfSpec = re.N;
            if (im.N != halfSpec)
                throw new ArgumentException("irfft: re and im must have the same length");
            if (halfSpec < 2)
                throw new ArgumentException("irfft: re.N must be >= 2 (minimum signal length N=2)");

            int M = halfSpec - 1;   // N/2
            int N = M << 1;         // signal length

            if (!IsPow2(N))
                throw new ArgumentException("irfft: N = 2*(re.N-1) must be a power of two");
            if (real.N != N)
                throw new ArgumentException("irfft: real.N must equal 2*(re.N-1)");

            RequireRadix4Workspace(in ws, N, "irfft");

            unsafe
            {
                if (real.Data.Ptr == re.Data.Ptr || real.Data.Ptr == im.Data.Ptr)
                    throw new ArgumentException("irfft: real must not alias re or im");
            }

            // Use workspace scratch (no per-call allocation).
            var cz = ws.cz;   // doubleN of length n/2 = M
            var sz = ws.sz;   // doubleN of length n/2 = M

            // k=0: X[0] = E[0]+O[0] and X[M] = E[0]-O[0] (both purely real).
            cz[0] = (re[0] + re[M]) * (double)0.5;
            sz[0] = (re[0] - re[M]) * (double)0.5;

            // General bins k = 1..M-1.
            // Same algebra as the recurrence irfft, but conj(W_N^k) = (twReFull[k], -twImFull[k]).
            //   E[k] = (X[k] + conj(X[M-k])) / 2
            //   O[k] = (X[k] - conj(X[M-k])) · conj(W_N^k) / 2
            //   Y[k] = E[k] + i·O[k]
            var twReFull = ws.twReFull;
            var twImFull = ws.twImFull;
            var sw1re    = ws.sw1re;
            var sw1im    = ws.sw1im;
            var cw1re    = ws.cw1re;
            var cw1im    = ws.cw1im;
            for (int k = 1; k < M; k++)
            {
                int kr = M - k;
                double xr_k  = re[k],  xi_k  = im[k];
                double xr_kr = re[kr], xi_kr = im[kr];

                // E[k] = (X[k] + conj(X[M-k])) / 2
                double E_re = (xr_k + xr_kr) * (double)0.5;
                double E_im = (xi_k - xi_kr) * (double)0.5;

                // (X[k] - conj(X[M-k])) = a + i·b
                double a = xr_k - xr_kr;
                double b = xi_k + xi_kr;

                // conj(W_N^k) = (twReFull[k], -twImFull[k]).
                // O[k] = (a + i·b) · conj(W_N^k) / 2  →  complex multiply (a+ib)·(cRe+icIm):
                //   real = a·cRe - b·cIm,  imag = b·cRe + a·cIm   (with cIm = -twImFull[k])
                double cRe = twReFull[k];
                double cIm = -twImFull[k];   // negate imaginary part for conjugate
                double O_re = (a * cRe - b * cIm) * (double)0.5;
                double O_im = (b * cRe + a * cIm) * (double)0.5;

                // Y[k] = E[k] + i·O[k]
                cz[k] = E_re - O_im;
                sz[k] = E_im + O_re;
            }

            // One M-point inverse FFT via radix-4 (with full-circle table, tableN = ws.n = N).
            var visitedScratch = ws.visited;
            if (IsPowerOf4(M))
                FftCoreRadix4(ref cz, ref sz, ref twReFull, ref twImFull, ref sw1re, ref sw1im, ws.n, true);
            else
                FftCoreRadix4Mixed(ref cz, ref sz, ref twReFull, ref twImFull, ref sw1re, ref sw1im, ref cw1re, ref cw1im, visitedScratch, ws.n, true);

            // Deinterleave: real[2j] = even[j], real[2j+1] = odd[j].
            for (int j = 0; j < M; j++)
            {
                real[2 * j]     = cz[j];
                real[2 * j + 1] = sz[j];
            }
        }

        // ---- radix-4 DIT FFT ----
        //
        // True radix-4 decimation-in-time for lengths that are exact powers of 4 (log4(n) even bits).
        // Radix-4 halves the number of full-array passes vs radix-2: log4(N) vs log2(N) stages,
        // trading twiddle-table memory (~2× for the full-circle table) against half the pass count.
        //
        // Inverse via conjugate trick: conjugate → forward radix-4 → conjugate + scale (1/N).
        // Permutation: base-4 digit reversal (reverse digit order in base-4 = swap bit-pairs).
        // Butterfly: forward DFT sign convention X[k] = Σ x[n]·exp(-2πi·kn/N).

        // IsPowerOf4 and ReverseBase4Digits live in OpHelpers.Shared.cs (type-agnostic, emitted once).

        // Inner radix-4 butterfly pointer kernel (wide + scalar hybrid).
        // Performs log4(n) stages of radix-4 DIT butterflies on already-permuted data.
        // twr/twi are the full-circle twiddle table of length tableN: T[m] = exp(-2πi·m/tableN).
        // s1r/s1i are the contiguous per-stage W^1 table (ws.sw1re/sw1im): stages with quarter-stride
        // q >= doubleW.Width vectorize across j (Width consecutive j give contiguous wide re/im loads
        // and a contiguous read of s1r/s1i; W^2/W^3 derived in-register), stages with q < Width run
        // scalar from the full-circle table. Both branches perform the exact same scalar butterfly per
        // element, so output is bit-identical to a fully scalar pass.
        // n is the DATA/transform size; tableN is the TABLE size (tableN >= n, both pow-of-4,
        // n divides tableN). Stage-len twiddle W_len^j = T_tableN[j*(tableN/len)] so a single
        // full-size table (and its shared per-stage sw1 slice) drives any sub-transform without copies.
        // All pointer arguments are non-aliasing — [NoAlias] is truthful.
        [MethodImpl(MethodImplOptions.NoInlining)]
        static unsafe void FftCoreRadix4Ptr(
            [NoAlias] double* re, [NoAlias] double* im,
            [NoAlias] double* twr, [NoAlias] double* twi,
            [NoAlias] double* s1r, [NoAlias] double* s1i, int n, int tableN)
        {
            // q = quarter-size per group (stride); starts at 1 and quadruples each stage.
            // sub-transform length = 4q;  step = tableN/(4q) into the full-circle table.
            int W = doubleW.Width;
            int stageOff = 0;   // running offset into the contiguous per-stage sw1 table

            for (int q = 1; q < n; q <<= 2)
            {
                int len  = q << 2;       // 4q
                int step = tableN / len; // twiddle stride: W_len^j = T_tableN[j*step]

                if (q >= W)
                {
                    // Wide stage: q (a power of 4, >= W) is a multiple of W, so no j tail.
                    for (int base_ = 0; base_ < n; base_ += len)
                    {
                        for (int j = 0; j < q; j += W)
                        {
                            int i0 = base_ + j, i1 = i0 + q, i2 = i1 + q, i3 = i2 + q;

                            doubleW Are = doubleW.Load(re + i0, 0), Aim = doubleW.Load(im + i0, 0);

                            // W^1 loaded; W^2 = W^1·W^1, W^3 = W^1·W^2 derived in-register.
                            doubleW w1r = doubleW.Load(s1r + stageOff + j, 0), w1i = doubleW.Load(s1i + stageOff + j, 0);
                            doubleW w2r = w1r * w1r - w1i * w1i, w2i = w1r * w1i + w1i * w1r;
                            doubleW w3r = w1r * w2r - w1i * w2i, w3i = w1r * w2i + w1i * w2r;

                            doubleW x1r = doubleW.Load(re + i1, 0), x1i = doubleW.Load(im + i1, 0);
                            doubleW Bre = w1r * x1r - w1i * x1i;
                            doubleW Bim = w1r * x1i + w1i * x1r;

                            doubleW x2r = doubleW.Load(re + i2, 0), x2i = doubleW.Load(im + i2, 0);
                            doubleW Cre = w2r * x2r - w2i * x2i;
                            doubleW Cim = w2r * x2i + w2i * x2r;

                            doubleW x3r = doubleW.Load(re + i3, 0), x3i = doubleW.Load(im + i3, 0);
                            doubleW Dre = w3r * x3r - w3i * x3i;
                            doubleW Dim = w3r * x3i + w3i * x3r;

                            doubleW T0re = Are + Cre, T0im = Aim + Cim;
                            doubleW T1re = Are - Cre, T1im = Aim - Cim;
                            doubleW T2re = Bre + Dre, T2im = Bim + Dim;
                            doubleW T3re = Bre - Dre, T3im = Bim - Dim;

                            doubleW.Store(re + i0, 0, T0re + T2re); doubleW.Store(im + i0, 0, T0im + T2im);
                            doubleW.Store(re + i2, 0, T0re - T2re); doubleW.Store(im + i2, 0, T0im - T2im);
                            doubleW.Store(re + i1, 0, T1re + T3im); doubleW.Store(im + i1, 0, T1im - T3re);
                            doubleW.Store(re + i3, 0, T1re - T3im); doubleW.Store(im + i3, 0, T1im + T3re);
                        }
                    }
                    stageOff += q;
                }
                else
                {
                    // Small stage (q < Width): scalar, reading the full-circle table directly.
                    for (int base_ = 0; base_ < n; base_ += len)
                    {
                        for (int j = 0; j < q; j++)
                        {
                            int i0 = base_ + j, i1 = i0 + q, i2 = i1 + q, i3 = i2 + q;
                            int tw1 = j * step, tw2 = tw1 + tw1, tw3 = tw2 + tw1;

                            double A_re = re[i0], A_im = im[i0];
                            double w1r = twr[tw1], w1i = twi[tw1];
                            double B_re = w1r * re[i1] - w1i * im[i1];
                            double B_im = w1r * im[i1] + w1i * re[i1];
                            double w2r = twr[tw2], w2i = twi[tw2];
                            double C_re = w2r * re[i2] - w2i * im[i2];
                            double C_im = w2r * im[i2] + w2i * re[i2];
                            double w3r = twr[tw3], w3i = twi[tw3];
                            double D_re = w3r * re[i3] - w3i * im[i3];
                            double D_im = w3r * im[i3] + w3i * re[i3];

                            double T0_re = A_re + C_re, T0_im = A_im + C_im;
                            double T1_re = A_re - C_re, T1_im = A_im - C_im;
                            double T2_re = B_re + D_re, T2_im = B_im + D_im;
                            double T3_re = B_re - D_re, T3_im = B_im - D_im;

                            re[i0] = T0_re + T2_re; im[i0] = T0_im + T2_im;
                            re[i2] = T0_re - T2_re; im[i2] = T0_im - T2_im;
                            re[i1] = T1_re + T3_im; im[i1] = T1_im - T3_re;
                            re[i3] = T1_re - T3_im; im[i3] = T1_im + T3_re;
                        }
                    }
                }
            }
        }

        // Outer radix-4 DIT core: permutation + conjugate trick + pointer kernel + inverse scale.
        // Transform size is re.N (must be a power of 4, caller guarantees).
        // tableN is the length of the twiddle table (must be a multiple of re.N; == re.N for top-level
        // callers, > re.N when called from FftCoreRadix4Mixed or rfft to drive a sub-transform).
        // sw1re/sw1im are the workspace's contiguous per-stage W^1 table for the wide butterfly.
        static unsafe void FftCoreRadix4(ref doubleN re, ref doubleN im,
                                         ref doubleN twReFull, ref doubleN twImFull,
                                         ref doubleN sw1re, ref doubleN sw1im,
                                         int tableN, bool inverse)
        {
            int size = re.N;
            if (size == 1) return;

            // Conjugate trick (see section banner above).
            if (inverse)
                for (int i = 0; i < size; i++)
                    im[i] = -im[i];

            // Digit reversal + butterfly stages via shared slice helper.
            double* rePtr  = re.Data.Ptr;
            double* imPtr  = im.Data.Ptr;
            double* twrPtr = twReFull.Data.Ptr;
            double* twiPtr = twImFull.Data.Ptr;
            double* s1rPtr = sw1re.Data.Ptr;
            double* s1iPtr = sw1im.Data.Ptr;
            FftCoreRadix4Slice(rePtr, imPtr, twrPtr, twiPtr, s1rPtr, s1iPtr, size, tableN);

            if (inverse)
            {
                double invN = (double)1 / (double)size;
                for (int i = 0; i < size; i++)
                {
                    re[i] =  re[i] * invN;
                    im[i] = -im[i] * invN;   // undo conjugate, apply 1/N scale
                }
            }
        }

        // Shared helper: base-4 digit reversal + butterfly on a raw pointer slice of length `size`.
        // re/im are already offset to the start of the sub-array; twr/twi are the full-circle
        // twiddle table (length tableN, shared across calls — read-only inside FftCoreRadix4Ptr);
        // s1r/s1i are the workspace's contiguous per-stage W^1 table (shared across sub-transforms
        // because they share tableN). size must be a power of 4; tableN must be a multiple of size.
        static unsafe void FftCoreRadix4Slice(
            double* re, double* im,
            double* twr, double* twi,
            double* s1r, double* s1i,
            int size, int tableN)
        {
            if (size <= 1) return;

            // Base-4 digit reversal on this slice.
            int log4n = 0;
            for (int t = size; t > 1; t >>= 2) log4n++;

            for (int i = 0; i < size; i++)
            {
                int j = ReverseBase4Digits(i, log4n);
                if (j > i)
                {
                    double tr = re[i]; re[i] = re[j]; re[j] = tr;
                    double ti = im[i]; im[i] = im[j]; im[j] = ti;
                }
            }

            // Butterfly stages.
            FftCoreRadix4Ptr(re, im, twr, twi, s1r, s1i, size, tableN);
        }

        // Mixed-radix DIT for N = 2·4^k (IsPow2(N) && !IsPowerOf4(N)).
        // Transform size is re.N; tableN is the twiddle table length (>= re.N, multiple of re.N).
        // One radix-2 level wraps two size-M = re.N/2 radix-4 sub-FFTs; M is always a power of 4.
        // Inverse via conjugate trick at the OUTER level — sub-FFTs always run forward.
        //
        // In-place implementation — no doubleN Temp allocations.
        // Step 1: de-interleave in-place via cycle-following (bool visited scratch, N bytes).
        // Step 2: two radix-4 sub-FFTs on the contiguous even/odd halves via FftCoreRadix4Slice.
        // Step 3: radix-2 DIT combine, writing natural-order output back in-place.
        // Combine twiddle: W_size^k = T_tableN[k*(tableN/size)].
        // visited is a workspace scratch of length >= size (0/1 flags, double-typed).
        // The caller passes ws.visited (length n); only [0, size) is used, cleared at entry.
        static unsafe void FftCoreRadix4Mixed(ref doubleN re, ref doubleN im,
                                              ref doubleN twReFull, ref doubleN twImFull,
                                              ref doubleN sw1re, ref doubleN sw1im,
                                              ref doubleN cw1re, ref doubleN cw1im,
                                              doubleN visited,
                                              int tableN, bool inverse)
        {
            int size = re.N;
            int M = size >> 1;   // size/2, always a power of 4

            // Conjugate trick at the outer level (see banner above).
            if (inverse)
                for (int i = 0; i < size; i++)
                    im[i] = -im[i];

            // Step 1: In-place de-interleave (unshuffle) via cycle-following.
            // dst(i) = i/2 if i is even; M + i/2 if i is odd.
            // After the permutation: [0,M) holds even-indexed elements, [M,2M) holds odd-indexed,
            // both in natural order — exactly what FftCoreRadix4Slice expects as input.
            // Cycle-following uses the workspace visited scratch (0 = unvisited, 1 = visited).
            // Clear [0, size) — workspace is reused across calls so it must be zeroed each time.
            for (int i = 0; i < size; i++)
                visited[i] = (double)0;

            for (int s = 0; s < size; s++)
            {
                if (visited[s] != (double)0) continue;
                visited[s] = (double)1;

                int j = (s & 1) == 0 ? (s >> 1) : (M + (s >> 1));
                if (j == s) continue;   // fixed point (s==0 or s==size-1)

                double carryRe = re[s], carryIm = im[s];
                while (j != s)
                {
                    double tmpRe = re[j], tmpIm = im[j];
                    re[j] = carryRe;
                    im[j] = carryIm;
                    visited[j] = (double)1;
                    carryRe = tmpRe;
                    carryIm = tmpIm;
                    j = (j & 1) == 0 ? (j >> 1) : (M + (j >> 1));
                }
                re[s] = carryRe;
                im[s] = carryIm;
            }

            // Step 2: Two in-place radix-4 sub-FFTs on the contiguous halves (no temp copy).
            // FftCoreRadix4Ptr twiddle indexing: W_M^j = T_tableN[j*(tableN/M)] via step=tableN/len,
            // so the full-size table drives the sub-transforms correctly — no sub-table copies needed.
            double* rePtr  = re.Data.Ptr;
            double* imPtr  = im.Data.Ptr;
            double* twrPtr = twReFull.Data.Ptr;
            double* twiPtr = twImFull.Data.Ptr;
            double* s1rPtr = sw1re.Data.Ptr;
            double* s1iPtr = sw1im.Data.Ptr;

            FftCoreRadix4Slice(rePtr,     imPtr,     twrPtr, twiPtr, s1rPtr, s1iPtr, M, tableN);
            FftCoreRadix4Slice(rePtr + M, imPtr + M, twrPtr, twiPtr, s1rPtr, s1iPtr, M, tableN);

            // Step 3: Radix-2 DIT combine (wide + scalar hybrid).
            //   X[k]   = E[k] + W_size^k * O[k]
            //   X[k+M] = E[k] - W_size^k * O[k]
            // The combine twiddle W_size^k = T_tableN[k*(tableN/size)] is pre-gathered contiguously
            // into cw1r/cw1i (ws.cw1re/cw1im) so k indexes it directly: Width consecutive k give
            // contiguous wide loads of the twiddles AND the E/O data (re[k],im[k],re[M+k],im[M+k]).
            // The scalar tail handles the M < Width remainder (M is a power of 4, so no partial
            // wide iteration once M >= Width). Bit-identical to the scalar combine per element.
            double* cw1r = cw1re.Data.Ptr;
            double* cw1i = cw1im.Data.Ptr;
            int Wc = doubleW.Width;
            int k = 0;
            for (; k + Wc <= M; k += Wc)
            {
                doubleW wr = doubleW.Load(cw1r + k, 0), wi = doubleW.Load(cw1i + k, 0);
                doubleW er  = doubleW.Load(rePtr + k, 0),     ei  = doubleW.Load(imPtr + k, 0);
                doubleW or_ = doubleW.Load(rePtr + M + k, 0), oi_ = doubleW.Load(imPtr + M + k, 0);
                doubleW tr  = wr * or_ - wi * oi_;
                doubleW ti  = wr * oi_ + wi * or_;
                doubleW.Store(rePtr + k, 0,     er + tr); doubleW.Store(imPtr + k, 0,     ei + ti);
                doubleW.Store(rePtr + M + k, 0, er - tr); doubleW.Store(imPtr + M + k, 0, ei - ti);
            }
            for (; k < M; k++)
            {
                double wr = cw1r[k], wi = cw1i[k];
                double er  = rePtr[k],     ei  = imPtr[k];
                double or_ = rePtr[M + k], oi_ = imPtr[M + k];
                double tr  = wr * or_ - wi * oi_;
                double ti  = wr * oi_ + wi * or_;
                rePtr[k]     = er + tr; imPtr[k]     = ei + ti;
                rePtr[M + k] = er - tr; imPtr[M + k] = ei - ti;
            }

            if (inverse)
            {
                double invN = (double)1 / (double)size;
                for (int i = 0; i < size; i++)
                {
                    re[i] =  re[i] * invN;
                    im[i] = -im[i] * invN;   // undo conjugate, apply 1/N scale
                }
            }
        }

    }
}
