// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/Fit.Geometry.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;

using Unity.Collections;
using Unity.Mathematics;

using BULA.ML;



namespace BULA
{
    // ================================================================================================
    // Fitting geometry to point clouds, parameterized by the METRIC.
    //
    // Every entry point comes in two forms: a plain overload minimizing squared orthogonal distance
    // (closed form, no iteration) and a generic overload taking an <see cref="IfloatRobustLoss"/>
    // that reweights by residual -- floatL1Loss, floatHuberLoss, floatCauchyLoss, floatTukeyLoss.
    // The robust form is IRLS: reweight, refit, repeat. Each iteration is one weighted covariance
    // (O(n·d²)) plus one d x d eigensolve, d in {2,3,4}, so cost is dominated by the point count.
    //
    // Job-safe: scratch is Allocator.Temp, disposed before returning.
    // ================================================================================================
    public static partial class Fit
    {
        // ============================================================================================
        // LINE -- the best-fit 1-D affine subspace (minimizes distance PERPENDICULAR to the line, not
        // vertical residual: this is orthogonal / total-least-squares regression, not y-on-x).
        // ============================================================================================

        /// <summary>
        /// Best-fit line through a 2D point cloud, minimizing squared perpendicular distance.
        /// centroid = mean of points, direction = unit, sign arbitrary. Requires
        /// points.Length &gt;= 2. False means the underlying eigensolve did not converge; direction is
        /// then undefined.
        /// </summary>
        public static bool line(NativeArray<float2> points, out float2 centroid, out float2 direction)
        {
            var l2 = new floatL2Loss();
            return line(points, in l2, out centroid, out direction);
        }

        /// <summary>Best-fit line through a 3D point cloud. See the 2D overload.</summary>
        public static bool line(NativeArray<float3> points, out float3 centroid, out float3 direction)
        {
            var l2 = new floatL2Loss();
            return line(points, in l2, out centroid, out direction);
        }

        /// <summary>Best-fit line through a 4D point cloud. See the 2D overload.</summary>
        public static bool line(NativeArray<float4> points, out float4 centroid, out float4 direction)
        {
            var l2 = new floatL2Loss();
            return line(points, in l2, out centroid, out direction);
        }

        /// <summary>
        /// Best-fit line through a 2D point cloud under <paramref name="loss"/>, by IRLS on the
        /// perpendicular residual. centroid is the WEIGHTED mean, direction the dominant weighted
        /// principal axis (unit, sign arbitrary). Requires points.Length &gt;= 2.
        /// <paramref name="maxIter"/> &lt;= 0 picks a default budget; a redescending loss
        /// (<see cref="floatTukeyLoss"/>) can leave every point zero-weighted from a bad start, which
        /// returns false rather than a fabricated line.
        /// </summary>
        public static bool line<TLoss>(NativeArray<float2> points, in TLoss loss,
                                       out float2 centroid, out float2 direction, int maxIter = 0)
            where TLoss : struct, IfloatRobustLoss
        {
            if (points.Length < 2) throw new ArgumentException("Fit.line: points.Length must be >= 2");

            var flat = points.Reinterpret<float2, float>();
            var mean = new floatN(2, Allocator.Temp);
            var V = new floatMxN(2, 2, Allocator.Temp);

            bool ok = SubspaceIrls(flat, points.Length, 2, 1, in loss, maxIter, ref mean, ref V);
            centroid = new float2(mean[0], mean[1]);
            direction = ok ? new float2(V[0, 0], V[1, 0]) : default;

            mean.Dispose(); V.Dispose();
            return ok;
        }

        /// <summary>Robust best-fit line through a 3D point cloud. See the 2D overload.</summary>
        public static bool line<TLoss>(NativeArray<float3> points, in TLoss loss,
                                       out float3 centroid, out float3 direction, int maxIter = 0)
            where TLoss : struct, IfloatRobustLoss
        {
            if (points.Length < 2) throw new ArgumentException("Fit.line: points.Length must be >= 2");

            var flat = points.Reinterpret<float3, float>();
            var mean = new floatN(3, Allocator.Temp);
            var V = new floatMxN(3, 3, Allocator.Temp);

            bool ok = SubspaceIrls(flat, points.Length, 3, 1, in loss, maxIter, ref mean, ref V);
            centroid = new float3(mean[0], mean[1], mean[2]);
            direction = ok ? new float3(V[0, 0], V[1, 0], V[2, 0]) : default;

            mean.Dispose(); V.Dispose();
            return ok;
        }

        /// <summary>Robust best-fit line through a 4D point cloud. See the 2D overload.</summary>
        public static bool line<TLoss>(NativeArray<float4> points, in TLoss loss,
                                       out float4 centroid, out float4 direction, int maxIter = 0)
            where TLoss : struct, IfloatRobustLoss
        {
            if (points.Length < 2) throw new ArgumentException("Fit.line: points.Length must be >= 2");

            var flat = points.Reinterpret<float4, float>();
            var mean = new floatN(4, Allocator.Temp);
            var V = new floatMxN(4, 4, Allocator.Temp);

            bool ok = SubspaceIrls(flat, points.Length, 4, 1, in loss, maxIter, ref mean, ref V);
            centroid = new float4(mean[0], mean[1], mean[2], mean[3]);
            direction = ok ? new float4(V[0, 0], V[1, 0], V[2, 0], V[3, 0]) : default;

            mean.Dispose(); V.Dispose();
            return ok;
        }

        // ============================================================================================
        // PLANE -- the best-fit (d-1)-dimensional affine subspace, reported by its unit normal.
        // ============================================================================================

        /// <summary>
        /// Best-fit plane through a 3D point cloud, minimizing squared perpendicular distance.
        /// centroid = mean of points, normal = unit, sign arbitrary. Requires points.Length &gt;= 3.
        /// False means the underlying eigensolve did not converge; normal is then undefined.
        /// </summary>
        public static bool plane(NativeArray<float3> points, out float3 centroid, out float3 normal)
        {
            var l2 = new floatL2Loss();
            return plane(points, in l2, out centroid, out normal);
        }

        /// <summary>
        /// Best-fit plane through a 3D point cloud under <paramref name="loss"/>, by IRLS on the
        /// perpendicular residual. centroid is the WEIGHTED mean, normal the least-variance weighted
        /// principal axis (unit, sign arbitrary). Requires points.Length &gt;= 3. See
        /// <see cref="line{TLoss}(NativeArray{float2}, in TLoss, out float2, out float2, int)"/>
        /// for the shared iteration contract.
        /// </summary>
        public static bool plane<TLoss>(NativeArray<float3> points, in TLoss loss,
                                        out float3 centroid, out float3 normal, int maxIter = 0)
            where TLoss : struct, IfloatRobustLoss
        {
            if (points.Length < 3) throw new ArgumentException("Fit.plane: points.Length must be >= 3");

            var flat = points.Reinterpret<float3, float>();
            var mean = new floatN(3, Allocator.Temp);
            var V = new floatMxN(3, 3, Allocator.Temp);

            bool ok = SubspaceIrls(flat, points.Length, 3, 2, in loss, maxIter, ref mean, ref V);
            centroid = new float3(mean[0], mean[1], mean[2]);
            normal = ok ? new float3(V[0, 2], V[1, 2], V[2, 2]) : default;

            mean.Dispose(); V.Dispose();
            return ok;
        }

        // ============================================================================================
        // The shared IRLS core: weighted centroid + weighted covariance eigendecomposition.
        //
        // Fits the affine subspace of dimension `k` through the n x d cloud X (row i = point i).
        // On return `mean` is the weighted centroid and V's COLUMNS are the weighted principal axes,
        // eigenvalues descending -- so the subspace is span(V[:,0..k-1]) and its orthogonal complement
        // is span(V[:,k..d-1]). The residual driving the reweighting is the distance from a point to
        // that subspace: r² = ‖q‖² − Σ_{j<k} (q·v_j)², q = x_i − mean.
        //
        // floatL2Loss has RhoPrime == 1, so the weights never move and this exits after one pass --
        // identical to plain PCA, which is why the non-generic overloads forward there directly.
        // ============================================================================================
        static bool SubspaceIrls<TLoss>(NativeArray<float> X, int n, int d, int k,
                                        in TLoss loss, int maxIter,
                                        ref floatN mean, ref floatMxN V)
            where TLoss : struct, IfloatRobustLoss
        {
            if (maxIter <= 0) maxIter = DefaultIrlsIter;

            var w = new floatN(n, Allocator.Temp);
            var C = new floatMxN(d, d, Allocator.Temp);
            var eig = new floatN(d, Allocator.Temp);
            for (int i = 0; i < n; i++) w[i] = (float)1;

            bool ok = false;
            for (int it = 0; it < maxIter; it++)
            {
                float sw = (float)0;
                for (int j = 0; j < d; j++) mean[j] = (float)0;
                for (int i = 0; i < n; i++)
                {
                    float wi = w[i];
                    sw += wi;
                    for (int j = 0; j < d; j++) mean[j] += wi * X[i * d + j];
                }
                if (!(sw > (float)0)) { ok = false; break; }   // every point rejected (redescending loss)
                for (int j = 0; j < d; j++) mean[j] /= sw;

                for (int a = 0; a < d; a++)
                    for (int b = 0; b < d; b++) C[a, b] = (float)0;
                for (int i = 0; i < n; i++)
                {
                    float wi = w[i];
                    for (int a = 0; a < d; a++)
                    {
                        float qa = X[i * d + a] - mean[a];
                        for (int b = 0; b < d; b++) C[a, b] += wi * qa * (X[i * d + b] - mean[b]);
                    }
                }
                for (int a = 0; a < d; a++)
                    for (int b = 0; b < d; b++) C[a, b] /= sw;

                ok = Eigen.symmetricInPlace(ref C, ref eig, ref V);   // DESTROYS C; rebuilt above each pass
                if (!ok) break;

                float maxDelta = (float)0;
                for (int i = 0; i < n; i++)
                {
                    float q2 = (float)0;
                    for (int a = 0; a < d; a++)
                    {
                        float qa = X[i * d + a] - mean[a];
                        q2 += qa * qa;
                    }

                    float inSub = (float)0;
                    for (int j = 0; j < k; j++)
                    {
                        float dp = (float)0;
                        for (int a = 0; a < d; a++) dp += (X[i * d + a] - mean[a]) * V[a, j];
                        inSub += dp * dp;
                    }

                    float wNew = loss.RhoPrime(math.max(q2 - inSub, (float)0));
                    maxDelta = math.max(maxDelta, math.abs(wNew - w[i]));
                    w[i] = wNew;
                }

                if (maxDelta <= Consts.floatSqrtEps) break;
            }

            w.Dispose(); C.Dispose(); eig.Dispose();
            return ok;
        }
    }
}
