// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/Kalman.UKF.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;

using Unity.Collections;
using Unity.Mathematics;

namespace LinearAlgebra
{
    // ================================================================================================
    // Unscented Kalman Filter (UKF): Van der Merwe scaled sigma points + the unscented transform, over
    // the SAME IdoubleKFModel/IdoubleKFMeasurement functors ekfPredict/ekfUpdate use -- but calling
    // ONLY F/H (JacobianF/JacobianH are never read; no linearization at all is the whole point).
    //
    // Algorithm reference: FilterPy (rlabbe/filterpy, MIT) -- MerweScaledSigmaPoints (lambda =
    // alpha^2(n+kappa)-n; point 0 = mean; points 1..n = mean + sqrt(n+lambda)*col_k(chol(P)); points
    // n+1..2n = mean - same; Wm[0]=lambda/(n+lambda), Wc[0]=Wm[0]+(1-alpha^2+beta), every other
    // weight = 1/(2(n+lambda))) and UnscentedKalmanFilter's predict/update recombination (weighted
    // mean, weighted-outer-product covariance, cross-covariance Pxz, K = Pxz*Pzz^-1, x += Ky,
    // P -= K*Pzz*Kᵀ).
    //
    // TWO deliberate deviations from FilterPy, both documented at their call site:
    //   1. Sigma points are regenerated FRESH at the start of BOTH ukfPredict and ukfUpdate (FilterPy
    //      reuses predict's propagated sigmas directly in update, a documented perf shortcut) -- see
    //      GenerateSigmaPoints's own doc comment for why.
    //   2. Default alpha=1 (not the classic ~1e-3) -- see doubleUKFCache's own doc comment for the
    //      float32 cancellation evidence.
    //
    // The sigma-point spread uses CHOP (rank-revealing pivoted Cholesky), not a plain Cholesky: a
    // rank-deficient P degrades to a DEGENERATE (duplicated-at-the-mean) sigma spread along the null
    // directions instead of FilterPy's hard failure, and an Indefinite P (numerically broken) falls
    // back to the same all-degenerate spread rather than reading an undefined factor.
    //
    // K is NEVER formed via an explicit Pzz inverse: ukfUpdate solves the TRANSPOSED system
    // Pzz·Kᵀ = Pxzᵀ via CHOP, exactly like the linear/EKF UpdateCore.
    //
    // Wc[0] can be NEGATIVE (alpha < 1) -- the classic scaled-UKF pitfall, since the recombined
    // covariance is a WEIGHTED SUM of outer products, not a Joseph-form product guaranteed PSD
    // regardless of gain. Both ukfPredict and ukfUpdate symmetrize explicitly; this library's default
    // alpha=1 keeps Wc[0] non-negative for kappa=0, but a caller-chosen smaller alpha can still drive
    // the recombination indefinite in principle (mitigated, not eliminated, by the defaults).
    // ================================================================================================
    public static partial class Kalman
    {
        // Regenerates cache.X (the (2n+1) x n sigma points) from the CURRENT (x, P), via CHOP's
        // pivoted Cholesky. CHOP factors P^T·P_cov·P = L·Lᵀ (P_cov the covariance, P the pivot
        // permutation -- unfortunate letter clash with the state covariance, disambiguated here as
        // "the permutation" everywhere else): the sigma-spread vectors are the COLUMNS of the
        // UNPERMUTED factor, i.e. column k of L scattered back through the permutation
        // (v[Piv[i]] = L[i,k]) -- L's own columns are in PIVOTED order, not the original one.
        //
        // On CHOP.Indefinite (P not even PSD -- a numerically broken covariance), every sigma point
        // collapses to the mean (v = 0) rather than reading L's undefined contents; on a rank-
        // deficient PSD P, CHOP's own contract already zero-fills L's columns past the detected rank,
        // so the same "collapse to the mean" degeneracy falls out for those columns with no special
        // casing here.
        //
        // Called FRESH at the start of BOTH ukfPredict and ukfUpdate (not cached across the two calls
        // the way FilterPy's UnscentedKalmanFilter reuses predict's propagated sigmas in update) --
        // this keeps ukfUpdate self-contained and safe to call more than once per ukfPredict (the
        // same multi-sensor-fusion pattern Kalman.update already supports), at the cost of one extra
        // Cholesky per ukfUpdate call. Mathematically identical to FilterPy's own result whenever
        // update immediately follows predict with nothing else in between (the common case).
        static void GenerateSigmaPoints(in doubleN x, in doubleMxN P, ref doubleUKFCache cache)
        {
            int n = cache.N;
            var rinfo = CHOP.decomp(in P, ref cache.L, ref cache.Piv, ref cache.chopWs);
            bool solved = rinfo.Solved;
            double scale = math.sqrt((double)n + cache.lambda);

            for (int i = 0; i < n; i++) cache.X[0, i] = x[i];

            for (int k = 0; k < n; k++)
            {
                for (int i = 0; i < n; i++) cache.diff[i] = 0;
                if (solved)
                {
                    for (int i = 0; i < n; i++)
                        cache.diff[cache.Piv[i]] = cache.L[i, k] * scale;
                }
                for (int i = 0; i < n; i++)
                {
                    double d = cache.diff[i];
                    cache.X[k + 1, i] = x[i] + d;
                    cache.X[n + k + 1, i] = x[i] - d;
                }
            }
        }

        /// <summary>
        /// UKF predict: regenerates sigma points from (x, P) (see <see cref="GenerateSigmaPoints"/>),
        /// propagates each through <c>model.F</c> (JacobianF is never called), then sets x/P to the
        /// weighted mean/covariance (+ Q, symmetrized) of the propagated points. Zero
        /// <c>Allocator.Temp</c> use -- every intermediate is a field of <paramref name="cache"/>.
        /// </summary>
        /// <param name="s">Must be constructed via <c>new doubleKFState(n, mMax, allocator)</c>.</param>
        /// <param name="cache">Must be constructed via <c>new doubleUKFCache(n, ...)</c> for the SAME n.</param>
        /// <param name="Q">Process noise covariance, n x n.</param>
        public static void ukfPredict<TModel>(ref doubleKFState s, ref doubleUKFCache cache,
                                              in TModel model, in doubleN u, in doubleMxN Q)
            where TModel : struct, IdoubleKFModel
        {
            if (!s.IsCreated)
                throw new ArgumentException("Kalman.ukfPredict: state must be constructed via new doubleKFState(n, mMax, allocator)");
            if (!cache.IsValid(s.N))
                throw new ArgumentException("Kalman.ukfPredict: cache must be constructed via new doubleUKFCache(n, ...) matching state dimension");
            if (!Q.IsSquare || Q.M_Rows != s.N)
                throw new ArgumentException("Kalman.ukfPredict: Q must be n x n");

            int n = s.N;
            int npts = 2 * n + 1;

            GenerateSigmaPoints(in s.x, in s.P, ref cache);

            for (int k = 0; k < npts; k++)
            {
                for (int i = 0; i < n; i++) cache.rowIn[i] = cache.X[k, i];
                model.F(in cache.rowIn, in u, ref cache.rowOut);
                for (int i = 0; i < n; i++) cache.Y[k, i] = cache.rowOut[i];
            }

            for (int i = 0; i < n; i++) cache.xPred[i] = 0;
            for (int k = 0; k < npts; k++)
            {
                double w = cache.Wm[k];
                for (int i = 0; i < n; i++) cache.xPred[i] += w * cache.Y[k, i];
            }

            for (int i = 0; i < n; i++)
                for (int j = 0; j < n; j++)
                    cache.Pacc[i, j] = 0;
            for (int k = 0; k < npts; k++)
            {
                for (int i = 0; i < n; i++) cache.diff[i] = cache.Y[k, i] - cache.xPred[i];
                double w = cache.Wc[k];
                for (int i = 0; i < n; i++)
                    for (int j = 0; j < n; j++)
                        cache.Pacc[i, j] += w * cache.diff[i] * cache.diff[j];
            }
            cache.Pacc.addInPlace(Q);
            Control.SymmetrizeInPlace(ref cache.Pacc);

            s.x.Data.CopyFrom(cache.xPred.Data);
            s.P.Data.CopyFrom(cache.Pacc.Data);
        }

        /// <summary>
        /// UKF update: regenerates sigma points from the CURRENT (x, P) (see
        /// <see cref="GenerateSigmaPoints"/> for why this is fresh, not reused from the last
        /// <c>ukfPredict</c>), propagates each through <c>meas.H</c> (JacobianH is never called),
        /// forms the innovation covariance Pzz = Σ Wc·outer(dz,dz) + R and cross-covariance
        /// Pxz = Σ Wc·outer(dx,dz), solves K = Pxz·Pzz⁻¹ via CHOP on the transposed system (never an
        /// explicit inverse), then x += Ky and P -= Pxz·Kᵀ (symmetrized). Allocates small
        /// <c>Allocator.Temp</c> scratch sized to <c>z.N</c> (arbitrary per call, same convention as
        /// <see cref="update"/>). On Pzz not even PSD (Indefinite), x/P are left UNCHANGED and
        /// <see cref="KFStatus.InnovationSolveFailed"/> is reported.
        /// </summary>
        /// <param name="R">Measurement noise covariance, m x m (m = z.N).</param>
        public static KFInfo ukfUpdate<TMeas>(ref doubleKFState s, ref doubleUKFCache cache,
                                              in TMeas meas, in doubleMxN R, in doubleN z)
            where TMeas : struct, IdoubleKFMeasurement
        {
            if (!s.IsCreated)
                throw new ArgumentException("Kalman.ukfUpdate: state must be constructed via new doubleKFState(n, mMax, allocator)");
            if (!cache.IsValid(s.N))
                throw new ArgumentException("Kalman.ukfUpdate: cache must be constructed via new doubleUKFCache(n, ...) matching state dimension");
            int m = z.N;
            if (!R.IsSquare || R.M_Rows != m)
                throw new ArgumentException("Kalman.ukfUpdate: R must be m x m (m = z.N)");

            int n = s.N;
            int npts = 2 * n + 1;

            GenerateSigmaPoints(in s.x, in s.P, ref cache);

            var zRow = new doubleN(m, Allocator.Temp);
            var Z = new doubleMxN(npts, m, Allocator.Temp);
            for (int k = 0; k < npts; k++)
            {
                for (int i = 0; i < n; i++) cache.rowIn[i] = cache.X[k, i];
                meas.H(in cache.rowIn, ref zRow);
                for (int j = 0; j < m; j++) Z[k, j] = zRow[j];
            }
            zRow.Dispose();

            var zPred = new doubleN(m, Allocator.Temp);
            for (int j = 0; j < m; j++) zPred[j] = 0;
            for (int k = 0; k < npts; k++)
            {
                double w = cache.Wm[k];
                for (int j = 0; j < m; j++) zPred[j] += w * Z[k, j];
            }

            var Pzz = new doubleMxN(m, m, Allocator.Temp);
            var Pxz = new doubleMxN(n, m, Allocator.Temp);
            for (int i = 0; i < m; i++) for (int j = 0; j < m; j++) Pzz[i, j] = 0;
            for (int i = 0; i < n; i++) for (int j = 0; j < m; j++) Pxz[i, j] = 0;

            var dz = new doubleN(m, Allocator.Temp);
            for (int k = 0; k < npts; k++)
            {
                for (int i = 0; i < n; i++) cache.diff[i] = cache.X[k, i] - s.x[i];
                for (int j = 0; j < m; j++) dz[j] = Z[k, j] - zPred[j];
                double w = cache.Wc[k];
                for (int i = 0; i < m; i++)
                    for (int j = 0; j < m; j++)
                        Pzz[i, j] += w * dz[i] * dz[j];
                for (int i = 0; i < n; i++)
                    for (int j = 0; j < m; j++)
                        Pxz[i, j] += w * cache.diff[i] * dz[j];
            }
            Pzz.addInPlace(R);
            Control.SymmetrizeInPlace(ref Pzz);
            dz.Dispose();

            var y = new doubleN(m, Allocator.Temp);
            y.Data.CopyFrom(z.Data);
            y.addScaledInPlace((double)(-1), zPred);
            double innovationNorm = math.sqrt((double)Blas.dot(y, y));

            var Pxzt = new doubleMxN(m, n, Allocator.Temp);
            Blas.trans(in Pxz, ref Pxzt);

            var L = new doubleMxN(m, m, Allocator.Temp);
            var Piv = new Pivot(m, Allocator.Temp);
            var rinfo = CHOP.decomp(in Pzz, ref L, ref Piv);

            KFStatus status;
            if (rinfo.Solved)
            {
                CHOP.decompSolve(ref L, in Piv, rinfo.rank, ref Pxzt);   // Pxzt := Pzz^-1 Pxzᵀ = Kᵀ

                var K = new doubleMxN(n, m, Allocator.Temp);
                Blas.trans(in Pxzt, ref K);
                var Ky = new doubleN(n, Allocator.Temp);
                Blas.dot(in K, in y, ref Ky);
                s.x.addScaledInPlace((double)1, Ky);

                var PxzK = new doubleMxN(n, n, Allocator.Temp);
                Blas.dot(in Pxz, in Pxzt, ref PxzK);   // Pxz * Kᵀ (Pxzt == Kᵀ)
                s.P.subInPlace(PxzK);
                Control.SymmetrizeInPlace(ref s.P);

                status = KFStatus.Ok;

                K.Dispose(); Ky.Dispose(); PxzK.Dispose();
            }
            else
            {
                status = KFStatus.InnovationSolveFailed;
            }

            L.Dispose(); Piv.Dispose(); Pxzt.Dispose(); y.Dispose();
            Pzz.Dispose(); Pxz.Dispose(); zPred.Dispose(); Z.Dispose();

            return new KFInfo { status = status, innovationNorm = innovationNorm };
        }
    }
}
