// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/Krylov.PBiCGStab.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using Unity.Mathematics;
using LinearAlgebra.Sparse;

namespace LinearAlgebra
{
    public static partial class Krylov
    {
        /// <summary>
        /// Right-preconditioned BiCGSTAB (van der Vorst): solves A x = b for a general square A
        /// with preconditioner M ≈ A (M⁻¹ applied via <typeparamref name="TPre"/>). Same contract
        /// as <see cref="biCGStab{TOp}"/> — warm-startable x, true-residual convergence test,
        /// breakdown statuses — plus two extra scratch vectors pHat/sHat for the preconditioned
        /// directions.
        /// </summary>
        public static SolveInfo pbiCGStab<TOp, TPre>(in TOp A, in TPre M, in floatN b, ref floatN x,
                                         ref floatN r, ref floatN rHat0, ref floatN p, ref floatN v, ref floatN t,
                                         ref floatN pHat, ref floatN sHat,
                                         int maxIter, float tol)
            where TOp : struct, IfloatLinearOperator
            where TPre : struct, IfloatPreconditioner
        {
            if (A.Rows != A.Cols)
                throw new ArgumentException("pbiCGStab: A must be square");
            if (b.N != A.Rows || x.N != A.Rows || r.N != A.Rows || rHat0.N != A.Rows ||
                p.N != A.Rows || v.N != A.Rows || t.N != A.Rows || pHat.N != A.Rows || sHat.N != A.Rows)
                throw new ArgumentException("pbiCGStab: all vectors must have length A.Rows");
            if (maxIter < 1)
                throw new ArgumentException("pbiCGStab: maxIter must be >= 1");

            unsafe
            {
                long* ptrs = stackalloc long[9];
                ptrs[0] = (long)r.Data.Ptr; ptrs[1] = (long)rHat0.Data.Ptr; ptrs[2] = (long)p.Data.Ptr;
                ptrs[3] = (long)v.Data.Ptr; ptrs[4] = (long)t.Data.Ptr; ptrs[5] = (long)x.Data.Ptr;
                ptrs[6] = (long)b.Data.Ptr; ptrs[7] = (long)pHat.Data.Ptr; ptrs[8] = (long)sHat.Data.Ptr;
                RequireDistinctBuffers("pbiCGStab: r/rHat0/p/v/t/x/b/pHat/sHat must be distinct", ptrs, 9);
            }

            float bb = Blas.dot(b, b);
            if (bb == (float)0)
            {
                x.Data.CopyFrom(b.Data);
                return MakeSolveInfo(IterativeSolveStatus.Converged, 0, (float)0);
            }

            A.Apply(in x, ref v);
            r.Data.CopyFrom(b.Data);
            r.addScaledInPlace((float)(-1), v);

            float threshold = tol * tol * bb;
            float rr = Blas.dot(r, r);
            if (rr <= threshold)
                return MakeSolveInfo(IterativeSolveStatus.Converged, 0, math.sqrt(rr));

            rHat0.Data.CopyFrom(r.Data);
            for (int i = 0; i < A.Rows; i++) { p[i] = (float)0; v[i] = (float)0; }

            float rho = (float)1, alpha = (float)1, omega = (float)1;

            for (int k = 0; k < maxIter; k++)
            {
                float rhoNew = Blas.dot(rHat0, r);
                if (rhoNew == (float)0 || math.isnan(rhoNew))
                    return MakeSolveInfo(IterativeSolveStatus.Breakdown, k, math.sqrt(rr));

                float beta = (rhoNew / rho) * (alpha / omega);
                p.addScaledInPlace(-omega, v);
                p.scaleAddInPlace(beta, r);

                M.Apply(in p, ref pHat);                     // pHat = M^-1 p
                A.Apply(in pHat, ref v);                     // v = A pHat

                float rv = Blas.dot(rHat0, v);
                if (rv == (float)0 || math.isnan(rv))
                    return MakeSolveInfo(IterativeSolveStatus.Breakdown, k, math.sqrt(rr));

                alpha = rhoNew / rv;

                float ss = Blas.axpyNormSq(-alpha, v, ref r);   // r := s
                if (ss <= threshold)
                {
                    x.addScaledInPlace(alpha, pHat);
                    return MakeSolveInfo(IterativeSolveStatus.Converged, k + 1, math.sqrt(ss));
                }

                M.Apply(in r, ref sHat);                     // sHat = M^-1 s
                A.Apply(in sHat, ref t);                     // t = A sHat

                float tt = Blas.dot(t, t);
                if (!(tt > (float)0))
                    return MakeSolveInfo(IterativeSolveStatus.Breakdown, k, math.sqrt(rr));

                omega = Blas.dot(t, r) / tt;
                if (omega == (float)0 || math.isnan(omega))
                    return MakeSolveInfo(IterativeSolveStatus.Breakdown, k, math.sqrt(rr));

                x.addScaledInPlace(alpha, pHat);
                x.addScaledInPlace(omega, sHat);

                rr = Blas.axpyNormSq(-omega, t, ref r);      // r := s - omega t
                if (rr <= threshold)
                    return MakeSolveInfo(IterativeSolveStatus.Converged, k + 1, math.sqrt(rr));

                rho = rhoNew;
            }

            return MakeSolveInfo(IterativeSolveStatus.MaxIterations, maxIter, math.sqrt(rr));
        }

        /// <summary>
        /// ILU(0)-preconditioned BiCGSTAB over a block-sparse (BSR) matrix — forwards into
        /// <see cref="pbiCGStab{TOp,TPre}"/> via <c>floatBSROperator</c>.
        /// </summary>
        public static SolveInfo pbiCGStab(in floatBSR A, in floatILU0 M, in floatN b, ref floatN x,
                               int maxIter, float tol)
        {
            floatN r     = b.floatTempVec(A.M_Rows);
            floatN rHat0 = b.floatTempVec(A.M_Rows);
            floatN p     = b.floatTempVec(A.M_Rows);
            floatN v     = b.floatTempVec(A.M_Rows);
            floatN t     = b.floatTempVec(A.M_Rows);
            floatN pHat  = b.floatTempVec(A.M_Rows);
            floatN sHat  = b.floatTempVec(A.M_Rows);
            return pbiCGStab(new floatBSROperator(in A), in M, in b, ref x,
                             ref r, ref rHat0, ref p, ref v, ref t, ref pHat, ref sHat,
                             maxIter, tol);
        }

        /// <summary>ILU(0) BiCGSTAB over BSR with default maxIter (A.M_Rows) and tolerance
        /// (Consts.floatSqrtEps).</summary>
        public static SolveInfo pbiCGStab(in floatBSR A, in floatILU0 M, in floatN b, ref floatN x)
        {
            return pbiCGStab(in A, in M, in b, ref x, A.M_Rows, Consts.floatSqrtEps);
        }
    }
}
