// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/Krylov.PBiCGStab.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using Unity.Mathematics;
using LinearAlgebra.Sparse;

namespace LinearAlgebra
{
    public static partial class Krylov
    {
        /// <summary>
        /// Right-preconditioned BiCGSTAB (van der Vorst): solves A x = b for a general square A
        /// with preconditioner M ≈ A (M⁻¹ applied via <typeparamref name="TPre"/>). Same contract
        /// as <see cref="biCGStab{TOp}"/> — warm-startable x, true-residual convergence test,
        /// breakdown statuses — plus two extra scratch vectors pHat/sHat for the preconditioned
        /// directions.
        /// </summary>
        public static SolveInfo pbiCGStab<TOp, TPre>(in TOp A, in TPre M, in doubleN b, ref doubleN x,
                                         ref doubleN r, ref doubleN rHat0, ref doubleN p, ref doubleN v, ref doubleN t,
                                         ref doubleN pHat, ref doubleN sHat,
                                         int maxIter, double tol)
            where TOp : struct, IdoubleLinearOperator
            where TPre : struct, IdoublePreconditioner
        {
            if (A.Rows != A.Cols)
                throw new ArgumentException("pbiCGStab: A must be square");
            if (b.N != A.Rows || x.N != A.Rows || r.N != A.Rows || rHat0.N != A.Rows ||
                p.N != A.Rows || v.N != A.Rows || t.N != A.Rows || pHat.N != A.Rows || sHat.N != A.Rows)
                throw new ArgumentException("pbiCGStab: all vectors must have length A.Rows");
            if (maxIter < 1)
                throw new ArgumentException("pbiCGStab: maxIter must be >= 1");

            unsafe
            {
                long* ptrs = stackalloc long[9];
                ptrs[0] = (long)r.Data.Ptr; ptrs[1] = (long)rHat0.Data.Ptr; ptrs[2] = (long)p.Data.Ptr;
                ptrs[3] = (long)v.Data.Ptr; ptrs[4] = (long)t.Data.Ptr; ptrs[5] = (long)x.Data.Ptr;
                ptrs[6] = (long)b.Data.Ptr; ptrs[7] = (long)pHat.Data.Ptr; ptrs[8] = (long)sHat.Data.Ptr;
                RequireDistinctBuffers("pbiCGStab: r/rHat0/p/v/t/x/b/pHat/sHat must be distinct", ptrs, 9);
            }

            double bb = Blas.dot(b, b);
            if (bb == (double)0)
            {
                x.Data.CopyFrom(b.Data);
                return MakeSolveInfo(IterativeSolveStatus.Converged, 0, (double)0);
            }

            A.Apply(in x, ref v);
            r.Data.CopyFrom(b.Data);
            r.addScaledInPlace((double)(-1), v);

            double threshold = tol * tol * bb;
            double rr = Blas.dot(r, r);
            if (rr <= threshold)
                return MakeSolveInfo(IterativeSolveStatus.Converged, 0, math.sqrt(rr));

            rHat0.Data.CopyFrom(r.Data);
            for (int i = 0; i < A.Rows; i++) { p[i] = (double)0; v[i] = (double)0; }

            double rho = (double)1, alpha = (double)1, omega = (double)1;

            for (int k = 0; k < maxIter; k++)
            {
                double rhoNew = Blas.dot(rHat0, r);
                if (rhoNew == (double)0 || math.isnan(rhoNew))
                    return MakeSolveInfo(IterativeSolveStatus.Breakdown, k, math.sqrt(rr));

                double beta = (rhoNew / rho) * (alpha / omega);
                p.addScaledInPlace(-omega, v);
                p.scaleAddInPlace(beta, r);

                M.Apply(in p, ref pHat);                     // pHat = M^-1 p
                A.Apply(in pHat, ref v);                     // v = A pHat

                double rv = Blas.dot(rHat0, v);
                if (rv == (double)0 || math.isnan(rv))
                    return MakeSolveInfo(IterativeSolveStatus.Breakdown, k, math.sqrt(rr));

                alpha = rhoNew / rv;

                double ss = Blas.axpyNormSq(-alpha, v, ref r);   // r := s
                if (ss <= threshold)
                {
                    x.addScaledInPlace(alpha, pHat);
                    return MakeSolveInfo(IterativeSolveStatus.Converged, k + 1, math.sqrt(ss));
                }

                M.Apply(in r, ref sHat);                     // sHat = M^-1 s
                A.Apply(in sHat, ref t);                     // t = A sHat

                double tt = Blas.dot(t, t);
                if (!(tt > (double)0))
                    return MakeSolveInfo(IterativeSolveStatus.Breakdown, k, math.sqrt(rr));

                omega = Blas.dot(t, r) / tt;
                if (omega == (double)0 || math.isnan(omega))
                    return MakeSolveInfo(IterativeSolveStatus.Breakdown, k, math.sqrt(rr));

                x.addScaledInPlace(alpha, pHat);
                x.addScaledInPlace(omega, sHat);

                rr = Blas.axpyNormSq(-omega, t, ref r);      // r := s - omega t
                if (rr <= threshold)
                    return MakeSolveInfo(IterativeSolveStatus.Converged, k + 1, math.sqrt(rr));

                rho = rhoNew;
            }

            return MakeSolveInfo(IterativeSolveStatus.MaxIterations, maxIter, math.sqrt(rr));
        }

        /// <summary>
        /// ILU(0)-preconditioned BiCGSTAB over a block-sparse (BSR) matrix — forwards into
        /// <see cref="pbiCGStab{TOp,TPre}"/> via <c>doubleBSROperator</c>.
        /// </summary>
        public static SolveInfo pbiCGStab(in doubleBSR A, in doubleILU0 M, in doubleN b, ref doubleN x,
                               int maxIter, double tol)
        {
            doubleN r     = b.doubleTempVec(A.M_Rows);
            doubleN rHat0 = b.doubleTempVec(A.M_Rows);
            doubleN p     = b.doubleTempVec(A.M_Rows);
            doubleN v     = b.doubleTempVec(A.M_Rows);
            doubleN t     = b.doubleTempVec(A.M_Rows);
            doubleN pHat  = b.doubleTempVec(A.M_Rows);
            doubleN sHat  = b.doubleTempVec(A.M_Rows);
            return pbiCGStab(new doubleBSROperator(in A), in M, in b, ref x,
                             ref r, ref rHat0, ref p, ref v, ref t, ref pHat, ref sHat,
                             maxIter, tol);
        }

        /// <summary>ILU(0) BiCGSTAB over BSR with default maxIter (A.M_Rows) and tolerance
        /// (Consts.doubleSqrtEps).</summary>
        public static SolveInfo pbiCGStab(in doubleBSR A, in doubleILU0 M, in doubleN b, ref doubleN x)
        {
            return pbiCGStab(in A, in M, in b, ref x, A.M_Rows, Consts.doubleSqrtEps);
        }
    }
}
