// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/Krylov.MINRESQLP.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using Unity.Mathematics;
using LinearAlgebra.Internal;
using LinearAlgebra.Sparse;

namespace LinearAlgebra
{
    public static partial class Krylov {

        /// <summary>
        /// MINRES-QLP (Choi, Paige &amp; Saunders 2011) for symmetric (possibly indefinite,
        /// singular, or ill-conditioned) systems A x = b, generic over BOTH the operator
        /// (<see cref="IdoubleLinearOperator"/>) and the preconditioner (<see
        /// cref="IdoublePreconditioner"/>). Structural sibling of <see cref="minres{TOp,TPre}"/>:
        /// same symmetric-Lanczos base and left-Givens (MINRES) reflection, plus a second,
        /// right-Givens (QLP) reflection that regularizes the near-singular tail of the
        /// tridiagonal system. Where plain MINRES can diverge or stall on a singular/rank-deficient
        /// A, this returns the MINIMUM-LENGTH solution of the compatible system, or of the
        /// associated least-squares problem when A x = b is incompatible.
        ///
        /// A MUST be symmetric; a real preconditioner M MUST be SPD (caller precondition, not
        /// verified beyond the NaN-safe breakdown guards). x is a warm-startable initial guess,
        /// overwritten with the solution. tol is the relative-residual tolerance (reference's
        /// RTOL); maxIter bounds the Lanczos step count. tol also sets the min-length
        /// regularization scale: solution growth past ~beta1/(64*tol*‖A‖est) -- contributions from
        /// directions with sigma below ~64*tol*‖A‖est, which can never be certified at tol -- is
        /// truncated toward the minimum-length solution (the reference's MAXXNORM knob, made
        /// problem-relative instead of its absolute 1e7 default).
        ///
        /// Caller provides x and nine scratch vectors (v, r1, r2, r3, w, wl, wl2, xl2, t1; all
        /// length A.Rows) -- see the folder DEVLOG for the buffer-reuse/aliasing plan. Returns a
        /// <see cref="SolveInfo"/>: Converged only when the FRESH residual r = b - A x certifies
        /// the exit, either as a compatible solve (‖r‖ &lt;= 64*tol*‖b‖) or as a least-squares
        /// optimum (‖A·r‖ &lt;= 64*tol*Anorm*‖r‖) -- so an incompatible-system Converged carries a
        /// legitimately large rnorm; MaxIterations when the step budget was exhausted or a claimed
        /// convergence failed both certificates; Breakdown when Acond exceeded its safety bound, a
        /// xnorm-clamp exit failed both certificates, the recurrence went singular, or a non-SPD M
        /// was detected -- see the folder DEVLOG for the full flag-to-status mapping and the
        /// reference's own flag semantics.
        /// </summary>
        public static SolveInfo minresQLP<TOp, TPre>(in TOp A, in TPre M, in doubleN b, ref doubleN x,
                                       ref doubleN v, ref doubleN r1, ref doubleN r2, ref doubleN r3,
                                       ref doubleN w, ref doubleN wl, ref doubleN wl2, ref doubleN xl2,
                                       ref doubleN t1, int maxIter, double tol)
            where TOp : struct, IdoubleLinearOperator
            where TPre : struct, IdoublePreconditioner
        {
            if (A.Rows != A.Cols)
                throw new ArgumentException("minresQLP: A must be square");

            if (b.N != A.Rows) throw new ArgumentException("minresQLP: b.N must equal A.Rows");
            if (x.N != A.Rows) throw new ArgumentException("minresQLP: x.N must equal A.Rows");
            if (v.N != A.Rows) throw new ArgumentException("minresQLP: v.N must equal A.Rows");
            if (r1.N != A.Rows) throw new ArgumentException("minresQLP: r1.N must equal A.Rows");
            if (r2.N != A.Rows) throw new ArgumentException("minresQLP: r2.N must equal A.Rows");
            if (r3.N != A.Rows) throw new ArgumentException("minresQLP: r3.N must equal A.Rows");
            if (w.N != A.Rows) throw new ArgumentException("minresQLP: w.N must equal A.Rows");
            if (wl.N != A.Rows) throw new ArgumentException("minresQLP: wl.N must equal A.Rows");
            if (wl2.N != A.Rows) throw new ArgumentException("minresQLP: wl2.N must equal A.Rows");
            if (xl2.N != A.Rows) throw new ArgumentException("minresQLP: xl2.N must equal A.Rows");
            if (t1.N != A.Rows) throw new ArgumentException("minresQLP: t1.N must equal A.Rows");

            if (maxIter < 1)
                throw new ArgumentException("minresQLP: maxIter must be >= 1");
            if (!M.IsSpd)
                throw new ArgumentException("Krylov.minresQLP: requires an SPD preconditioner (M.IsSpd == false — e.g. ILU0/SPAI/restricted-Schwarz). Use a non-symmetric solver (gmres/biCGStab) for a general preconditioner.");
            if (!M.IsConstant)
                throw new ArgumentException("Krylov.minresQLP: requires a constant (non-flexible) preconditioner (M.IsConstant == false — e.g. an AMG K-cycle). Use the flexible variant (fcg / fgmres).");

            unsafe
            {
                long* ptrs = stackalloc long[11];
                ptrs[0] = (long)v.Data.Ptr;   ptrs[1] = (long)r1.Data.Ptr;  ptrs[2] = (long)r2.Data.Ptr;
                ptrs[3] = (long)r3.Data.Ptr;  ptrs[4] = (long)w.Data.Ptr;   ptrs[5] = (long)wl.Data.Ptr;
                ptrs[6] = (long)wl2.Data.Ptr; ptrs[7] = (long)xl2.Data.Ptr; ptrs[8] = (long)t1.Data.Ptr;
                ptrs[9] = (long)x.Data.Ptr;   ptrs[10] = (long)b.Data.Ptr;
                RequireDistinctBuffers("minresQLP: v/r1/r2/r3/w/wl/wl2/xl2/t1/x/b must be distinct", ptrs, 11);
            }

            double bb = Blas.dot(b, b);
            if (bb == (double)0)
            {
                x.CopyFrom(in b);
                return MakeSolveInfo(IterativeSolveStatus.Converged, 0, (double)0);
            }

            // r2 = r0 = b - A x (warm start: r1 is temp scratch here, overwritten before it is
            // ever read as Lanczos history).
            A.Apply(in x, ref r1);
            r2.CopyFrom(in b);
            r2.addScaledInPlace((double)(-1), r1);

            double beta1;
            if (M.IsIdentity)
            {
                beta1 = math.sqrt(Blas.dot(r2, r2));
            }
            else
            {
                M.Apply(in r2, ref r3);
                double beta1Sq = Blas.dot(r2, r3);
                if (!(beta1Sq > (double)0))
                    return MakeSolveInfo(IterativeSolveStatus.Breakdown, 0, math.sqrt(Blas.dot(r2, r2)));
                beta1 = math.sqrt(beta1Sq);
            }
            if (beta1 == (double)0)
                return MakeSolveInfo(IterativeSolveStatus.Converged, 0, (double)0);

            double eps = Consts.doubleEpsilon;
            double tiny = eps * eps;
            double Acondlim = (double)1e15;
            double TranCond = (double)1e7;
            // Denominator of the per-iteration min-length cap maxxnorm (computed inside the loop
            // from the running Anorm estimate): solution growth beyond
            // beta1/(MaxXNormFactor*tol*Anorm) can never be certified at tolerance tol -- both the
            // relres stop metric and the exit certificates (64*tol slack, mirrored by
            // MaxXNormFactor) go vacuous there -- so it is truncated toward the min-length
            // solution. tol is floored at eps.
            double maxxnormDenom = Consts.doubleMaxXNormFactor * math.max(tol, eps);

            const int flag0 = -2;
            int flag = flag0;
            int QLPiter = 0;
            double beta = (double)0;
            double betan = beta1;
            double tau = (double)0, taul = (double)0;
            double phi = beta1;
            double cs = (double)(-1), sn = (double)0;
            double cr1 = (double)(-1), sr1 = (double)0;
            double cr2 = (double)(-1), sr2 = (double)0;
            double dltan = (double)0, eplnn = (double)0;
            double gama = (double)0, gamal = (double)0, gamal2 = (double)0;
            double eta = (double)0, etal = (double)0, etal2 = (double)0;
            double vepln = (double)0, veplnl = (double)0, veplnl2 = (double)0;
            double ul3 = (double)0, ul2 = (double)0, ul = (double)0, u = (double)0;
            double gmin = (double)0, gminl = (double)0, gminl2 = (double)0;
            double rnorm = beta1;
            double xnorm = (double)0, xl2norm = (double)0, Axnorm = (double)0;
            double Anorm = (double)0, Acond = (double)1;
            double relres = (double)1;
            double gamalQLP = (double)0, veplnQLP = (double)0, gamaQLP = (double)0, ulQLP = (double)0, uQLP = (double)0;

            // 3-term search-direction history and the lagged solution accumulator start at 0.
            w.zeroInPlace(); wl.zeroInPlace(); wl2.zeroInPlace(); xl2.zeroInPlace();

            int iters;
            for (iters = 1; iters <= maxIter; iters++)
            {
                // ---- symmetric Lanczos step ----
                double betal = beta;
                beta = betan;

                if (M.IsIdentity) Blas.scaledCopy(1 / beta, r2, ref v);
                else              Blas.scaledCopy(1 / beta, r3, ref v);

                A.Apply(in v, ref r3);
                if (iters > 1) r3.addScaledInPlace(-(beta / betal), r1);
                double alfa = Blas.dot(r3, v);
                r3.addScaledInPlace(-(alfa / beta), r2);

                { doubleN tmp = r1; r1 = r2; r2 = r3; r3 = tmp; }

                double betanSq;
                if (M.IsIdentity)
                {
                    betanSq = Blas.dot(r2, r2);
                }
                else
                {
                    M.Apply(in r2, ref r3);
                    betanSq = Blas.dot(r2, r3);
                    if (!(betanSq >= (double)0)) { flag = -3; break; }
                }
                betan = math.sqrt(betanSq);

                if (iters == 1 && betan == (double)0)
                {
                    // v is an exact eigenvector of A (Av = alfa v): either r0 has no component in
                    // range(A) (x already optimal, flag 0) or the correction r0/alfa solves exactly
                    // (flag -1).
                    if (alfa == (double)0) flag = 0;
                    else { x.addScaledInPlace(1 / alfa, r1); flag = -1; }
                    break;
                }

                // Column norm of the Lanczos tridiagonal T, feeding the Anorm (~ ‖A‖) estimate. At
                // iters == 2 the sliding window's betal holds beta1 = ‖M-weighted r0‖, which is NOT
                // an entry of T -- substituting beta (= beta_2, T's actual subdiagonal entry) keeps
                // Anorm a ‖T‖ estimate instead of max(‖A‖, ‖r0‖), which otherwise inflates the
                // relres denominator and both exit certificates whenever ‖b‖ > ‖A‖.
                double pnorm = (iters == 2)
                    ? math.sqrt(beta * beta + alfa * alfa + betan * betan)
                    : math.sqrt(betal * betal + alfa * alfa + betan * betan);

                // Min-length cap on the tracked solution(-correction) norm, relative to the
                // problem's own scale beta1/Anorm -- never an absolute constant. pnorm keeps the
                // estimate live at iters == 1, before the first Anorm update below.
                double maxxnorm = beta1 / (maxxnormDenom * math.max(Anorm, pnorm));

                // ---- previous left rotation Q_{k-1} ----
                double dbar = dltan;
                double dlta = cs * dbar + sn * alfa;
                double epln = eplnn;
                double gbar = sn * dbar - cs * alfa;
                eplnn = sn * betan;
                dltan = -cs * betan;
                double dltaQLP = dlta;

                // ---- current left plane rotation Q_k ----
                double gamal3 = gamal2;
                gamal2 = gamal;
                gamal = gama;
                SymGivens(gbar, betan, out cs, out sn, out gama);
                double gamaTmp = gama;
                double taul2 = taul;
                taul = tau;
                tau = cs * phi;
                Axnorm = math.sqrt(Axnorm * Axnorm + tau * tau);
                phi = sn * phi;

                // ---- previous right plane rotation P_{k-2,k} ----
                if (iters > 2)
                {
                    veplnl2 = veplnl;
                    etal2 = etal;
                    etal = eta;
                    double dltaTmp = sr2 * vepln - cr2 * dlta;
                    veplnl = cr2 * vepln + sr2 * dlta;
                    dlta = dltaTmp;
                    eta = sr2 * gama;
                    gama = -cr2 * gama;
                }

                // ---- current right plane rotation P_{k-1,k} ----
                if (iters > 1)
                {
                    SymGivens(gamal, dlta, out cr1, out sr1, out gamal);
                    vepln = sr1 * gama;
                    gama = -cr1 * gama;
                }

                // ---- xnorm update / maxxnorm-and-degeneracy guard ----
                double ul4 = ul3;
                ul3 = ul2;
                if (iters > 2) ul2 = (taul2 - etal2 * ul4 - veplnl2 * ul3) / gamal2;
                if (iters > 1) ul = (taul - etal * ul3 - veplnl * ul2) / gamal;
                double xnormTmp = math.sqrt(xl2norm * xl2norm + ul2 * ul2 + ul * ul);
                if (math.abs(gama) > tiny && xnormTmp < maxxnorm)
                {
                    u = (tau - eta * ul2 - vepln * ul) / gama;
                    if (math.sqrt(xnormTmp * xnormTmp + u * u) > maxxnorm) { u = (double)0; flag = 6; }
                }
                else
                {
                    u = (double)0;
                    flag = 9;
                }
                xl2norm = math.sqrt(xl2norm * xl2norm + ul2 * ul2);
                xnorm = math.sqrt(xl2norm * xl2norm + ul * ul + u * u);

                // ---- update w & x: conventional MINRES step, or the MINRES-QLP right-reflection ----
                if (Acond < TranCond && flag != flag0 && QLPiter == 0)
                {
                    doubleN tmp = wl2; wl2 = wl; wl = w; w = tmp;
                    Blas.combine3(ref w, v, -epln, wl2, -dltaQLP, wl, 1 / gamaTmp);
                    if (xnorm < maxxnorm) x.addScaledInPlace(tau, w);
                    else flag = 6;
                }
                else
                {
                    QLPiter += 1;
                    if (QLPiter == 1)
                    {
                        xl2.CopyFrom(in x);   // seed x0 (warm start); == zeroInPlace for cold x=0. iters>1 reseeds below.
                        if (iters > 1)
                        {
                            if (iters > 3)
                            {
                                Blas.scaledCopy(gamal3, wl2, ref t1);
                                t1.addScaledInPlace(veplnl2, wl);
                                t1.addScaledInPlace(etal, w);
                                { doubleN buf = wl2; wl2 = t1; t1 = buf; }
                            }
                            if (iters > 2)
                            {
                                Blas.scaledCopy(gamalQLP, wl, ref t1);
                                t1.addScaledInPlace(veplnQLP, w);
                                { doubleN buf = wl; wl = t1; t1 = buf; }
                            }
                            w.mulInPlace(gamaQLP);
                            xl2.CopyFrom(in x);
                            xl2.addScaledInPlace(-ulQLP, wl);
                            xl2.addScaledInPlace(-uQLP, w);
                        }
                    }

                    if (iters == 1)
                    {
                        doubleN buf = wl2;
                        wl2 = wl;
                        Blas.scaledCopy(sr1, v, ref buf);
                        wl = buf;
                        Blas.scaledCopy(-cr1, v, ref w);
                    }
                    else if (iters == 2)
                    {
                        doubleN buf = wl2;
                        wl2 = wl;
                        Blas.scaledCopy(cr1, w, ref buf);
                        buf.addScaledInPlace(sr1, v);
                        w.mulInPlace(sr1);
                        w.addScaledInPlace(-cr1, v);
                        wl = buf;
                    }
                    else
                    {
                        doubleN wl2Free = wl2;
                        Blas.scaledCopy(cr2, wl, ref wl2Free);
                        wl2Free.addScaledInPlace(sr2, v);
                        v.mulInPlace(-cr2);
                        v.addScaledInPlace(sr2, wl);
                        Blas.scaledCopy(cr1, w, ref t1);
                        t1.addScaledInPlace(sr1, v);
                        w.mulInPlace(sr1);
                        w.addScaledInPlace(-cr1, v);
                        doubleN wlFree = wl;
                        wl2 = wl2Free;
                        wl = t1;
                        t1 = wlFree;
                    }

                    xl2.addScaledInPlace(ul2, wl2);
                    x.CopyFrom(in xl2);
                    x.addScaledInPlace(ul, wl);
                    x.addScaledInPlace(u, w);
                }

                // ---- next right plane rotation P_{k-1,k+1}; snapshot for the next QLP transition ----
                double gamalTmp2 = gamal;
                SymGivens(gamal, eplnn, out cr2, out sr2, out gamal);
                gamalQLP = gamalTmp2;
                veplnQLP = vepln;
                gamaQLP = gama;
                ulQLP = ul;
                uQLP = u;

                // ---- norm / condition estimates ----
                double absGama = math.abs(gama);
                Anorm = math.max(math.max(Anorm, pnorm), math.max(gamal, absGama));
                if (iters == 1)
                {
                    gmin = gama;
                    gminl = gmin;
                }
                else
                {
                    gminl2 = gminl;
                    gminl = gmin;
                    gmin = math.min(math.min(gminl2, gamal), absGama);
                }
                double Acondl = Acond;
                Acond = Anorm / gmin;
                double rnorml = rnorm;
                double relresl = relres;
                if (flag != 9) rnorm = phi;
                relres = rnorm / (Anorm * xnorm + beta1);
                double rootl = math.sqrt(gbar * gbar + dltan * dltan);
                double relAresl = rootl / Anorm;

                // ---- stopping tests (relative residual, ‖Ar‖, xnorm/Acond safety bounds) ----
                double epsx = Anorm * xnorm * eps;
                if (flag == flag0 || flag == 9)
                {
                    double chk1 = 1 + relres;
                    double chk2 = 1 + relAresl;
                    if (iters >= maxIter) flag = 8;
                    if (Acond >= Acondlim) flag = 7;
                    if (xnorm >= maxxnorm) flag = 6;
                    if (epsx >= beta1) flag = 5;
                    if (chk2 <= 1) flag = 4;
                    if (chk1 <= 1) flag = 3;
                    if (relAresl <= tol) flag = 2;
                    if (relres <= tol) flag = 1;
                }

                // flag in {2,4,6,7}: this step's boundary trip is not yet trustworthy -- report the
                // pre-step diagnostics (x/w/wl/wl2 themselves are NOT rolled back).
                if (flag == 2 || flag == 4 || flag == 6 || flag == 7)
                {
                    iters -= 1;
                    Acond = Acondl;
                    rnorm = rnorml;
                    relres = relresl;
                }

                if (flag != flag0) break;
            }

            if (flag == flag0) { flag = 8; iters = maxIter; }

            // Final true residual (fresh, regardless of exit reason -- r3/r1 are idle by now).
            double finalRnorm = math.sqrt(VerifyTrueResidual(in A, in b, in x, ref r3, ref r1));

            IterativeSolveStatus status;
            if (flag == 8) status = IterativeSolveStatus.MaxIterations;
            else if (flag == 6 || flag == 7 || flag == 9 || flag == -3) status = IterativeSolveStatus.Breakdown;
            else status = IterativeSolveStatus.Converged;

            // Exit certificates against the FRESH residual r = b - A x (left in r1 above), on
            // un-inflated scales -- the QLP stop metric divides by (Anorm*xnorm + beta1), which
            // a near-breakdown's large Anorm*xnorm can deflate below tol while the true residual
            // is large. Converged is only reported when one certificate holds:
            //   1. compatible:    ‖b-Ax‖ <= 64*tol*‖b‖ (no extra cost);
            //   2. least-squares: ‖A(b-Ax)‖ <= 64*tol*Anorm*‖b-Ax‖ (one extra matvec, only when
            //      1 fails; A symmetric, so A·r is the optimality residual Aᵀr of min ‖b-Ax‖).
            // A Converged claim failing both is downgraded to MaxIterations. A flag-6/9 exit
            // (the maxxnorm/u-clamp -- the min-length mechanism on a singular A) is promoted to
            // Converged when a certificate holds, else stays Breakdown; flags 7 (Acond) and -3
            // (non-SPD M) are genuine breakdowns, never promoted.
            if (status == IterativeSolveStatus.Converged ||
                (status == IterativeSolveStatus.Breakdown && (flag == 6 || flag == 9)))
            {
                if (finalRnorm <= (double)64 * tol * beta1)
                {
                    status = IterativeSolveStatus.Converged;
                }
                else
                {
                    A.Apply(in r1, ref r3);
                    double arnorm = math.sqrt(Blas.dot(r3, r3));
                    if (arnorm <= (double)64 * tol * Anorm * finalRnorm)
                        status = IterativeSolveStatus.Converged;
                    else if (status == IterativeSolveStatus.Converged)
                        status = IterativeSolveStatus.MaxIterations;
                }
            }

            return MakeSolveInfo(status, iters, finalRnorm);
        }

        /// <summary>
        /// Stable symmetric Givens rotation (Golub &amp; Van Loan): returns c, s, r such that
        /// [[c, s], [-s, c]] · [a, b]ᵀ = [r, 0]ᵀ, with r = ±‖(a,b)‖ chosen for cancellation safety.
        /// Zero -> +1 sign convention (matches <see cref="Helpers.signOrOne"/>).
        /// </summary>
        static void SymGivens(double a, double b, out double c, out double s, out double r)
        {
            if (b == (double)0)
            {
                c = Helpers.signOrOne(a);
                s = (double)0;
                r = math.abs(a);
            }
            else if (a == (double)0)
            {
                c = (double)0;
                s = Helpers.signOrOne(b);
                r = math.abs(b);
            }
            else if (math.abs(b) > math.abs(a))
            {
                double t = a / b;
                s = Helpers.signOrOne(b) / math.sqrt((double)1 + t * t);
                c = s * t;
                r = b / s;
            }
            else
            {
                double t = b / a;
                c = Helpers.signOrOne(a) / math.sqrt((double)1 + t * t);
                s = c * t;
                r = a / c;
            }
        }

        /// <summary>
        /// Unpreconditioned MINRES-QLP -- forwards into the merged
        /// <see cref="minresQLP{TOp, TPre}(in TOp, in TPre, in doubleN, ref doubleN, ref doubleN, ref doubleN, ref doubleN, ref doubleN, ref doubleN, ref doubleN, ref doubleN, ref doubleN, ref doubleN, int, double)"/>
        /// with the identity preconditioner.
        /// </summary>
        public static SolveInfo minresQLP<TOp>(in TOp A, in doubleN b, ref doubleN x,
                                       ref doubleN v, ref doubleN r1, ref doubleN r2, ref doubleN r3,
                                       ref doubleN w, ref doubleN wl, ref doubleN wl2, ref doubleN xl2,
                                       ref doubleN t1, int maxIter, double tol)
            where TOp : struct, IdoubleLinearOperator
        {
            return minresQLP(in A, default(doubleIdentityPreconditioner), in b, ref x, ref v, ref r1, ref r2, ref r3, ref w, ref wl, ref wl2, ref xl2, ref t1, maxIter, tol);
        }

        /// <summary>
        /// MINRES-QLP over a dense <see cref="doubleMxN"/> -- zero-alloc primitive. Forwards into
        /// <see cref="minresQLP{TOp}"/> via <see cref="doubleDenseOperator"/>.
        /// </summary>
        public static SolveInfo minresQLP(in doubleMxN A, in doubleN b, ref doubleN x,
                                  ref doubleN v, ref doubleN r1, ref doubleN r2, ref doubleN r3,
                                  ref doubleN w, ref doubleN wl, ref doubleN wl2, ref doubleN xl2,
                                  ref doubleN t1, int maxIter, double tol)
        {
            return minresQLP(new doubleDenseOperator(in A), in b, ref x, ref v, ref r1, ref r2, ref r3, ref w, ref wl, ref wl2, ref xl2, ref t1, maxIter, tol);
        }

        /// <summary>MINRES-QLP over a dense matrix -- allocates nine scratch vectors from the arena.</summary>
        public static SolveInfo minresQLP(in doubleMxN A, in doubleN b, ref doubleN x, int maxIter, double tol)
        {
            doubleN v   = b.doubleTempVec(A.M_Rows);
            doubleN r1  = b.doubleTempVec(A.M_Rows);
            doubleN r2  = b.doubleTempVec(A.M_Rows);
            doubleN r3  = b.doubleTempVec(A.M_Rows);
            doubleN w   = b.doubleTempVec(A.M_Rows);
            doubleN wl  = b.doubleTempVec(A.M_Rows);
            doubleN wl2 = b.doubleTempVec(A.M_Rows);
            doubleN xl2 = b.doubleTempVec(A.M_Rows);
            doubleN t1  = b.doubleTempVec(A.M_Rows);
            return minresQLP(in A, in b, ref x, ref v, ref r1, ref r2, ref r3, ref w, ref wl, ref wl2, ref xl2, ref t1, maxIter, tol);
        }

        /// <summary>MINRES-QLP over a dense matrix with default maxIter (A.M_Rows) and tol (Consts.doubleSqrtEps).</summary>
        public static SolveInfo minresQLP(in doubleMxN A, in doubleN b, ref doubleN x)
        {
            return minresQLP(in A, in b, ref x, A.M_Rows, Consts.doubleSqrtEps);
        }

        /// <summary>
        /// MINRES-QLP over a symmetric block-sparse (BSR) matrix -- zero-alloc primitive. Forwards
        /// into <see cref="minresQLP{TOp}"/> via <c>doubleBSROperator</c>.
        /// </summary>
        public static SolveInfo minresQLP(in doubleBSR A, in doubleN b, ref doubleN x,
                                  ref doubleN v, ref doubleN r1, ref doubleN r2, ref doubleN r3,
                                  ref doubleN w, ref doubleN wl, ref doubleN wl2, ref doubleN xl2,
                                  ref doubleN t1, int maxIter, double tol)
        {
            return minresQLP(new doubleBSROperator(in A), in b, ref x, ref v, ref r1, ref r2, ref r3, ref w, ref wl, ref wl2, ref xl2, ref t1, maxIter, tol);
        }

        /// <summary>MINRES-QLP over a BSR matrix -- allocates nine scratch vectors from the arena.</summary>
        public static SolveInfo minresQLP(in doubleBSR A, in doubleN b, ref doubleN x, int maxIter, double tol)
        {
            doubleN v   = b.doubleTempVec(A.M_Rows);
            doubleN r1  = b.doubleTempVec(A.M_Rows);
            doubleN r2  = b.doubleTempVec(A.M_Rows);
            doubleN r3  = b.doubleTempVec(A.M_Rows);
            doubleN w   = b.doubleTempVec(A.M_Rows);
            doubleN wl  = b.doubleTempVec(A.M_Rows);
            doubleN wl2 = b.doubleTempVec(A.M_Rows);
            doubleN xl2 = b.doubleTempVec(A.M_Rows);
            doubleN t1  = b.doubleTempVec(A.M_Rows);
            return minresQLP(in A, in b, ref x, ref v, ref r1, ref r2, ref r3, ref w, ref wl, ref wl2, ref xl2, ref t1, maxIter, tol);
        }

        /// <summary>MINRES-QLP over a BSR matrix with default maxIter (A.M_Rows) and tol (Consts.doubleSqrtEps).</summary>
        public static SolveInfo minresQLP(in doubleBSR A, in doubleN b, ref doubleN x)
        {
            return minresQLP(in A, in b, ref x, A.M_Rows, Consts.doubleSqrtEps);
        }

        /// <summary>
        /// Preconditioned MINRES-QLP solver -- allocates nine scratch vectors from the arena and
        /// calls the zero-alloc primitive.
        /// </summary>
        public static SolveInfo minresQLP<TOp, TPre>(in TOp A, in TPre M, in doubleN b, ref doubleN x,
                                          int maxIter, double tol)
            where TOp : struct, IdoubleLinearOperator
            where TPre : struct, IdoublePreconditioner
        {
            doubleN v   = b.doubleTempVec(A.Rows);
            doubleN r1  = b.doubleTempVec(A.Rows);
            doubleN r2  = b.doubleTempVec(A.Rows);
            doubleN r3  = b.doubleTempVec(A.Rows);
            doubleN w   = b.doubleTempVec(A.Rows);
            doubleN wl  = b.doubleTempVec(A.Rows);
            doubleN wl2 = b.doubleTempVec(A.Rows);
            doubleN xl2 = b.doubleTempVec(A.Rows);
            doubleN t1  = b.doubleTempVec(A.Rows);
            return minresQLP(in A, in M, in b, ref x, ref v, ref r1, ref r2, ref r3, ref w, ref wl, ref wl2, ref xl2, ref t1, maxIter, tol);
        }

        /// <summary>
        /// Preconditioned MINRES-QLP solver with default maxIter (A.Rows) and tol
        /// (Consts.doubleSqrtEps).
        /// </summary>
        public static SolveInfo minresQLP<TOp, TPre>(in TOp A, in TPre M, in doubleN b, ref doubleN x)
            where TOp : struct, IdoubleLinearOperator
            where TPre : struct, IdoublePreconditioner
        {
            return minresQLP(in A, in M, in b, ref x, A.Rows, Consts.doubleSqrtEps);
        }

        /// <summary>
        /// Preconditioned MINRES-QLP over a block-sparse (BSR) matrix with ANY
        /// <see cref="IdoublePreconditioner"/> (block-Jacobi). Forwards into
        /// <see cref="minresQLP{TOp,TPre}"/> via <c>doubleBSROperator</c>.
        /// </summary>
        public static SolveInfo minresQLP<TPre>(in doubleBSR A, in TPre M, in doubleN b, ref doubleN x,
                               ref doubleN v, ref doubleN r1, ref doubleN r2, ref doubleN r3,
                               ref doubleN w, ref doubleN wl, ref doubleN wl2, ref doubleN xl2,
                               ref doubleN t1, int maxIter, double tol)
            where TPre : struct, IdoublePreconditioner
        {
            return minresQLP(new doubleBSROperator(in A), in M, in b, ref x, ref v, ref r1, ref r2, ref r3, ref w, ref wl, ref wl2, ref xl2, ref t1, maxIter, tol);
        }

        /// <summary>
        /// Preconditioned MINRES-QLP over a BSR matrix with ANY <see cref="IdoublePreconditioner"/>
        /// (block-Jacobi) -- allocates nine scratch vectors from the arena and calls the zero-alloc
        /// primitive.
        /// </summary>
        public static SolveInfo minresQLP<TPre>(in doubleBSR A, in TPre M, in doubleN b, ref doubleN x,
                               int maxIter, double tol)
            where TPre : struct, IdoublePreconditioner
        {
            doubleN v   = b.doubleTempVec(A.M_Rows);
            doubleN r1  = b.doubleTempVec(A.M_Rows);
            doubleN r2  = b.doubleTempVec(A.M_Rows);
            doubleN r3  = b.doubleTempVec(A.M_Rows);
            doubleN w   = b.doubleTempVec(A.M_Rows);
            doubleN wl  = b.doubleTempVec(A.M_Rows);
            doubleN wl2 = b.doubleTempVec(A.M_Rows);
            doubleN xl2 = b.doubleTempVec(A.M_Rows);
            doubleN t1  = b.doubleTempVec(A.M_Rows);
            return minresQLP(in A, in M, in b, ref x, ref v, ref r1, ref r2, ref r3, ref w, ref wl, ref wl2, ref xl2, ref t1, maxIter, tol);
        }

        /// <summary>
        /// Preconditioned MINRES-QLP over a BSR matrix with ANY <see cref="IdoublePreconditioner"/>
        /// (block-Jacobi), with default maxIter (A.M_Rows) and tol (Consts.doubleSqrtEps).
        /// </summary>
        public static SolveInfo minresQLP<TPre>(in doubleBSR A, in TPre M, in doubleN b, ref doubleN x)
            where TPre : struct, IdoublePreconditioner
        {
            return minresQLP(in A, in M, in b, ref x, A.M_Rows, Consts.doubleSqrtEps);
        }
    }
}
