// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/Krylov.GCRODR.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Mathematics;
using BULA.Sparse;

namespace BULA
{
    public static partial class Krylov
    {
        /// <summary>
        /// GCRO-DR (Morgan 2002 / Parks-de Sturler-Mackey-Johnson-Maiti 2006): restarted GMRES(m)
        /// that RECYCLES a k-dimensional approximate invariant subspace (harmonic Ritz vectors)
        /// across restart cycles, for a general (nonsymmetric) square A x = b. Generic over both the
        /// operator (<see cref="IdoubleLinearOperator"/>) and the preconditioner
        /// (<see cref="IdoublePreconditioner"/>) -- the SINGLE body behind the plain and the
        /// right-preconditioned entry points.
        ///
        /// With <see cref="doubleIdentityPreconditioner"/> the IsIdentity fold matches
        /// <see cref="gmres{TOp,TPre}"/>'s: no M⁻¹ apply, no separate preconditioned-basis storage.
        /// recycle = 0 disables recycling entirely and is bit-identical to <see cref="gmres{TOp,TPre}"/>.
        ///
        /// x is a warm-startable initial guess, overwritten with the solution; tol is relative
        /// (‖b − Ax‖ ≤ tol·‖b‖); maxIter counts TOTAL inner Arnoldi iterations across restarts (the
        /// per-cycle residual/recycle-projection matvecs are not counted, matching gmres's convention).
        /// recycle must be in [0, restart). Allocates its workspace (Arnoldi + recycle + small dense
        /// deflation buffers) from the Temp allocator. Returns the shared <see cref="SolveInfo"/>;
        /// rnorm on a Converged exit is a freshly recomputed ‖b−Ax‖, not the raw Arnoldi/Givens
        /// estimate (which only measures the C-orthogonal, recycle-projected residual) -- a failed
        /// verify falls through to another cycle instead of a false Converged. Status: Converged /
        /// MaxIterations / Breakdown (a collapsed Hessenberg pivot in the least-squares
        /// back-substitution) -- never NaN, never a false Converged. A failed or ill-conditioned
        /// per-cycle deflation update degrades gracefully (keeps the previous cycle's recycled
        /// subspace) rather than aborting the solve.
        /// </summary>
        public static SolveInfo gcrodr<TOp, TPre>(in TOp A, in TPre M, in doubleN b, ref doubleN x,
                                     int restart, int recycle, int maxIter, double tol)
            where TOp : struct, IdoubleLinearOperator
            where TPre : struct, IdoublePreconditioner
        {
            if (A.Rows != A.Cols) throw new ArgumentException("gcrodr: A must be square");
            if (b.N != A.Rows) throw new ArgumentException("gcrodr: b.N must equal A.Rows");
            if (x.N != A.Rows) throw new ArgumentException("gcrodr: x.N must equal A.Rows");
            if (restart < 1) throw new ArgumentException("gcrodr: restart must be >= 1");
            if (recycle < 0) throw new ArgumentException("gcrodr: recycle must be >= 0");
            if (recycle >= restart) throw new ArgumentException("gcrodr: recycle must be < restart");
            if (maxIter < 1) throw new ArgumentException("gcrodr: maxIter must be >= 1");
            if (!M.IsConstant)
                throw new ArgumentException("Krylov.gcrodr: requires a constant (non-flexible) preconditioner (M.IsConstant == false — e.g. an AMG K-cycle). Use the flexible variant (fcg / fgmres).");

            int n = A.Rows;
            int m = restart;
            bool flexible = !M.IsIdentity;
            bool recycling = recycle > 0;

            double bb = Blas.dot(b, b);
            if (bb == (double)0)
            {
                x.CopyFrom(in b);
                return MakeSolveInfo(IterativeSolveStatus.Converged, 0, (double)0);
            }
            double bnorm = math.sqrt(bb);
            double thresh = tol * bnorm;
            // hMaxAbs tracks the running max |H| entry (raw Arnoldi, pre-Givens) seen so far in this
            // solve -- an ||A||-scaled reference for the Arnoldi/back-substitution pivot guards below,
            // instead of the ||b||-scaled bnorm (which under- or over-guards whenever ||A|| and ||b||
            // differ in magnitude). The Ru guard is scaled separately, per use, by max |Ru[i,i]|.
            double hMaxAbs = (double)0;
            double hPivotGuard = (double)0;

            // ---- Arnoldi workspace (Temp), fixed max size, mirrors gmres/fgmres ----
            var V = new UnsafeList<doubleN>(m + 1, Allocator.Temp);
            for (int i = 0; i <= m; i++) V.Add(new doubleN(n));
            UnsafeList<doubleN> Zv = default;
            if (flexible)
            {
                Zv = new UnsafeList<doubleN>(m, Allocator.Temp);
                for (int i = 0; i < m; i++) Zv.Add(new doubleN(n));
            }
            UnsafeList<doubleN> AV = default;
            if (recycling)
            {
                AV = new UnsafeList<doubleN>(m, Allocator.Temp);
                for (int i = 0; i < m; i++) AV.Add(new doubleN(n));
            }
            var H = new doubleMxN(m + 1, m, Allocator.Temp, false);
            var cs = new doubleN(m);
            var sn = new doubleN(m);
            var g = new doubleN(m + 1);
            var y = new doubleN(m);
            var w = new doubleN(n);

            // ---- recycled-subspace state (Temp), fixed max size `recycle`, active prefix `kcur` ----
            UnsafeList<doubleN> U = default, C = default;
            doubleMxN Ru = default;   // recycle x recycle, active top-left kcur x kcur upper-triangular
            doubleMxN Bmat = default; // recycle x m, active kcur x p projection coefficients
            doubleN ctr = default;
            doubleN zproj = default;
            int kcur = 0;
            if (recycling)
            {
                U = new UnsafeList<doubleN>(recycle, Allocator.Temp);
                C = new UnsafeList<doubleN>(recycle, Allocator.Temp);
                for (int i = 0; i < recycle; i++) { U.Add(new doubleN(n)); C.Add(new doubleN(n)); }
                Ru = new doubleMxN(recycle, recycle, Allocator.Temp, false);
                Bmat = new doubleMxN(recycle, m, Allocator.Temp, false);
                ctr = new doubleN(recycle);
                zproj = new doubleN(recycle);
            }

            int total = 0;
            double resnorm = bnorm;
            bool converged = false;
            bool breakdown = false;

            while (total < maxIter && !converged && !breakdown)
            {
                // ---- residual, then recycled-subspace projection (fresh matvec both times: never
                // trust an incremental residual update through a possibly near-singular Ru solve) ----
                doubleN v0 = V[0];
                A.Apply(in x, ref w);
                v0.CopyFrom(in b);
                v0.addScaledInPlace((double)(-1), w);

                if (kcur > 0)
                {
                    for (int i = 0; i < kcur; i++) ctr[i] = Blas.dot(C[i], v0);

                    double ruMaxAbs = (double)0;
                    for (int i = 0; i < kcur; i++) ruMaxAbs = math.max(ruMaxAbs, math.abs(Ru[i, i]));
                    double ruPivotGuard = Consts.doubleEpsilon * (double)100 * ruMaxAbs;
                    for (int i = kcur - 1; i >= 0; i--)
                    {
                        double s = ctr[i];
                        for (int l = i + 1; l < kcur; l++) s -= Ru[i, l] * zproj[l];
                        double diag = Ru[i, i];
                        zproj[i] = math.abs(diag) > ruPivotGuard ? s / diag : (double)0;
                    }
                    for (int i = 0; i < kcur; i++) x.addScaledInPlace(zproj[i], U[i]);

                    A.Apply(in x, ref w);
                    v0.CopyFrom(in b);
                    v0.addScaledInPlace((double)(-1), w);
                }

                double beta = math.sqrt(Blas.dot(v0, v0));
                resnorm = beta;
                if (beta <= thresh) { converged = true; break; }

                double invBeta = (double)1 / beta;
                for (int i = 0; i < n; i++) v0[i] *= invBeta;
                for (int i = 0; i <= m; i++) g[i] = (double)0;
                g[0] = beta;

                int p = 0;
                for (int j = 0; j < m && total < maxIter; j++)
                {
                    doubleN vj = V[j];
                    if (flexible)
                    {
                        doubleN zj = Zv[j];
                        M.Apply(in vj, ref zj);
                        A.Apply(in zj, ref w);
                    }
                    else
                    {
                        A.Apply(in vj, ref w);
                    }

                    if (recycling) AV[j].CopyFrom(in w);   // raw A*(this-cycle basis vector), pre-projection

                    if (kcur > 0)
                    {
                        for (int i = 0; i < kcur; i++)
                        {
                            double bij = Blas.dot(C[i], w);
                            Bmat[i, j] = bij;
                            w.addScaledInPlace(-bij, C[i]);
                        }
                    }

                    // Modified Gram-Schmidt against v_0..v_j.
                    for (int i = 0; i <= j; i++)
                    {
                        doubleN vi = V[i];
                        double hij = Blas.dot(w, vi);
                        H[i, j] = hij;
                        hMaxAbs = math.max(hMaxAbs, math.abs(hij));
                        w.addScaledInPlace(-hij, vi);
                    }
                    double hj1 = math.sqrt(Blas.dot(w, w));
                    H[j + 1, j] = hj1;
                    hPivotGuard = Consts.doubleEpsilon * (double)100 * hMaxAbs;
                    bool arnoldiDone = hj1 <= hPivotGuard;
                    hMaxAbs = math.max(hMaxAbs, hj1);
                    if (!arnoldiDone)
                    {
                        doubleN vj1 = V[j + 1];
                        double invh = (double)1 / hj1;
                        vj1.CopyFrom(in w);
                        for (int i = 0; i < n; i++) vj1[i] *= invh;
                    }

                    // Apply previous Givens rotations to column j of H.
                    for (int i = 0; i < j; i++)
                    {
                        double t0 = cs[i] * H[i, j] + sn[i] * H[i + 1, j];
                        H[i + 1, j] = -sn[i] * H[i, j] + cs[i] * H[i + 1, j];
                        H[i, j] = t0;
                    }

                    // New Givens rotation zeroing H[j+1,j].
                    double a0 = H[j, j], b0 = H[j + 1, j];
                    double rr = math.sqrt(a0 * a0 + b0 * b0);
                    double c, s;
                    if (rr > (double)0) { c = a0 / rr; s = b0 / rr; }
                    else { c = (double)1; s = (double)0; }
                    cs[j] = c; sn[j] = s;
                    H[j, j] = rr;
                    H[j + 1, j] = (double)0;

                    double gj = g[j];
                    g[j] = c * gj;
                    g[j + 1] = -s * gj;

                    resnorm = math.abs(g[j + 1]);
                    total++;
                    p = j + 1;

                    if (resnorm <= thresh) { converged = true; break; }
                    if (arnoldiDone) break;
                }

                // Back-substitute H[0..p-1,0..p-1] y = g[0..p-1]; a collapsed pivot is an honest
                // Breakdown (never divide by a near-zero H[i,i]). hPivotGuard uses the full running
                // hMaxAbs (including the last column's subdiagonal), the freshest ||A||-scale estimate.
                hPivotGuard = Consts.doubleEpsilon * (double)100 * hMaxAbs;
                for (int i = p - 1; i >= 0; i--)
                {
                    double sum = g[i];
                    for (int l = i + 1; l < p; l++) sum -= H[i, l] * y[l];
                    double diag = H[i, i];
                    if (math.abs(diag) <= hPivotGuard) { breakdown = true; break; }
                    y[i] = sum / diag;
                }
                if (breakdown)
                {
                    // x was never updated this cycle -- report the TRUE fresh residual at the
                    // returned x, not the stale (and here misleadingly small) Arnoldi/Givens estimate.
                    A.Apply(in x, ref w);
                    double rr2 = (double)0;
                    for (int i = 0; i < n; i++) { double d = b[i] - w[i]; rr2 += d * d; }
                    resnorm = math.sqrt(rr2);
                    break;
                }

                // x += (this-cycle basis)·y  [identity: V itself; flexible: the stored M⁻¹-applied Zv]
                // then the recycle correction x -= U·(Ru⁻¹ (B[:,:p]·y)) that keeps the C-component of
                // the new residual exactly zero (see the folder DEVLOG for the derivation).
                for (int i = 0; i < p; i++)
                {
                    doubleN bi = flexible ? Zv[i] : V[i];
                    x.addScaledInPlace(y[i], bi);
                }

                if (kcur > 0 && p > 0)
                {
                    for (int i = 0; i < kcur; i++)
                    {
                        double s = (double)0;
                        for (int j = 0; j < p; j++) s += Bmat[i, j] * y[j];
                        ctr[i] = s;
                    }
                    double ruMaxAbs = (double)0;
                    for (int i = 0; i < kcur; i++) ruMaxAbs = math.max(ruMaxAbs, math.abs(Ru[i, i]));
                    double ruPivotGuard = Consts.doubleEpsilon * (double)100 * ruMaxAbs;
                    for (int i = kcur - 1; i >= 0; i--)
                    {
                        double s = ctr[i];
                        for (int l = i + 1; l < kcur; l++) s -= Ru[i, l] * zproj[l];
                        double diag = Ru[i, i];
                        zproj[i] = math.abs(diag) > ruPivotGuard ? s / diag : (double)0;
                    }
                    for (int i = 0; i < kcur; i++) x.addScaledInPlace(-zproj[i], U[i]);
                }

                if (converged)
                {
                    // Verify-at-exit: |g[j+1]| only measures the C-orthogonal (recycle-projected)
                    // residual, and a clamped Ru back-solve above can leave the C-component
                    // un-cancelled -- recompute the TRUE residual at the just-updated x. V[0] and w
                    // are both about to be fully overwritten at the top of the next cycle regardless,
                    // so they're free scratch here; a failed verify falls through to the normal
                    // not-converged path below (including the deflation update).
                    doubleN v0v = V[0];
                    double trueRR = VerifyTrueResidual(in A, in b, in x, ref w, ref v0v);
                    resnorm = math.sqrt(trueRR);
                    converged = resnorm <= thresh;
                }

                // ---- deflation update: rebuild the recycled subspace from the combined
                // (old-recycle + this-cycle Krylov) space via a small dense harmonic-Ritz eigenproblem.
                // Skipped (old U/C/Ru kept as-is) on convergence, on a degenerate zero-step cycle, or
                // whenever a numerical guard below trips -- recycling is an accelerator, not a
                // correctness requirement, so any failure here degrades gracefully.
                if (recycling && !converged && p > 0)
                {
                    int d = kcur + p;
                    int kcurAtEntry = kcur;
                    bool hadOldU = kcurAtEntry > 0;

                    UnsafeList<doubleN> AU = default;
                    if (hadOldU)
                    {
                        AU = new UnsafeList<doubleN>(kcurAtEntry, Allocator.Temp);
                        for (int i = 0; i < kcurAtEntry; i++)
                        {
                            var col = new doubleN(n);
                            for (int l = 0; l < kcurAtEntry; l++) col.addScaledInPlace(Ru[l, i], C[l]);
                            AU.Add(col);
                        }
                    }

                    var Fmat = new doubleMxN(d, d, Allocator.Temp, false);
                    var Gmat = new doubleMxN(d, d, Allocator.Temp, false);
                    var Pgram = new doubleMxN(d, d, Allocator.Temp, false);

                    for (int ai = 0; ai < d; ai++)
                    {
                        doubleN APa = ai < kcurAtEntry ? AU[ai] : AV[ai - kcurAtEntry];
                        doubleN Pa = ai < kcurAtEntry ? U[ai] : (flexible ? Zv[ai - kcurAtEntry] : V[ai - kcurAtEntry]);

                        for (int bi = ai; bi < d; bi++)
                        {
                            doubleN APbv = bi < kcurAtEntry ? AU[bi] : AV[bi - kcurAtEntry];
                            doubleN Pbv = bi < kcurAtEntry ? U[bi] : (flexible ? Zv[bi - kcurAtEntry] : V[bi - kcurAtEntry]);

                            double fval = Blas.dot(APa, APbv);
                            Fmat[ai, bi] = fval; Fmat[bi, ai] = fval;

                            double pval = Blas.dot(Pa, Pbv);
                            Pgram[ai, bi] = pval; Pgram[bi, ai] = pval;
                        }

                        for (int bi = 0; bi < d; bi++)
                        {
                            doubleN Pbv = bi < kcurAtEntry ? U[bi] : (flexible ? Zv[bi - kcurAtEntry] : V[bi - kcurAtEntry]);
                            Gmat[ai, bi] = Blas.dot(APa, Pbv);
                        }
                    }

                    var GmatLU = new doubleMxN(Gmat, Allocator.Temp);
                    var Xsol = new doubleMxN(Fmat, Allocator.Temp);
                    var piv = new Pivot(d, Allocator.Temp);
                    var luInfo = LU.solveInPlace(ref GmatLU, ref piv, ref Xsol);
                    piv.Dispose();
                    GmatLU.Dispose();

                    var evReal = new doubleN(d);
                    var evImag = new doubleN(d);
                    bool haveEig = false;
                    if (luInfo.Solved)
                    {
                        var eiInfo = Eigen.valuesQRInPlace(ref Xsol, ref evReal, ref evImag);
                        haveEig = eiInfo.status == IterativeSolveStatus.Converged;
                    }

                    double huge = (double)1e30;
                    var keys = new doubleN(d);
                    for (int i = 0; i < d; i++)
                    {
                        if (!haveEig) { keys[i] = huge; continue; }
                        double re = evReal[i], im = evImag[i];
                        double imagTol = Consts.doubleZeroThreshold * (math.abs(re) + (double)1);
                        keys[i] = math.abs(im) <= imagTol ? math.abs(re) : huge;
                    }

                    int target = math.min(recycle, d);
                    var selIdx = new UnsafeList<int>(math.max(target, 1), Allocator.Temp);
                    for (int sIt = 0; sIt < target; sIt++)
                    {
                        int best = -1;
                        double bestKey = huge;
                        for (int i = 0; i < d; i++)
                            if (keys[i] < bestKey) { bestKey = keys[i]; best = i; }
                        if (best < 0 || bestKey >= huge) break;
                        selIdx.Add(best);
                        keys[best] = huge;
                    }
                    int kNew = selIdx.Length;

                    int allocK = math.max(kNew, 1);
                    var Zsel = new doubleMxN(d, allocK, Allocator.Temp, false);
                    var Ntheta = new doubleMxN(d, d, Allocator.Temp, false);
                    var evTmp = new doubleN(d);
                    var Vtmp = new doubleMxN(d, d, Allocator.Temp, false);

                    bool eigOk = kNew > 0;
                    for (int sIt = 0; sIt < kNew && eigOk; sIt++)
                    {
                        int idx = selIdx[sIt];
                        double th = evReal[idx];
                        for (int ai = 0; ai < d; ai++)
                            for (int bi = 0; bi < d; bi++)
                                Ntheta[ai, bi] = Fmat[ai, bi] - th * (Gmat[ai, bi] + Gmat[bi, ai]) + th * th * Pgram[ai, bi];

                        var symInfo = Eigen.symmetricInPlace(ref Ntheta, ref evTmp, ref Vtmp);
                        if (symInfo.status != IterativeSolveStatus.Converged) { eigOk = false; break; }
                        for (int r = 0; r < d; r++) Zsel[r, sIt] = Vtmp[r, d - 1];
                    }

                    if (eigOk && kNew > 0)
                    {
                        var Unew = new UnsafeList<doubleN>(kNew, Allocator.Temp);
                        var AUraw = new doubleMxN(n, kNew, Allocator.Temp, false);

                        for (int sIt = 0; sIt < kNew; sIt++)
                        {
                            var ucol = new doubleN(n);
                            var aucol = new doubleN(n);
                            for (int l = 0; l < d; l++)
                            {
                                double zl = Zsel[l, sIt];
                                doubleN Pl = l < kcurAtEntry ? U[l] : (flexible ? Zv[l - kcurAtEntry] : V[l - kcurAtEntry]);
                                doubleN APl = l < kcurAtEntry ? AU[l] : AV[l - kcurAtEntry];
                                ucol.addScaledInPlace(zl, Pl);
                                aucol.addScaledInPlace(zl, APl);
                            }
                            Unew.Add(ucol);
                            for (int r = 0; r < n; r++) AUraw[r, sIt] = aucol[r];
                            aucol.Dispose();
                        }

                        var Rnew = new doubleMxN(kNew, kNew, Allocator.Temp, false);
                        QR.decompInPlace(ref AUraw, ref Rnew);

                        double rGuard = Consts.doubleEpsilon * (double)100 * (math.abs(Rnew[0, 0]) + (double)1);
                        int kSafe = 0;
                        while (kSafe < kNew && math.abs(Rnew[kSafe, kSafe]) > rGuard) kSafe++;

                        if (kSafe > 0)
                        {
                            for (int i = 0; i < kSafe; i++)
                            {
                                U[i].CopyFrom(Unew[i]);
                                for (int r = 0; r < n; r++) C[i][r] = AUraw[r, i];
                                for (int l = 0; l < kSafe; l++) Ru[i, l] = i <= l ? Rnew[i, l] : (double)0;
                            }
                            kcur = kSafe;
                        }

                        Rnew.Dispose();
                        AUraw.Dispose();
                        for (int sIt = 0; sIt < kNew; sIt++) Unew[sIt].Dispose();
                        Unew.Dispose();
                    }

                    Vtmp.Dispose(); evTmp.Dispose(); Ntheta.Dispose(); Zsel.Dispose();
                    selIdx.Dispose(); keys.Dispose();
                    evImag.Dispose(); evReal.Dispose();
                    Xsol.Dispose(); Pgram.Dispose(); Gmat.Dispose(); Fmat.Dispose();
                    if (hadOldU)
                    {
                        for (int i = 0; i < kcurAtEntry; i++) AU[i].Dispose();
                        AU.Dispose();
                    }
                }
            }

            for (int i = 0; i <= m; i++) V[i].Dispose();
            V.Dispose();
            if (flexible) { for (int i = 0; i < m; i++) Zv[i].Dispose(); Zv.Dispose(); }
            if (recycling)
            {
                for (int i = 0; i < m; i++) AV[i].Dispose();
                AV.Dispose();
                for (int i = 0; i < recycle; i++) { U[i].Dispose(); C[i].Dispose(); }
                U.Dispose(); C.Dispose();
                Ru.Dispose(); Bmat.Dispose(); ctr.Dispose(); zproj.Dispose();
            }
            H.Dispose(); cs.Dispose(); sn.Dispose(); g.Dispose(); y.Dispose(); w.Dispose();

            var status = breakdown ? IterativeSolveStatus.Breakdown
                       : converged ? IterativeSolveStatus.Converged
                       : IterativeSolveStatus.MaxIterations;
            return MakeSolveInfo(status, total, resnorm);
        }

        /// <summary>
        /// Unpreconditioned GCRO-DR -- forwards into the merged
        /// <see cref="gcrodr{TOp, TPre}(in TOp, in TPre, in doubleN, ref doubleN, int, int, int, double)"/>
        /// with the identity preconditioner.
        /// </summary>
        public static SolveInfo gcrodr<TOp>(in TOp A, in doubleN b, ref doubleN x, int restart, int recycle, int maxIter, double tol)
            where TOp : struct, IdoubleLinearOperator
        {
            return gcrodr(in A, default(doubleIdentityPreconditioner), in b, ref x, restart, recycle, maxIter, tol);
        }

        static int doubleGcrodrDefaultRecycle(int restart) => math.min(10, math.max(0, restart - 1));

        /// <summary>GCRO-DR over a dense <see cref="doubleMxN"/>. Forwards via doubleDenseOperator.</summary>
        public static SolveInfo gcrodr(in doubleMxN A, in doubleN b, ref doubleN x, int restart, int recycle, int maxIter, double tol)
            => gcrodr(new doubleDenseOperator(in A), in b, ref x, restart, recycle, maxIter, tol);

        /// <summary>GCRO-DR over a dense matrix with defaults (restart = min(30, N), recycle = min(10, restart-1), maxIter = N, tol = sqrtEps).</summary>
        public static SolveInfo gcrodr(in doubleMxN A, in doubleN b, ref doubleN x)
        {
            int r = math.min(30, A.M_Rows);
            return gcrodr(new doubleDenseOperator(in A), in b, ref x, r, doubleGcrodrDefaultRecycle(r), A.M_Rows, Consts.doubleSqrtEps);
        }

        /// <summary>GCRO-DR over a block-sparse (BSR) matrix. Forwards via doubleBSROperator.</summary>
        public static SolveInfo gcrodr(in doubleBSR A, in doubleN b, ref doubleN x, int restart, int recycle, int maxIter, double tol)
            => gcrodr(new doubleBSROperator(in A), in b, ref x, restart, recycle, maxIter, tol);

        /// <summary>GCRO-DR over a BSR matrix with defaults (restart = min(30, N), recycle = min(10, restart-1), maxIter = N, tol = sqrtEps).</summary>
        public static SolveInfo gcrodr(in doubleBSR A, in doubleN b, ref doubleN x)
        {
            int r = math.min(30, A.M_Rows);
            return gcrodr(new doubleBSROperator(in A), in b, ref x, r, doubleGcrodrDefaultRecycle(r), A.M_Rows, Consts.doubleSqrtEps);
        }

        /// <summary>Right-preconditioned GCRO-DR over a BSR matrix with ANY <see cref="IdoublePreconditioner"/> (ILU0).</summary>
        public static SolveInfo gcrodr<TPre>(in doubleBSR A, in TPre M, in doubleN b, ref doubleN x, int restart, int recycle, int maxIter, double tol)
            where TPre : struct, IdoublePreconditioner
            => gcrodr(new doubleBSROperator(in A), in M, in b, ref x, restart, recycle, maxIter, tol);

        /// <summary>Right-preconditioned GCRO-DR over a BSR matrix with ANY <see cref="IdoublePreconditioner"/> (ILU0), with defaults (restart = min(30, N)).</summary>
        public static SolveInfo gcrodr<TPre>(in doubleBSR A, in TPre M, in doubleN b, ref doubleN x)
            where TPre : struct, IdoublePreconditioner
        {
            int r = math.min(30, A.M_Rows);
            return gcrodr(new doubleBSROperator(in A), in M, in b, ref x, r, doubleGcrodrDefaultRecycle(r), A.M_Rows, Consts.doubleSqrtEps);
        }
    }
}
