// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/NLS.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;

using Unity.Collections;
using Unity.Mathematics;

namespace BULA
{
    // ================================================================================================
    // Nonlinear least squares via Levenberg-Marquardt with Nielsen damping. Algorithm reference:
    // Madsen, Nielsen & Tingleff, "Methods for Non-Linear Least Squares Problems" (2nd ed., 2004),
    // Algorithm 3.16 -- the gain-ratio damping update (mu *= max(1/3, 1-(2*rho-1)^3) on accept,
    // mu *= nu, nu *= 2 on reject) and the convergence structure (the step-size test on the PROPOSED
    // step, before it is evaluated against the objective, so a reject/reject spiral trips SmallStep
    // instead of escalating mu without bound -- verified in the from-scratch numpy prototype against
    // a NIST StRD case that false-failed under a naive post-accept-only step check). The per-column
    // Marquardt scaling (D = diag of column norms of J, floored at its own running max) is the
    // well-known MINPACK convention, not transcribed from MINPACK source -- Math.NET Numerics'
    // LevenbergMarquardtMinimizer.cs (MIT) was read as an independent C# structural reference.
    // Robust-loss row rescaling (nlsApplyRobustScale) is scipy `optimize._lsq` (BSD-3):
    // least_squares.py's huber/cauchy loss definitions and common.py's scale_for_robust_loss_function,
    // verified line-by-line against the installed scipy source. Tukey biweight has no scipy
    // precedent (scipy ships no redescending loss); its Rho/RhoPrime/RhoPrime2 are the standard
    // robust-statistics biweight identities, derived independently (see Interfaces/DEVLOG.md).
    // ================================================================================================

    public static partial class Optimize
    {
        // ---- shared engine helpers (no TF/TLoss generics -- pure buffer arithmetic, reused by both
        // the numeric- and analytic-Jacobian cores) ---------------------------------------------------

        // D_j = max(running D_j, effective_j), effective_j = column-norm_j(J) for any column with a
        // genuine (however small) sensitivity, or the LARGEST real column norm this iteration for a
        // column at-or-below flatThresh -- see the file DEVLOG for why a plain per-type absolute
        // epsilon test (never scaled by the matrix's own magnitude) is required here, and why the
        // flat-column floor is the max REAL column norm rather than a small constant. d must be
        // pre-zeroed before the first call so that call also seeds D from J's own initial column
        // norms. colNorms is scratch sized to J.N_Cols (caches each column norm so the flat-floor
        // pass does not recompute it). Returns the max real (above-flatThresh) column norm seen this
        // call; 0 means every column is at-or-below flatThresh, so d was left unchanged by this call
        // -- on the very first call (d still all-zero) the caller must treat that as already
        // stationary rather than dividing by a zero scale.
        private static float nlsUpdateScale(ref floatN d, in floatMxN J, float flatThresh, ref floatN colNorms)
        {
            int m = J.M_Rows, n = J.N_Cols;

            float maxRealColNorm = (float)0;
            for (int j = 0; j < n; j++)
            {
                float s = (float)0;
                for (int i = 0; i < m; i++) { float v = J[i, j]; s += v * v; }
                float cn = math.sqrt(s);
                colNorms[j] = cn;
                if (cn > flatThresh && cn > maxRealColNorm) maxRealColNorm = cn;
            }

            for (int j = 0; j < n; j++)
            {
                float cn = colNorms[j];
                float effective = cn <= flatThresh ? maxRealColNorm : cn;
                if (effective > d[j]) d[j] = effective;
            }

            return maxRealColNorm;
        }

        private static float nlsMaxD2(in floatN d)
        {
            float best = (float)0;
            for (int j = 0; j < d.N; j++)
            {
                float v = d[j] * d[j];
                if (v > best) best = v;
            }
            return best;
        }

        // scipy optimize._lsq common.py `scale_for_robust_loss_function` (BSD-3): rescales (r, J) so
        // an ordinary (unweighted) damped least-squares step on the rescaled system reproduces one
        // IRLS step of the robust loss. J_scale is floored at Consts.floatEpsilon (not zero) -- a
        // residual whose rho'' term drives rho'+2*rho''*s negative (a redescending loss past its
        // own transition) must not divide by a non-positive number.
        private static void nlsApplyRobustScale<TLoss>(in floatN r, in floatMxN J, ref floatN rs, ref floatMxN Js, in TLoss loss)
            where TLoss : struct, IfloatRobustLoss
        {
            int m = J.M_Rows, n = J.N_Cols;
            float floorEps = Consts.floatEpsilon;
            for (int i = 0; i < m; i++)
            {
                float ri = r[i];
                float s = ri * ri;
                float rp = loss.RhoPrime(s);
                float rp2 = loss.RhoPrime2(s);
                float jscale = math.sqrt(math.max(rp + (float)2 * rp2 * s, floorEps));
                rs[i] = ri * (rp / jscale);
                for (int j = 0; j < n; j++)
                    Js[i, j] = J[i, j] * jscale;
            }
        }

        // Forward/central finite-difference Jacobian. Per-parameter relative step h_j =
        // sqrt(max(epsfcn, eps)) * max(|p_j|, 1) -- MINPACK's own numerical-differencing convention.
        private static void nlsNumericJacobian<TF>(ref TF f, in floatN p, in floatN r0, ref floatMxN J,
            NLSJacobianMode mode, float epsfcn, ref floatN pPert, ref floatN rPert, ref floatN rPert2)
            where TF : struct, IfloatResidualFunction
        {
            int n = p.N, m = r0.N;
            float hEps = math.sqrt(math.max(epsfcn, Consts.floatEpsilon));

            for (int j = 0; j < n; j++)
            {
                float pj = p[j];
                float step = hEps * math.max(math.abs(pj), (float)1);

                for (int k = 0; k < n; k++) pPert[k] = p[k];
                pPert[j] = pj + step;
                f.Residuals(in pPert, ref rPert);

                if (mode == NLSJacobianMode.Central)
                {
                    pPert[j] = pj - step;
                    f.Residuals(in pPert, ref rPert2);
                    float inv = (float)1 / ((float)2 * step);
                    for (int i = 0; i < m; i++) J[i, j] = (rPert[i] - rPert2[i]) * inv;
                }
                else
                {
                    float inv = (float)1 / step;
                    for (int i = 0; i < m; i++) J[i, j] = (rPert[i] - r0[i]) * inv;
                }
            }
        }

        // Damped augmented least squares: [Js; sqrt(mu)*diag(d)] h = [-rs; 0], solved via QR.solveInPlace
        // (m+n x n, tall by construction -- full column rank as long as mu > 0, since d is floored
        // away from zero). Returns false only if h itself comes back non-finite (mu overflow).
        private static bool nlsSolveStep(in floatMxN Js, in floatN rs, in floatN d, float mu,
            ref floatMxN Aaug, ref floatN baug, ref floatN h, ref floatN u, ref floatN w)
        {
            int m = Js.M_Rows, n = Js.N_Cols;

            for (int i = 0; i < m; i++)
                for (int j = 0; j < n; j++)
                    Aaug[i, j] = Js[i, j];

            float sq = math.sqrt(mu);
            for (int i = 0; i < n; i++)
            {
                for (int j = 0; j < n; j++)
                    Aaug[m + i, j] = (float)0;
                Aaug[m + i, i] = sq * d[i];
            }

            for (int i = 0; i < m; i++) baug[i] = -rs[i];
            for (int i = 0; i < n; i++) baug[m + i] = (float)0;

            QR.solveInPlace(ref Aaug, ref baug, ref h, ref u, ref w);

            for (int j = 0; j < n; j++)
                if (!math.isfinite(h[j])) return false;
            return true;
        }

        // Convergence bookkeeping (cost, gain ratio, gradient/step norms) accumulates in double --
        // same idiom as ladIRLS's own dx/xn convergence check -- while J, r, h, d, mu stay float
        // (the actual factorized system QR.solveInPlace consumes).
        private static double nlsCost(in floatN r)
        {
            double s = 0;
            for (int i = 0; i < r.N; i++) { double v = r[i]; s += v * v; }
            return 0.5 * s;
        }

        private static double nlsCostRobust<TLoss>(in floatN r, in TLoss loss)
            where TLoss : struct, IfloatRobustLoss
        {
            double s = 0;
            for (int i = 0; i < r.N; i++)
            {
                float ri = r[i];
                s += (double)loss.Rho(ri * ri);
            }
            return 0.5 * s;
        }

        private static double nlsScaledGradNorm(in floatN g, in floatN d)
        {
            double best = 0;
            for (int j = 0; j < g.N; j++)
            {
                double v = math.abs((double)g[j] / (double)d[j]);
                if (v > best) best = v;
            }
            return best;
        }

        private static double nlsL2Double(in floatN v)
        {
            double s = 0;
            for (int i = 0; i < v.N; i++) { double x = v[i]; s += x * x; }
            return math.sqrt(s);
        }

        private static double nlsPredictedReduction(in floatN h, in floatN d, float mu, in floatN g)
        {
            double s = 0;
            for (int j = 0; j < h.N; j++)
            {
                double dj = d[j];
                double term = (double)mu * dj * dj * (double)h[j] - (double)g[j];
                s += (double)h[j] * term;
            }
            return 0.5 * s;
        }

        // ---- numeric-Jacobian core (shared by the plain and robust-loss overloads: floatL2Loss is
        // the identity element of nlsApplyRobustScale, so the unweighted overloads route through here
        // too instead of duplicating the loop) ----------------------------------------------------------

        private static NLSInfo nlsSolveNumericCore<TF, TLoss>(ref TF f, ref floatN p, int m, in TLoss loss,
            float gradTol, float stepTol, int maxIter, NLSJacobianMode jacobianMode, float epsfcn)
            where TF : struct, IfloatResidualFunction
            where TLoss : struct, IfloatRobustLoss
        {
            int n = p.N;
            if (m <= 0) throw new ArgumentException("nlsSolve: m must be positive");
            if (n <= 0) throw new ArgumentException("nlsSolve: p.N must be positive");
            if (maxIter < 1) throw new ArgumentException("nlsSolve: maxIter must be >= 1");

            var r = new floatN(m, Allocator.Temp, true);
            var J = new floatMxN(m, n, Allocator.Temp, true);
            var rs = new floatN(m, Allocator.Temp, true);
            var Js = new floatMxN(m, n, Allocator.Temp, true);
            var d = new floatN(n, Allocator.Temp);
            var colNorms = new floatN(n, Allocator.Temp, true);
            var g = new floatN(n, Allocator.Temp, true);
            var h = new floatN(n, Allocator.Temp, true);
            var Aaug = new floatMxN(m + n, n, Allocator.Temp, true);
            var baug = new floatN(m + n, Allocator.Temp, true);
            var u = new floatN(m + n, Allocator.Temp, true);
            var w = new floatN(n, Allocator.Temp, true);
            var pTrial = new floatN(n, Allocator.Temp, true);
            var rTrial = new floatN(m, Allocator.Temp, true);
            var pPert = new floatN(n, Allocator.Temp, true);
            var rPert = new floatN(m, Allocator.Temp, true);
            var rPert2 = new floatN(m, Allocator.Temp, true);

            f.Residuals(in p, ref r);
            nlsNumericJacobian(ref f, in p, in r, ref J, jacobianMode, epsfcn, ref pPert, ref rPert, ref rPert2);

            double cost = nlsCostRobust(in r, in loss);

            NLSStatus status;
            int it = 0;
            double gnorm;

            // flatThresh classifies a column as flat/negligible -- NOT Consts.floatSqrtEps *
            // LInfJ0 (a threshold scaled by the WHOLE Jacobian's magnitude cross-contaminates
            // columns of genuinely different natural scale: a parameter with a small-but-real
            // derivative gets misclassified as flat and floored up to another parameter's much
            // larger scale, destroying its own gradient signal; found empirically on a NIST StRD
            // case whose two parameters' sensitivities differ by ~1e6x). A plain per-type epsilon
            // (no matrix-scale multiplier) only classifies a column as flat when it is actually
            // at-or-below machine precision for ITS OWN norm -- see nlsUpdateScale for what a
            // flat column is floored TO (not this threshold itself).
            float flatThresh = Consts.floatEpsilon;
            float maxRealColNorm0 = nlsUpdateScale(ref d, in J, flatThresh, ref colNorms);

            if (maxRealColNorm0 <= (float)0)
            {
                // Every column is at-or-below flatThresh (includes the literal-zero Jacobian): d is
                // left all-zero and unusable as a scale -- already stationary, nothing to move.
                status = NLSStatus.Converged;
                gnorm = 0;
            }
            else
            {
                nlsApplyRobustScale(in r, in J, ref rs, ref Js, in loss);
                Blas.dot(in rs, in Js, ref g);

                double gnorm0 = nlsScaledGradNorm(in g, in d);
                double floorAbs = math.sqrt((double)Consts.floatEpsilon);
                float mu = (float)1e-3 * nlsMaxD2(in d);
                float nu = (float)2;
                float muMax = (float)1 / (Consts.floatEpsilon * Consts.floatEpsilon);

                gnorm = gnorm0;
                bool stop = gnorm <= gradTol * math.max(gnorm0, floorAbs);
                status = stop ? NLSStatus.Converged : NLSStatus.MaxIterations;

                while (!stop && it < maxIter)
                {
                    bool solveOk = nlsSolveStep(in Js, in rs, in d, mu, ref Aaug, ref baug, ref h, ref u, ref w);
                    if (!solveOk) { status = NLSStatus.FailedLinearSolve; break; }

                    double pNorm = nlsL2Double(in p);
                    double hNorm = nlsL2Double(in h);
                    if (hNorm <= (double)stepTol * (pNorm + (double)stepTol))
                    {
                        status = NLSStatus.SmallStep;
                        stop = true;
                        break;
                    }

                    for (int j = 0; j < n; j++) pTrial[j] = p[j] + h[j];
                    f.Residuals(in pTrial, ref rTrial);
                    double costNew = nlsCostRobust(in rTrial, in loss);

                    double predicted = nlsPredictedReduction(in h, in d, mu, in g);
                    double actual = cost - costNew;
                    double rhoGain = predicted > 0 ? actual / predicted : -1.0;

                    it++;
                    if (rhoGain > 0)
                    {
                        for (int j = 0; j < n; j++) p[j] = pTrial[j];
                        r.CopyFrom(in rTrial);
                        cost = costNew;

                        nlsNumericJacobian(ref f, in p, in r, ref J, jacobianMode, epsfcn, ref pPert, ref rPert, ref rPert2);
                        nlsUpdateScale(ref d, in J, flatThresh, ref colNorms);
                        nlsApplyRobustScale(in r, in J, ref rs, ref Js, in loss);
                        Blas.dot(in rs, in Js, ref g);

                        double factor = math.max(1.0 / 3.0, 1.0 - (2.0 * rhoGain - 1.0) * (2.0 * rhoGain - 1.0) * (2.0 * rhoGain - 1.0));
                        mu = mu * (float)factor;
                        nu = (float)2;

                        gnorm = nlsScaledGradNorm(in g, in d);
                        if (gnorm <= gradTol * math.max(gnorm0, floorAbs))
                        {
                            status = NLSStatus.Converged;
                            stop = true;
                        }
                    }
                    else
                    {
                        mu = mu * nu;
                        nu = nu * (float)2;
                    }

                    if (!math.isfinite(mu) || mu > muMax)
                    {
                        status = NLSStatus.FailedLinearSolve;
                        break;
                    }
                }

                gnorm = nlsScaledGradNorm(in g, in d);
            }

            double rnorm = nlsL2Double(in r);

            rPert2.Dispose(); rPert.Dispose(); pPert.Dispose();
            rTrial.Dispose(); pTrial.Dispose();
            w.Dispose(); u.Dispose(); baug.Dispose(); Aaug.Dispose();
            h.Dispose(); g.Dispose(); colNorms.Dispose(); d.Dispose(); Js.Dispose(); rs.Dispose(); J.Dispose(); r.Dispose();

            return new NLSInfo { status = status, iterations = it, objective = cost, residualNorm = rnorm, gradientNorm = gnorm };
        }

        // ---- analytic-Jacobian core (no robust-loss overload in v1 -- see file DEVLOG) -----------------

        private static NLSInfo nlsSolveAnalyticCore<TF>(ref TF f, ref floatN p, int m,
            float gradTol, float stepTol, int maxIter)
            where TF : struct, IfloatResidualJacobian
        {
            int n = p.N;
            if (m <= 0) throw new ArgumentException("nlsSolve: m must be positive");
            if (n <= 0) throw new ArgumentException("nlsSolve: p.N must be positive");
            if (maxIter < 1) throw new ArgumentException("nlsSolve: maxIter must be >= 1");

            var r = new floatN(m, Allocator.Temp, true);
            var J = new floatMxN(m, n, Allocator.Temp, true);
            var d = new floatN(n, Allocator.Temp);
            var colNorms = new floatN(n, Allocator.Temp, true);
            var g = new floatN(n, Allocator.Temp, true);
            var h = new floatN(n, Allocator.Temp, true);
            var Aaug = new floatMxN(m + n, n, Allocator.Temp, true);
            var baug = new floatN(m + n, Allocator.Temp, true);
            var u = new floatN(m + n, Allocator.Temp, true);
            var w = new floatN(n, Allocator.Temp, true);
            var pTrial = new floatN(n, Allocator.Temp, true);
            var rTrial = new floatN(m, Allocator.Temp, true);

            f.Residuals(in p, ref r);
            f.Jacobian(in p, ref J);

            double cost = nlsCost(in r);

            NLSStatus status;
            int it = 0;
            double gnorm;

            // flatThresh classifies a column as flat/negligible -- NOT Consts.floatSqrtEps *
            // LInfJ0 (a threshold scaled by the WHOLE Jacobian's magnitude cross-contaminates
            // columns of genuinely different natural scale: a parameter with a small-but-real
            // derivative gets misclassified as flat and floored up to another parameter's much
            // larger scale, destroying its own gradient signal; found empirically on a NIST StRD
            // case whose two parameters' sensitivities differ by ~1e6x). A plain per-type epsilon
            // (no matrix-scale multiplier) only classifies a column as flat when it is actually
            // at-or-below machine precision for ITS OWN norm -- see nlsUpdateScale for what a
            // flat column is floored TO (not this threshold itself).
            float flatThresh = Consts.floatEpsilon;
            float maxRealColNorm0 = nlsUpdateScale(ref d, in J, flatThresh, ref colNorms);

            if (maxRealColNorm0 <= (float)0)
            {
                // Every column is at-or-below flatThresh (includes the literal-zero Jacobian): d is
                // left all-zero and unusable as a scale -- already stationary, nothing to move.
                status = NLSStatus.Converged;
                gnorm = 0;
            }
            else
            {
                Blas.dot(in r, in J, ref g);

                double gnorm0 = nlsScaledGradNorm(in g, in d);
                double floorAbs = math.sqrt((double)Consts.floatEpsilon);
                float mu = (float)1e-3 * nlsMaxD2(in d);
                float nu = (float)2;
                float muMax = (float)1 / (Consts.floatEpsilon * Consts.floatEpsilon);

                gnorm = gnorm0;
                bool stop = gnorm <= gradTol * math.max(gnorm0, floorAbs);
                status = stop ? NLSStatus.Converged : NLSStatus.MaxIterations;

                while (!stop && it < maxIter)
                {
                    bool solveOk = nlsSolveStep(in J, in r, in d, mu, ref Aaug, ref baug, ref h, ref u, ref w);
                    if (!solveOk) { status = NLSStatus.FailedLinearSolve; break; }

                    double pNorm = nlsL2Double(in p);
                    double hNorm = nlsL2Double(in h);
                    if (hNorm <= (double)stepTol * (pNorm + (double)stepTol))
                    {
                        status = NLSStatus.SmallStep;
                        stop = true;
                        break;
                    }

                    for (int j = 0; j < n; j++) pTrial[j] = p[j] + h[j];
                    f.Residuals(in pTrial, ref rTrial);
                    double costNew = nlsCost(in rTrial);

                    double predicted = nlsPredictedReduction(in h, in d, mu, in g);
                    double actual = cost - costNew;
                    double rhoGain = predicted > 0 ? actual / predicted : -1.0;

                    it++;
                    if (rhoGain > 0)
                    {
                        for (int j = 0; j < n; j++) p[j] = pTrial[j];
                        r.CopyFrom(in rTrial);
                        cost = costNew;

                        f.Jacobian(in p, ref J);
                        nlsUpdateScale(ref d, in J, flatThresh, ref colNorms);
                        Blas.dot(in r, in J, ref g);

                        double factor = math.max(1.0 / 3.0, 1.0 - (2.0 * rhoGain - 1.0) * (2.0 * rhoGain - 1.0) * (2.0 * rhoGain - 1.0));
                        mu = mu * (float)factor;
                        nu = (float)2;

                        gnorm = nlsScaledGradNorm(in g, in d);
                        if (gnorm <= gradTol * math.max(gnorm0, floorAbs))
                        {
                            status = NLSStatus.Converged;
                            stop = true;
                        }
                    }
                    else
                    {
                        mu = mu * nu;
                        nu = nu * (float)2;
                    }

                    if (!math.isfinite(mu) || mu > muMax)
                    {
                        status = NLSStatus.FailedLinearSolve;
                        break;
                    }
                }

                gnorm = nlsScaledGradNorm(in g, in d);
            }

            double rnorm = nlsL2Double(in r);

            rTrial.Dispose(); pTrial.Dispose();
            w.Dispose(); u.Dispose(); baug.Dispose(); Aaug.Dispose();
            h.Dispose(); g.Dispose(); colNorms.Dispose(); d.Dispose(); J.Dispose(); r.Dispose();

            return new NLSInfo { status = status, iterations = it, objective = cost, residualNorm = rnorm, gradientNorm = gnorm };
        }

        // ==== public entry points =======================================================================

        /// <summary>
        /// Levenberg-Marquardt (Nielsen damping) nonlinear least squares: minimizes 0.5·‖r(p)‖²,
        /// r given by <typeparamref name="TF"/>. Numeric (finite-difference) Jacobian.
        /// <paramref name="p"/> is both the initial guess and the overwritten result (length n, the
        /// parameter count). <paramref name="m"/> is the residual count (r.N). Converged once the
        /// scaled gradient infinity-norm falls to <paramref name="gradTol"/> times its own value at
        /// the start (never an assumed O(1) scale); SmallStep once the proposed step falls to
        /// <paramref name="stepTol"/>·(‖p‖+stepTol). Job-safe (Allocator.Temp scratch, disposed
        /// before returning).
        /// </summary>
        public static NLSInfo nlsSolve<TF>(ref TF f, ref floatN p, int m,
            float gradTol, float stepTol, int maxIter, NLSJacobianMode jacobianMode, float epsfcn)
            where TF : struct, IfloatResidualFunction
        {
            var loss = new floatL2Loss();
            return nlsSolveNumericCore(ref f, ref p, m, in loss, gradTol, stepTol, maxIter, jacobianMode, epsfcn);
        }

        /// <summary>nlsSolve with a default noise floor (epsfcn = 0, i.e. machine epsilon only).</summary>
        public static NLSInfo nlsSolve<TF>(ref TF f, ref floatN p, int m,
            float gradTol, float stepTol, int maxIter, NLSJacobianMode jacobianMode)
            where TF : struct, IfloatResidualFunction
            => nlsSolve(ref f, ref p, m, gradTol, stepTol, maxIter, jacobianMode, (float)0);

        /// <summary>nlsSolve with default tolerances (gradTol = Consts.floatSqrtEps, stepTol =
        /// Consts.floatEpsilon), maxIter (200), Jacobian mode (Forward) and epsfcn (0).</summary>
        public static NLSInfo nlsSolve<TF>(ref TF f, ref floatN p, int m)
            where TF : struct, IfloatResidualFunction
            => nlsSolve(ref f, ref p, m, Consts.floatSqrtEps, Consts.floatEpsilon, 200, NLSJacobianMode.Forward, (float)0);

        /// <summary>
        /// Levenberg-Marquardt nonlinear least squares with an ANALYTIC Jacobian
        /// (<typeparamref name="TF"/> : <see cref="IfloatResidualJacobian"/>) -- otherwise identical
        /// contract to the numeric-Jacobian overload above.
        /// </summary>
        public static NLSInfo nlsSolve<TF>(ref TF f, ref floatN p, int m,
            float gradTol, float stepTol, int maxIter)
            where TF : struct, IfloatResidualJacobian
            => nlsSolveAnalyticCore(ref f, ref p, m, gradTol, stepTol, maxIter);

        /// <summary>
        /// Levenberg-Marquardt nonlinear least squares under a robust <typeparamref name="TLoss"/>
        /// (scipy-style per-iteration row rescale of r/J, see <see cref="IfloatRobustLoss"/>) --
        /// otherwise identical contract to the plain numeric-Jacobian overload above. Numeric
        /// Jacobian only (no analytic-Jacobian + robust-loss combination in v1).
        /// </summary>
        public static NLSInfo nlsSolve<TF, TLoss>(ref TF f, ref floatN p, int m, in TLoss loss,
            float gradTol, float stepTol, int maxIter, NLSJacobianMode jacobianMode, float epsfcn)
            where TF : struct, IfloatResidualFunction
            where TLoss : struct, IfloatRobustLoss
            => nlsSolveNumericCore(ref f, ref p, m, in loss, gradTol, stepTol, maxIter, jacobianMode, epsfcn);

        /// <summary>nlsSolve (robust loss) with a default Jacobian mode (Forward) and epsfcn (0).</summary>
        public static NLSInfo nlsSolve<TF, TLoss>(ref TF f, ref floatN p, int m, in TLoss loss,
            float gradTol, float stepTol, int maxIter)
            where TF : struct, IfloatResidualFunction
            where TLoss : struct, IfloatRobustLoss
            => nlsSolve(ref f, ref p, m, in loss, gradTol, stepTol, maxIter, NLSJacobianMode.Forward, (float)0);

        /// <summary>nlsSolve (robust loss) with default tolerances/maxIter (see the 3-arg overload).</summary>
        public static NLSInfo nlsSolve<TF, TLoss>(ref TF f, ref floatN p, int m, in TLoss loss)
            where TF : struct, IfloatResidualFunction
            where TLoss : struct, IfloatRobustLoss
            => nlsSolve(ref f, ref p, m, in loss, Consts.floatSqrtEps, Consts.floatEpsilon, 200);

        // ==== curveFit facade ===========================================================================

        // r_i = model.Eval(x_i, p) - y_i. Internal -- not part of the public API surface, only the
        // vehicle curveFit uses to reach nlsSolve<TF>'s numeric-Jacobian path.
        private struct floatCurveFitResidual<TModel> : IfloatResidualFunction
            where TModel : struct, IfloatCurveModel
        {
            public TModel Model;
            public floatN X;
            public floatN Y;

            public void Residuals(in floatN p, ref floatN r)
            {
                for (int i = 0; i < r.N; i++)
                    r[i] = Model.Eval(X[i], in p) - Y[i];
            }
        }

        // r_i = (model.Eval(x_i, p) - y_i) / sigma_i -- standard chi-square weighting (sigma =
        // per-point standard deviation, not a raw weight).
        private struct floatCurveFitWeightedResidual<TModel> : IfloatResidualFunction
            where TModel : struct, IfloatCurveModel
        {
            public TModel Model;
            public floatN X;
            public floatN Y;
            public floatN Sigma;

            public void Residuals(in floatN p, ref floatN r)
            {
                for (int i = 0; i < r.N; i++)
                    r[i] = (Model.Eval(X[i], in p) - Y[i]) / Sigma[i];
            }
        }

        /// <summary>
        /// Curve-fit facade over <see cref="nlsSolve{TF}(ref TF, ref floatN, int)"/>: fits
        /// <typeparamref name="TModel"/>'s y = f(x; p) to (xdata, ydata) by nonlinear least squares,
        /// minimizing 0.5·Σ(f(x_i; p) - y_i)². <paramref name="p"/> is both the initial guess and the
        /// overwritten result. Numeric Jacobian (forward difference) only.
        /// </summary>
        public static NLSInfo curveFit<TModel>(in floatN xdata, in floatN ydata, ref TModel model, ref floatN p,
            float gradTol, float stepTol, int maxIter)
            where TModel : struct, IfloatCurveModel
        {
            if (xdata.N != ydata.N)
                throw new ArgumentException("curveFit: xdata.N must equal ydata.N");

            var residual = new floatCurveFitResidual<TModel> { Model = model, X = xdata, Y = ydata };
            return nlsSolve(ref residual, ref p, xdata.N, gradTol, stepTol, maxIter, NLSJacobianMode.Forward, (float)0);
        }

        /// <summary>curveFit with default tolerances (gradTol = Consts.floatSqrtEps, stepTol =
        /// Consts.floatEpsilon) and maxIter (200).</summary>
        public static NLSInfo curveFit<TModel>(in floatN xdata, in floatN ydata, ref TModel model, ref floatN p)
            where TModel : struct, IfloatCurveModel
            => curveFit(in xdata, in ydata, ref model, ref p, Consts.floatSqrtEps, Consts.floatEpsilon, 200);

        /// <summary>
        /// curveFit weighted by a per-point standard deviation <paramref name="sigma"/>: minimizes
        /// 0.5·Σ((f(x_i; p) - y_i)/sigma_i)² (standard chi-square fitting).
        /// </summary>
        public static NLSInfo curveFit<TModel>(in floatN xdata, in floatN ydata, in floatN sigma, ref TModel model, ref floatN p,
            float gradTol, float stepTol, int maxIter)
            where TModel : struct, IfloatCurveModel
        {
            if (xdata.N != ydata.N)
                throw new ArgumentException("curveFit: xdata.N must equal ydata.N");
            if (sigma.N != xdata.N)
                throw new ArgumentException("curveFit: sigma.N must equal xdata.N");

            var residual = new floatCurveFitWeightedResidual<TModel> { Model = model, X = xdata, Y = ydata, Sigma = sigma };
            return nlsSolve(ref residual, ref p, xdata.N, gradTol, stepTol, maxIter, NLSJacobianMode.Forward, (float)0);
        }

        /// <summary>Weighted curveFit with default tolerances/maxIter (see the unweighted 4-arg overload).</summary>
        public static NLSInfo curveFit<TModel>(in floatN xdata, in floatN ydata, in floatN sigma, ref TModel model, ref floatN p)
            where TModel : struct, IfloatCurveModel
            => curveFit(in xdata, in ydata, in sigma, ref model, ref p, Consts.floatSqrtEps, Consts.floatEpsilon, 200);
    }
}
