// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/QR.Workspace.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using Unity.Collections;

namespace LinearAlgebra
{
    public static partial class QR
    {
        /// <summary>
        /// Throws if <paramref name="ws"/> is not sized for an m x n QR problem. u (m) and w (n) are
        /// needed by every cache overload (decomp/decompInPlace/solveInPlace); the five blocked-WY
        /// buffers (Vpanel, Tbuf, Wbuf, tcolBuf, VfullBuf) are needed only when the caller is about to
        /// engage the level-3 blocked kernel (decomp/decompInPlace once N_Cols &gt;= 2*QR_BLOCK) — NOT
        /// by solveInPlace, whose fused kernel never forms Q and so has no use for them. Matches
        /// the doubleQRCache(m, n, allocator) constructor.
        /// </summary>
        static void RequireQRWorkspace(in doubleQRCache ws, int m, int n, bool needBlocked)
        {
            // Panel width for the blocked (level-3 / compact-WY) path. Method-local (not a class
            // field): QR merges across the float/double generated partials, so a class-level const
            // of this name would collide (CS0102) — see qrDecompositionBlockedCore.
            const int QR_BLOCK = 32;

            bool ok =
                ws.u.N == m &&
                ws.w.N == n &&
                (!needBlocked ||
                 (ws.Vpanel.N == m * QR_BLOCK &&
                  ws.Tbuf.N == QR_BLOCK * QR_BLOCK &&
                  ws.Wbuf.N == QR_BLOCK * n &&
                  ws.tcolBuf.N == QR_BLOCK &&
                  ws.VfullBuf.N == m * n));

            if (!ok)
                throw new ArgumentException("QR: workspace must be sized for m x n (use new doubleQRCache(m, n, allocator))");
        }
    }

    /// <summary>
    /// Reusable scratch for QR's cache overloads (decomp / decompInPlace / solveInPlace). Allocate
    /// ONCE via the Allocator ctor and reuse across same-shape calls to avoid the per-call
    /// Allocator.Temp allocations the allocating overloads make internally.
    ///
    /// u (length m) and w (length n) are the Householder-reflector scratch shared by every overload
    /// (the same pair the raw <c>ref u, ref w</c> level-2 overloads take). Vpanel (m*QR_BLOCK), Tbuf
    /// (QR_BLOCK*QR_BLOCK), Wbuf (QR_BLOCK*n), tcolBuf (QR_BLOCK) and VfullBuf (m*n) are the level-3
    /// (compact-WY) blocked-factorization buffers — see qrDecompositionBlockedCore. decomp/decompInPlace
    /// engage them once N_Cols &gt;= 2*QR_BLOCK (the same gate, and the same kernel, as the fully
    /// allocating overload — so the cache overload is bit-identical to it, just fed from caller-owned
    /// buffers instead of Allocator.Temp). solveInPlace's fused kernel never forms Q, so it only ever
    /// touches u/w — the blocked buffers sit unused for that call, exactly as CHOP's rank-Gram buffers
    /// or Bidiag's leftU sit unused for calls that don't need them.
    /// </summary>
    public struct doubleQRCache : IDisposable
    {
        public doubleN u;
        public doubleN w;
        public doubleN Vpanel;
        public doubleN Tbuf;
        public doubleN Wbuf;
        public doubleN tcolBuf;
        public doubleN VfullBuf;

        /// <summary>Allocates a QR workspace for an m x n (m &gt;= n) system. Pair with <see cref="Dispose"/>.</summary>
        public doubleQRCache(int m, int n, Allocator allocator)
        {
            // See qrDecompositionBlockedCore for why this is a method-local const, not a class field.
            const int QR_BLOCK = 32;

            u = new doubleN(m, allocator);
            w = new doubleN(n, allocator);
            Vpanel = new doubleN(m * QR_BLOCK, allocator);
            Tbuf = new doubleN(QR_BLOCK * QR_BLOCK, allocator);
            Wbuf = new doubleN(QR_BLOCK * n, allocator);
            tcolBuf = new doubleN(QR_BLOCK, allocator);
            VfullBuf = new doubleN(m * n, allocator);
        }

        /// <summary>Dispose when done.</summary>
        public void Dispose()
        {
            u.Dispose();
            w.Dispose();
            Vpanel.Dispose();
            Tbuf.Dispose();
            Wbuf.Dispose();
            tcolBuf.Dispose();
            VfullBuf.Dispose();
        }
    }
}
