// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/SelectOP.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using Unity.Burst;
using Unity.Mathematics;
using LinearAlgebra.Internal;

namespace LinearAlgebra
{

    /// <summary>
    /// Elementwise and scalar-bool select: returns b where c is true, a otherwise. Overloaded over
    /// vector/matrix and per-element/scalar bool <c>c</c>, for float, iProxy, and bool element types.
    /// </summary>
    public static partial class Select
    {
        // ref-dest primitive. No alias guard: select is elementwise (dst[i] = c[i] ? b[i] : a[i]),
        // so the destination may alias a or b safely.
        public static void select(in floatN a, in floatN b, in boolN c, ref floatN dest)
        {
            Assume.SameDim(in a, in b);
            Assume.SameDim(in a, in c);

            if (dest.N != a.N)
                throw new ArgumentException("select: dest.N must equal a.N");

            unsafe
            {
                UnsafeSelectOP.selectfloat(a.Data.Ptr, b.Data.Ptr, c.Data.Ptr, dest.Data.Ptr, a.N);
            }
        }

        public static floatN select(in floatN a, in floatN b, in boolN c)
        {
            floatN res = a.floatTempVec(a.N, true);
            select(in a, in b, in c, ref res);
            return res;
        }

        // ref-dest primitive. No alias guard: elementwise op.
        public static void select(in floatMxN a, in floatMxN b, in boolMxN c, ref floatMxN dest)
        {
            Assume.SameDim(in a, in b);
            Assume.SameDim(in a, in c);

            if (dest.M_Rows != a.M_Rows || dest.N_Cols != a.N_Cols)
                throw new ArgumentException("select: dest dimensions must match a");

            unsafe
            {
                UnsafeSelectOP.selectfloat(a.Data.Ptr, b.Data.Ptr, c.Data.Ptr, dest.Data.Ptr, a.M_Rows * a.N_Cols);
            }
        }

        public static floatMxN select(in floatMxN a, in floatMxN b, in boolMxN c)
        {
            floatMxN res = a.floatTempMat(a.M_Rows, a.N_Cols, true);
            select(in a, in b, in c, ref res);
            return res;
        }

        // ref-dest primitive. No alias guard: scalar bool selects the whole source unchanged.
        public static void select(in floatN a, in floatN b, in bool c, ref floatN dest)
        {
            Assume.SameDim(in a, in b);

            if (dest.N != a.N)
                throw new ArgumentException("select: dest.N must equal a.N");

            if (c)
                dest.CopyFrom(in b);
            else
                dest.CopyFrom(in a);
        }

        public static floatN select(in floatN a, in floatN b, in bool c)
        {
            return c ? b.TempCopy() : a.TempCopy();
        }

        // Matrix analog of the scalar-bool vector overload above (same no-alias reasoning).
        public static void select(in floatMxN a, in floatMxN b, in bool c, ref floatMxN dest)
        {
            Assume.SameDim(in a, in b);

            if (dest.M_Rows != a.M_Rows || dest.N_Cols != a.N_Cols)
                throw new ArgumentException("select: dest dimensions must match a");

            if (c)
                dest.CopyFrom(in b);
            else
                dest.CopyFrom(in a);
        }

        public static floatMxN select(in floatMxN a, in floatMxN b, in bool c)
        {
            return c ? b.TempCopy() : a.TempCopy();
        }
    }
}

namespace LinearAlgebra.Internal
{
    public static unsafe partial class UnsafeSelectOP
    {
        // a/b carry no [NoAlias]: the public select contract allows target to alias either input
        // (elementwise, each index reads before it writes). c is a different element type and
        // cannot alias the float pointers through the public API.
        public static void selectfloat(float* a, float* b, [NoAlias] bool* c, float* target, int n)
        {
            for (int i = 0; i < n; i++)
                target[i] = math.select(a[i], b[i], c[i]);
        }
    }
}
