// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/OP/WideOP.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System.Runtime.CompilerServices;

using Unity.Burst;
using Unity.Burst.Intrinsics;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Mathematics;


#pragma warning disable 0162 // template-only: both dtype arms coexist here, so the second is dead code until codegen splits them

namespace BULA.Internal
{
    // Widest per-dtype SIMD vector for level-1 kernels: 8 float lanes (one AVX ymm register)
    // or 4 double lanes (double4 — 256 bits is already double's full AVX2 width). Kernels
    // written against doubleW get the full register width for BOTH element types from one
    // template body. Storage is always a 32-byte v256; the double side reinterprets it as a
    // double4 (same size, zero-cost) and uses native vector math.
    //
    // Numeric contract: every operation is lane-independent except HSum, whose fold order is
    // FIXED below (halves first, then the balanced width-4 tree). A kernel's summation tree is
    // therefore identical between the AVX path, the non-AVX lane-wise fallback, and Mono —
    // bit-identical results on every path. The float fallback is a correctness path (pre-2011
    // CPUs and managed execution), not a fast path.
    internal unsafe struct doubleW
    {
        /// <summary>Lanes per vector: 8 (float) / 4 (double).</summary>
        /// <remarks>The template placeholder must be 8: the template assembly's own tests RUN
        /// this code with the 4-byte float-backed double stub, so the template-compiled variant
        /// must be the float (8-lane) configuration or every wide load overlaps.</remarks>
        public const int Width = 4;

        public v256 v;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static doubleW Load([NoAlias] double* p, int i)
        {
            
            return new doubleW { v = *(v256*)(p + (long)i * Width) };
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void Store([NoAlias] double* p, int i, doubleW w)
        {
            
            *(v256*)(p + (long)i * Width) = w.v;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static doubleW Splat(double s)
        {
            
            
            double4 r = new double4(s, s, s, s);
            return new doubleW { v = UnsafeUtility.As<double4, v256>(ref r) };
            
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static doubleW operator -(doubleW a, doubleW b)
        {
            
            
            double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
            double4 bv = UnsafeUtility.As<v256, double4>(ref b.v);
            double4 r = av - bv;
            return new doubleW { v = UnsafeUtility.As<double4, v256>(ref r) };
            
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static doubleW operator +(doubleW a, doubleW b)
        {
            
            
            {
                double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
                double4 bv = UnsafeUtility.As<v256, double4>(ref b.v);
                double4 r = av + bv;
                return new doubleW { v = UnsafeUtility.As<double4, v256>(ref r) };
            }
            
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static doubleW operator *(doubleW a, doubleW b)
        {
            
            
            {
                double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
                double4 bv = UnsafeUtility.As<v256, double4>(ref b.v);
                double4 r = av * bv;
                return new doubleW { v = UnsafeUtility.As<double4, v256>(ref r) };
            }
            
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static doubleW operator /(doubleW a, doubleW b)
        {
            
            
            {
                double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
                double4 bv = UnsafeUtility.As<v256, double4>(ref b.v);
                double4 r = av / bv;
                return new doubleW { v = UnsafeUtility.As<double4, v256>(ref r) };
            }
            
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static doubleW Abs(doubleW a)
        {
            
            
            double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
            double4 r = math.abs(av);
            return new doubleW { v = UnsafeUtility.As<double4, v256>(ref r) };
            
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static doubleW Max(doubleW a, doubleW b)
        {
            
            
            if (X86.Avx.IsAvxSupported)
                return new doubleW { v = X86.Avx.mm256_max_pd(a.v, b.v) };
            double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
            double4 bv = UnsafeUtility.As<v256, double4>(ref b.v);
            double4 r = math.max(av, bv);
            return new doubleW { v = UnsafeUtility.As<double4, v256>(ref r) };
            
        }

        // Fixed max-fold companion to HSum (max is exact, so the order only matters for a
        // consistent NaN story — kept fixed anyway).
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static double HMax(doubleW a)
        {
            
            
            double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
            return math.max(math.max(av.x, av.y), math.max(av.z, av.w));
            
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static doubleW Min(doubleW a, doubleW b)
        {
            
            
            if (X86.Avx.IsAvxSupported)
                return new doubleW { v = X86.Avx.mm256_min_pd(a.v, b.v) };
            double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
            double4 bv = UnsafeUtility.As<v256, double4>(ref b.v);
            double4 r = math.min(av, bv);
            return new doubleW { v = UnsafeUtility.As<double4, v256>(ref r) };
            
        }

        // Fixed min-fold companion to HMax (min is exact; order only matters for a consistent NaN
        // story — kept fixed anyway).
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static double HMin(doubleW a)
        {
            
            
            double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
            return math.min(math.min(av.x, av.y), math.min(av.z, av.w));
            
        }

        // Fixed fold — part of every consuming kernel's frozen numeric contract: opposite
        // halves pair first (lane l + lane l+W/2), then the balanced width-4 tree.
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static double HSum(doubleW a)
        {
            
            
            {
                double4 av = UnsafeUtility.As<v256, double4>(ref a.v);
                return (av.x + av.y) + (av.z + av.w);
            }
            
        }
    }
}
