// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/Sparse/Arena.Sparse.fProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using LinearAlgebra.Sparse;

namespace LinearAlgebra
{
    internal partial struct ArenaCore
    {
        // Pointer-stable allocation-record tables, same design as floatVecRecords/floatMatRecords
        // (see Arena/floatRecords.float.cs, Arena/Arena.float.cs) -- floatBSR/floatBlockJacobi
        // hold a stable floatBSRRecord*/floatBlockJacobiRecord* into one of these instead of being
        // tracked by a separate value copy. No temp-pool counterpart (BSR has no isTemp/floatTempBSR
        // analogue). floatBSRBuilders stays on the growable-list-of-value-copies model: a builder's
        // only mutable-relevant field is its heap-Malloc'd `State*` (see floatBSRBuilder.cs), which
        // is already pointer-stable and shared identically by every value-copy.
        internal ChunkedRecordTable<floatBSRRecord> floatBSRRecords;
        internal UnsafeList<floatBSRBuilder> floatBSRBuilders;
        internal ChunkedRecordTable<floatBlockJacobiRecord> floatBlockJacobiRecords;
    }

    // Core bump-allocator primitives for the block-sparse matrix type, mirroring how
    // floatVec/floatMat are declared directly on the Arena struct (see Arena.float.cs).
    // Lifecycle wiring (AllocationsCount / Clear / Dispose) lives in Arena.cs / ArenaCore.
    public unsafe partial struct Arena
    {
        /// <summary>
        /// Allocates a compressed block-sparse (BSR) matrix with the given block-grid shape
        /// and stored-block capacity (nnzb). Typically produced by floatBSRBuilder.ToBSR
        /// rather than called directly. Arena-owned: disposed with the arena.
        /// </summary>
        public floatBSR floatBSR(int blockRows, int blockCols, int BR, int BC, int nnzb, bool uninit = false, bool symmetric = false)
        {
            if (_core == null)
                throw new System.InvalidOperationException("Arena.floatBSR/floatBSRBuilder/floatBlockJacobi: arena is not initialized (default or disposed).");
#if ENABLE_UNITY_COLLECTIONS_CHECKS
            _core->EnterMutation();
            try
            {
#endif
                floatBSRRecord* rec = _core->floatBSRRecords.Allocate(out int slot);
                rec->Owner = _core;
                rec->Table = &_core->floatBSRRecords;
                rec->SelfIndex = slot;
                return new floatBSR(blockRows, blockCols, BR, BC, nnzb, rec, Allocator, uninit, symmetric);
#if ENABLE_UNITY_COLLECTIONS_CHECKS
            }
            finally { _core->ExitMutation(); }
#endif
        }

        /// <summary>
        /// Allocates a COO-of-blocks assembly builder for a blockRows x blockCols grid of
        /// BR x BC blocks. Accumulate triplets via AddBlock/AddValue, then call ToBSR(arena)
        /// once to compress into a floatBSR. Arena-owned: disposed with the arena.
        /// </summary>
        public floatBSRBuilder floatBSRBuilder(int blockRows, int blockCols, int BR, int BC, int capacityHint = 8)
        {
            if (_core == null)
                throw new System.InvalidOperationException("Arena.floatBSR/floatBSRBuilder/floatBlockJacobi: arena is not initialized (default or disposed).");
#if ENABLE_UNITY_COLLECTIONS_CHECKS
            _core->EnterMutation();
            try
            {
#endif
                var builder = new floatBSRBuilder(blockRows, blockCols, BR, BC, in this, capacityHint);
                _core->floatBSRBuilders.Add(in builder);
                return builder;
#if ENABLE_UNITY_COLLECTIONS_CHECKS
            }
            finally { _core->ExitMutation(); }
#endif
        }

        /// <summary>
        /// Builds a block-Jacobi preconditioner from A's diagonal blocks (A must be square:
        /// BlockRows==BlockCols, BR==BC). Arena-owned: disposed with the arena.
        /// </summary>
        public floatBlockJacobi floatBlockJacobi(in floatBSR A)
        {
            if (_core == null)
                throw new System.InvalidOperationException("Arena.floatBSR/floatBSRBuilder/floatBlockJacobi: arena is not initialized (default or disposed).");
#if ENABLE_UNITY_COLLECTIONS_CHECKS
            _core->EnterMutation();
            try
            {
#endif
                floatBlockJacobiRecord* rec = _core->floatBlockJacobiRecords.Allocate(out int slot);
                rec->Owner = _core;
                rec->Table = &_core->floatBlockJacobiRecords;
                rec->SelfIndex = slot;
                return new floatBlockJacobi(in A, rec, Allocator);
#if ENABLE_UNITY_COLLECTIONS_CHECKS
            }
            finally { _core->ExitMutation(); }
#endif
        }

        /// <summary>
        /// Non-throwing twin of <see cref="floatBlockJacobi(in floatBSR)"/>: info carries the
        /// build outcome (see the floatBlockJacobi out-info constructor). On failure the returned
        /// struct is unusable and no arena record is retained.
        /// </summary>
        public floatBlockJacobi floatBlockJacobi(in floatBSR A, out PreconditionerInfo info)
        {
            if (_core == null)
                throw new System.InvalidOperationException("Arena.floatBSR/floatBSRBuilder/floatBlockJacobi: arena is not initialized (default or disposed).");
#if ENABLE_UNITY_COLLECTIONS_CHECKS
            _core->EnterMutation();
            try
            {
#endif
                floatBlockJacobiRecord* rec = _core->floatBlockJacobiRecords.Allocate(out int slot);
                rec->Owner = _core;
                rec->Table = &_core->floatBlockJacobiRecords;
                rec->SelfIndex = slot;
                var M = new floatBlockJacobi(in A, rec, Allocator, out info);
                if (!info.Solved)
                    _core->floatBlockJacobiRecords.Free(slot);
                return M;
#if ENABLE_UNITY_COLLECTIONS_CHECKS
            }
            finally { _core->ExitMutation(); }
#endif
        }

        /// <summary>
        /// Materializes A^T as its own compressed BSR (O(nnz)): every stored block at (blockRow,
        /// blockCol) becomes a block at (blockCol, blockRow), transposed in place, then
        /// re-compressed via <see cref="floatBSRBuilder"/>. If A.Symmetric, returns A itself
        /// unchanged (transposing symmetric lower-block storage is a no-op).
        /// </summary>
        public unsafe floatBSR floatBSRTranspose(in floatBSR A)
        {
            if (A.Symmetric)
                return A;

            var builder = floatBSRBuilder(A.BlockCols, A.BlockRows, A.BC, A.BR, A.Nnzb);

            int blockLen = A.BR * A.BC;
            float* blockT = stackalloc float[blockLen];

            for (int bi = 0; bi < A.BlockRows; bi++)
            {
                int rowStart = A.RowPtr[bi];
                int rowEnd = A.RowPtr[bi + 1];

                for (int k = rowStart; k < rowEnd; k++)
                {
                    int bj = A.ColInd[k];
                    float* block = A.Values.Ptr + k * blockLen;

                    // Transpose the BR x BC block into blockT (BC x BR, row-major): blockT's
                    // row c, col r == block's row r, col c.
                    for (int r = 0; r < A.BR; r++)
                        for (int c = 0; c < A.BC; c++)
                            blockT[c * A.BR + r] = block[r * A.BC + c];

                    builder.AddBlock(bj, bi, blockT);
                }
            }

            Arena self = this;
            return builder.ToBSR(ref self);
        }

        /// <summary>
        /// One-time mirror of a SYMMETRIC-storage (lower-block-triangle-only) BSR into an
        /// equivalent FULL-storage BSR: every stored block K at (bi,bj) is kept at (bi,bj), and
        /// if bi != bj its transpose is ALSO materialized at (bj,bi) -- the implicit upper block
        /// <see cref="floatBSR.ToDense"/> already computes on the fly. O(nnzb*BR*BC), one-time
        /// copy. If A is already full storage (Symmetric == false), returns A unchanged -- no copy.
        /// </summary>
        public unsafe floatBSR floatBSRMirrorToFull(in floatBSR A)
        {
            if (!A.Symmetric)
                return A;

            var builder = floatBSRBuilder(A.BlockRows, A.BlockCols, A.BR, A.BC, A.Nnzb * 2);

            int blockLen = A.BR * A.BC;
            float* blockT = stackalloc float[blockLen];

            for (int bi = 0; bi < A.BlockRows; bi++)
            {
                int rowStart = A.RowPtr[bi];
                int rowEnd = A.RowPtr[bi + 1];

                for (int k = rowStart; k < rowEnd; k++)
                {
                    int bj = A.ColInd[k];
                    float* block = A.Values.Ptr + k * blockLen;

                    builder.AddBlock(bi, bj, block);

                    if (bi != bj)
                    {
                        for (int r = 0; r < A.BR; r++)
                            for (int c = 0; c < A.BC; c++)
                                blockT[c * A.BR + r] = block[r * A.BC + c];
                        builder.AddBlock(bj, bi, blockT);
                    }
                }
            }

            Arena self = this;
            return builder.ToBSR(ref self);
        }

        /// <summary>
        /// Builds a symmetric-SOR preconditioner from A (must be square: BlockRows==BlockCols,
        /// BR==BC), with the given relaxation parameter omega in (0, 2). Setup is A's own
        /// diagonal-block inverses (<see cref="floatBlockJacobi"/>, reused unchanged) plus a
        /// one-time mirror-to-full pass if A is Symmetric-storage
        /// (<see cref="floatBSRMirrorToFull"/>). Arena-owned: disposed with the arena.
        /// </summary>
        public floatSSOR floatSSOR(in floatBSR A, float omega)
        {
            Arena self = this;
            return new floatSSOR(in A, omega, ref self);
        }

        /// <summary>floatSSOR with omega=1 (symmetric Gauss-Seidel).</summary>
        public floatSSOR floatSSOR(in floatBSR A)
        {
            Arena self = this;
            return new floatSSOR(in A, ref self);
        }

        /// <summary>
        /// Builds a block incomplete-Cholesky IC(0) preconditioner from A (must be square SPD
        /// with every diagonal block stored; Symmetric-storage A is consumed zero-copy -- its
        /// stored lower-block pattern IS the IC(0) pattern). See <see cref="floatIC0"/> for the
        /// breakdown/diagonal-shift contract. Arena-owned: disposed with the arena.
        /// </summary>
        public floatIC0 floatIC0(in floatBSR A)
        {
            Arena self = this;
            return new floatIC0(in A, ref self);
        }

        /// <summary>Non-throwing twin of <see cref="floatIC0(in floatBSR)"/>: info carries the
        /// build outcome (Success, or NotPositiveDefinite on factorization breakdown).</summary>
        public floatIC0 floatIC0(in floatBSR A, out PreconditionerInfo info)
        {
            Arena self = this;
            return new floatIC0(in A, ref self, out info);
        }

        /// <summary>
        /// Builds a block incomplete-LU ILU(0) preconditioner from A (square, every diagonal
        /// block stored) — the nonsymmetric sibling of <see cref="floatIC0"/>, for
        /// Krylov.pbiCGStab. See <see cref="floatILU0"/> for the breakdown/shift contract.
        /// Arena-owned: disposed with the arena.
        /// </summary>
        public floatILU0 floatILU0(in floatBSR A)
        {
            Arena self = this;
            return new floatILU0(in A, ref self);
        }

        /// <summary>Non-throwing twin of <see cref="floatILU0(in floatBSR)"/>: info carries the
        /// build outcome (Success, or Singular on factorization breakdown).</summary>
        public floatILU0 floatILU0(in floatBSR A, out PreconditionerInfo info)
        {
            Arena self = this;
            return new floatILU0(in A, ref self, out info);
        }
    }
}
