// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/Sparse/fProxySSOR.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using LinearAlgebra;
using LinearAlgebra.Internal;
using Unity.Collections;

namespace LinearAlgebra.Sparse
{
    /// <summary>
    /// Symmetric-SOR preconditioner over a square BSR (BlockRows==BlockCols, BR==BC):
    /// z = M⁻¹ r with M = [ω/(2−ω)] · (D/ω+L) · D⁻¹ · (D/ω+Lᵀ), the standard SSOR preconditioner
    /// (Young; Saad, "Iterative Methods for Sparse Linear Systems" 2nd ed., ch. 10.2; Eisenstat
    /// 1981) -- L is A's strictly-lower stored blocks, D its block diagonal, ω the relaxation
    /// parameter (0, 2), default 1 (plain symmetric Gauss-Seidel). SPD whenever A is SPD and
    /// 0&lt;ω&lt;2 (standard result).
    ///
    /// Solving M z = r factors into
    ///   v = (D/ω+L)⁻¹ r            (forward sweep, <see cref="BSR.sweepLower"/>, diagScale=ω)
    ///   u = [(2−ω)/ω] · D · v      (diagonal scale -- needs RAW D, not D⁻¹: M's own middle
    ///                                factor is D⁻¹, so M⁻¹'s middle factor is D itself)
    ///   z = (D/ω+Lᵀ)⁻¹ u           (backward sweep, <see cref="BSR.sweepUpper"/>, diagScale=ω)
    /// Setup reuses block-Jacobi's setup (<see cref="Jacobi"/>, unchanged) for the D⁻¹ half used by
    /// both sweeps' diagonal solve; the raw-D half needed only by the middle step is a cheap
    /// O(nnzb_diag·BR²) extraction done once here and pre-scaled by [(2−ω)/ω] into
    /// <see cref="ScaledD"/> so Apply pays for it once, not every iteration.
    ///
    /// FULL-storage BSR only: a Symmetric-storage A pays a one-time mirror-to-full copy at
    /// construction (<see cref="Arena.doubleBSRMirrorToFull"/> / <see cref="doubleBSR.MirrorToFull"/>)
    /// -- the sweeps need row-ordered access to BOTH triangles, which lower-only storage cannot give
    /// without a column-order scatter. No record table of its own: built via a ref Arena ctor, every
    /// piece (A, Jacobi, ScaledD, Scratch1/2) is arena-tracked and the arena owns disposal -- do not
    /// call Dispose() on that instance. Built via the Allocator ctor, this instance owns those same
    /// pieces standalone and Dispose() must be called when done (see Dispose()'s own doc for the A
    /// aliasing caveat).
    /// </summary>
    public readonly struct doubleSSOR : IdoublePreconditioner, IDisposable
    {
        public readonly doubleBSR A;               // full-storage (mirrored once if the input was symmetric-storage)
        public readonly doubleBlockJacobi Jacobi;   // A's diagonal block INVERSES -- block-Jacobi's own setup, reused unchanged
        public readonly doubleN ScaledD;            // A's diagonal blocks themselves, pre-scaled by (2-omega)/omega at construction
        public readonly double Omega;
        public readonly doubleN Scratch1;           // length Rows; Apply's forward-sweep result v
        public readonly doubleN Scratch2;           // length Rows; Apply's diagonal-scaled result u

        // True when A was freshly mirrored to full storage by the Allocator ctor (owned, must be
        // disposed); false when A aliases the caller's input matrix -- either the arena path (never
        // disposed at all) or an already-full-storage input on the Allocator path. Consulted only
        // by Dispose().
        private readonly bool _ownsA;

        public int Rows => A.M_Rows;

        /// <summary>
        /// Builds the preconditioner from A's diagonal blocks and (if A is Symmetric-storage) a
        /// one-time mirror to full storage. Throws if A is not square, or omega is not in (0, 2).
        /// </summary>
        public doubleSSOR(in doubleBSR a, double omega, ref Arena arena)
        {
            if (a.BlockRows != a.BlockCols || a.BR != a.BC)
                throw new ArgumentException("doubleSSOR: A must be square (BlockRows==BlockCols, BR==BC)");
            if (!(omega > (double)0 && omega < (double)2))
                throw new ArgumentException("doubleSSOR: omega must be in (0, 2) for M to be SPD");

            _ownsA = false; // arena-tracked path: Dispose() is never called on this path, value unused
            A = arena.doubleBSRMirrorToFull(in a);
            Jacobi = arena.doubleBlockJacobi(in A);
            Omega = omega;

            int blockLen = A.BR * A.BR;
            var scaledD = arena.doubleVec(A.BlockRows * blockLen);
            double c = ((double)2 - omega) / omega;

            for (int i = 0; i < A.BlockRows; i++)
            {
                // Blocks within a block-row are stored in ascending ColInd (BSR invariant) --
                // scan forward and stop as soon as we pass column i. Same scan doubleBlockJacobi's
                // own constructor uses to find the diagonal block; NOT an inversion (just a copy),
                // so this does not duplicate doubleBlockJacobi's LU-inversion code.
                int s = A.RowPtr[i], e = A.RowPtr[i + 1];
                int found = -1;
                for (int k = s; k < e; k++)
                {
                    int col = A.ColInd[k];
                    if (col == i) { found = k; break; }
                    if (col > i) break;
                }
                if (found < 0)
                    throw new ArgumentException("doubleSSOR: missing diagonal block in A");

                int srcOff = found * blockLen, dstOff = i * blockLen;
                for (int t = 0; t < blockLen; t++)
                    scaledD[dstOff + t] = A.Values[srcOff + t] * c;
            }
            ScaledD = scaledD;

            Scratch1 = arena.doubleVec(A.M_Rows);
            Scratch2 = arena.doubleVec(A.M_Rows);
        }

        /// <summary>doubleSSOR with omega=1 (symmetric Gauss-Seidel).</summary>
        public doubleSSOR(in doubleBSR a, ref Arena arena) : this(in a, (double)1, ref arena) { }

        /// <summary>
        /// Standalone twin of <see cref="doubleSSOR(in doubleBSR, double, ref Arena)"/>: allocates
        /// every owned buffer from <paramref name="allocator"/> instead of an arena. Dispose the
        /// result with <see cref="Dispose"/> when done -- only call Dispose on an instance built via
        /// this ctor, never on one built via the ref Arena ctor (that instance is arena-owned).
        /// </summary>
        public unsafe doubleSSOR(in doubleBSR a, double omega, Allocator allocator)
        {
            if (a.BlockRows != a.BlockCols || a.BR != a.BC)
                throw new ArgumentException("doubleSSOR: A must be square (BlockRows==BlockCols, BR==BC)");
            if (!(omega > (double)0 && omega < (double)2))
                throw new ArgumentException("doubleSSOR: omega must be in (0, 2) for M to be SPD");

            _ownsA = a.Symmetric;
            A = a.MirrorToFull(allocator);
            // try/finally with a success flag, NOT try/catch -- Burst rejects `catch` (BC1006).
            // On the managed path this still disposes the fresh mirror if Jacobi construction
            // throws (no caller handle exists yet); under Burst the guard degrades to a no-op on
            // the throw path, same as Arena's ctor guard.
            bool ok = false;
            try
            {
                Jacobi = new doubleBlockJacobi(in A, allocator);
                ok = true;
            }
            finally
            {
                if (!ok && _ownsA) A.Dispose();
            }
            Omega = omega;

            int blockLen = A.BR * A.BR;
            var scaledD = new doubleN(A.BlockRows * blockLen, allocator);
            double c = ((double)2 - omega) / omega;

            for (int i = 0; i < A.BlockRows; i++)
            {
                int s = A.RowPtr[i], e = A.RowPtr[i + 1];
                int found = -1;
                for (int k = s; k < e; k++)
                {
                    int col = A.ColInd[k];
                    if (col == i) { found = k; break; }
                    if (col > i) break;
                }
                if (found < 0)
                    throw new ArgumentException("doubleSSOR: missing diagonal block in A");

                int srcOff = found * blockLen, dstOff = i * blockLen;
                for (int t = 0; t < blockLen; t++)
                    scaledD[dstOff + t] = A.Values[srcOff + t] * c;
            }
            ScaledD = scaledD;

            Scratch1 = new doubleN(A.M_Rows, allocator);
            Scratch2 = new doubleN(A.M_Rows, allocator);
        }

        /// <summary>doubleSSOR with omega=1 (symmetric Gauss-Seidel), allocated from <paramref name="allocator"/>.</summary>
        public unsafe doubleSSOR(in doubleBSR a, Allocator allocator) : this(in a, (double)1, allocator) { }

        /// <summary>
        /// Disposes every buffer this instance owns: A only if it was freshly mirrored to full
        /// storage (not when it aliases the input matrix), plus Jacobi/ScaledD/Scratch1/Scratch2.
        /// Only call on an instance built via the Allocator ctor -- an instance built via the ref
        /// Arena ctor is arena-owned and must not be disposed directly.
        /// </summary>
        public unsafe void Dispose()
        {
            if (_ownsA) A.Dispose();
            Jacobi.Dispose();
            ScaledD.Dispose();
            Scratch1.Dispose();
            Scratch2.Dispose();
        }

        /// <summary>z = M⁻¹ r -- see the type doc comment for the three-step derivation. z must not alias r.</summary>
        public bool IsIdentity => false;
        public bool IsSpd => true;
        public bool IsConstant => true;

        public unsafe void Apply(in doubleN r, ref doubleN z)
        {
            int n = Rows;

            if (r.N != n)
                throw new ArgumentException("doubleSSOR.Apply: r.N must equal Rows");
            if (z.N != n)
                throw new ArgumentException("doubleSSOR.Apply: z.N must equal Rows");

            if (z.Data.Ptr == r.Data.Ptr)
                throw new ArgumentException("doubleSSOR.Apply: z must not alias r");

            var v = Scratch1;
            BSR.sweepLower(in A, in Jacobi, Omega, in r, ref v);   // v = (D/omega+L)^-1 r

            var u = Scratch2;
            ApplyScaledDiag(in v, ref u);                          // u = [(2-omega)/omega] * D * v

            BSR.sweepUpper(in A, in Jacobi, Omega, in u, ref z);   // z = (D/omega+L^T)^-1 u
        }

        // b x b block matvec using ScaledD (mirrors doubleBlockJacobi.Apply's own unroll
        // dispatch, reusing the SAME UnsafeOP.blockJacobiApplyB{b} kernels -- they operate on
        // "any b x b array of the right shape", not specifically DInv, so ScaledD substitutes in
        // directly with no new kernel needed). vIn/vOut here are always Scratch1/Scratch2 (Apply's
        // own distinct buffers), never aliased.
        private unsafe void ApplyScaledDiag(in doubleN vIn, ref doubleN vOut)
        {
            double* dp = ScaledD.Data.Ptr;
            double* ip = vIn.Data.Ptr;
            double* op = vOut.Data.Ptr;
            int blockRows = A.BlockRows;

            switch (A.BR)
            {
                case 1: UnsafeOP.blockJacobiApplyB1(dp, ip, op, blockRows); return;
                case 2: UnsafeOP.blockJacobiApplyB2(dp, ip, op, blockRows); return;
                case 3: UnsafeOP.blockJacobiApplyB3(dp, ip, op, blockRows); return;
                case 4: UnsafeOP.blockJacobiApplyB4(dp, ip, op, blockRows); return;
                case 6: UnsafeOP.blockJacobiApplyB6(dp, ip, op, blockRows); return;
            }

            int BR = A.BR, blockLen = BR * BR;
            for (int i = 0; i < blockRows; i++)
            {
                int rowBase = i * BR, blockOff = i * blockLen;
                for (int lr = 0; lr < BR; lr++)
                {
                    double sum = 0;
                    for (int lc = 0; lc < BR; lc++)
                        sum += dp[blockOff + lr * BR + lc] * ip[rowBase + lc];
                    op[rowBase + lr] = sum;
                }
            }
        }
    }
}
