// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/Sparse/fProxySchwarz.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using LinearAlgebra;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Mathematics;

namespace LinearAlgebra.Sparse
{
    /// <summary>
    /// Shared setup for the one-level Schwarz preconditioners: contiguous block-row partitioning,
    /// delta-layer overlap over the symmetrized block-adjacency graph, and dense local-matrix
    /// gather. Both <see cref="floatAdditiveSchwarz"/> and <see cref="floatRestrictedSchwarz"/>
    /// build their topology through here; they differ only in local factor kind and scatter.
    /// </summary>
    internal static class floatSchwarzShared
    {
        /// <summary>
        /// Builds the subdomain topology into fresh arena buffers. Partitions block-rows
        /// 0..BlockRows-1 into K contiguous ranges of blocksPerSub = max(1, subdomainSize/BR) blocks,
        /// then extends each by opts.overlap adjacency layers. Returns the effective full-storage A
        /// to gather values from (a transient arena mirror for Symmetric-storage input, else A
        /// itself). Throws if A is not square (BlockRows==BlockCols, BR==BC).
        /// </summary>
        internal static floatBSR BuildTopology(in floatBSR a, ref Arena arena, in SchwarzOptions opts,
            out Indices subStart, out Indices subBlocks, out Indices ownedLo, out Indices ownedHi,
            out int K, out int maxBlocks)
        {
            if (a.BlockRows != a.BlockCols || a.BR != a.BC)
                throw new ArgumentException("floatSchwarz: A must be square (BlockRows==BlockCols, BR==BC)");

            floatBSR A = a.Symmetric ? arena.floatBSRMirrorToFull(in a) : a;

            int nb = A.BlockRows;
            int BR = A.BR;

            int blocksPerSub = math.max(1, opts.subdomainSize / BR);
            K = (nb + blocksPerSub - 1) / blocksPerSub;
            int delta = math.max(0, opts.overlap);

            ownedLo = arena.Indices(K);
            ownedHi = arena.Indices(K);
            subStart = arena.Indices(K + 1);
            for (int i = 0; i < K; i++)
            {
                int lo = i * blocksPerSub;
                int hi = math.min((i + 1) * blocksPerSub, nb);
                ownedLo[i] = lo;
                ownedHi[i] = hi;
            }

            // Transient symmetrized adjacency: A's own block pattern (out-neighbors) plus its
            // transpose (in-neighbors). Duplicate edges are harmless -- the BFS mark dedups.
            var tPtr = new NativeArray<int>(nb + 1, Allocator.Temp, NativeArrayOptions.ClearMemory);
            int nnzb = A.Nnzb;
            var tIdx = new NativeArray<int>(nnzb, Allocator.Temp, NativeArrayOptions.UninitializedMemory);
            {
                var aRowPtr = A.RowPtr; var aColInd = A.ColInd;
                for (int k = 0; k < nnzb; k++) tPtr[aColInd[k] + 1]++;
                for (int c = 0; c < nb; c++) tPtr[c + 1] += tPtr[c];
                var fill = new NativeArray<int>(nb, Allocator.Temp, NativeArrayOptions.ClearMemory);
                for (int r = 0; r < nb; r++)
                {
                    int s = aRowPtr[r], e = aRowPtr[r + 1];
                    for (int k = s; k < e; k++)
                    {
                        int c = aColInd[k];
                        tIdx[tPtr[c] + fill[c]] = r;
                        fill[c]++;
                    }
                }
                fill.Dispose();
            }

            // Multi-source BFS per subdomain, bounded to delta layers. mark[g]==stamp marks members;
            // dist[g] the layer (trusted only when mark[g]==stamp).
            var mark = new NativeArray<int>(nb, Allocator.Temp, NativeArrayOptions.ClearMemory);
            var dist = new NativeArray<int>(nb, Allocator.Temp, NativeArrayOptions.UninitializedMemory);
            var queue = new UnsafeList<int>(math.max(1, blocksPerSub), Allocator.Temp);
            var allMembers = new UnsafeList<int>(math.max(1, nb), Allocator.Temp);

            var aRp = A.RowPtr; var aCi = A.ColInd;
            maxBlocks = 0;
            subStart[0] = 0;
            for (int i = 0; i < K; i++)
            {
                int stamp = i + 1;
                queue.Clear();
                int lo = ownedLo[i], hi = ownedHi[i];
                for (int g = lo; g < hi; g++)
                {
                    mark[g] = stamp;
                    dist[g] = 0;
                    queue.Add(g);
                }

                int head = 0;
                while (head < queue.Length)
                {
                    int r = queue[head++];
                    int d = dist[r];
                    if (d >= delta) continue;

                    int s = aRp[r], e = aRp[r + 1];
                    for (int k = s; k < e; k++)
                    {
                        int j = aCi[k];
                        if (mark[j] != stamp) { mark[j] = stamp; dist[j] = d + 1; queue.Add(j); }
                    }
                    int ts = tPtr[r], te = tPtr[r + 1];
                    for (int k = ts; k < te; k++)
                    {
                        int j = tIdx[k];
                        if (mark[j] != stamp) { mark[j] = stamp; dist[j] = d + 1; queue.Add(j); }
                    }
                }

                // Collect members ascending (canonical local order) by scanning the whole index space.
                int count = 0;
                for (int g = 0; g < nb; g++)
                    if (mark[g] == stamp) { allMembers.Add(g); count++; }

                subStart[i + 1] = subStart[i] + count;
                if (count > maxBlocks) maxBlocks = count;
            }

            subBlocks = arena.Indices(allMembers.Length);
            for (int t = 0; t < allMembers.Length; t++) subBlocks[t] = allMembers[t];

            allMembers.Dispose();
            queue.Dispose();
            dist.Dispose();
            mark.Dispose();
            tIdx.Dispose();
            tPtr.Dispose();

            return A;
        }

        /// <summary>
        /// Standalone twin of <see cref="BuildTopology(in floatBSR, ref Arena, in SchwarzOptions, out Indices, out Indices, out Indices, out Indices, out int, out int)"/>:
        /// allocates SubStart/SubBlocks/OwnedLo/OwnedHi from <paramref name="allocator"/> instead of
        /// an arena; a Symmetric-storage input's mirror-to-full copy is Temp-allocated. Because the
        /// mirror (when made) is still used by the caller after this returns (to gather subdomain
        /// values), disposal is the CALLER's responsibility: <paramref name="ownsA"/> reports whether
        /// the returned matrix must be disposed once the caller is done reading it (true = freshly
        /// mirrored, false = aliases the caller's own input matrix `a`).
        /// </summary>
        internal static floatBSR BuildTopology(in floatBSR a, Allocator allocator, in SchwarzOptions opts,
            out Indices subStart, out Indices subBlocks, out Indices ownedLo, out Indices ownedHi,
            out int K, out int maxBlocks, out bool ownsA)
        {
            if (a.BlockRows != a.BlockCols || a.BR != a.BC)
                throw new ArgumentException("floatSchwarz: A must be square (BlockRows==BlockCols, BR==BC)");

            ownsA = a.Symmetric;
            floatBSR A = ownsA ? a.MirrorToFull(Allocator.Temp) : a;

            int nb = A.BlockRows;
            int BR = A.BR;

            int blocksPerSub = math.max(1, opts.subdomainSize / BR);
            K = (nb + blocksPerSub - 1) / blocksPerSub;
            int delta = math.max(0, opts.overlap);

            ownedLo = new Indices(K, allocator);
            ownedHi = new Indices(K, allocator);
            subStart = new Indices(K + 1, allocator);
            for (int i = 0; i < K; i++)
            {
                int lo = i * blocksPerSub;
                int hi = math.min((i + 1) * blocksPerSub, nb);
                ownedLo[i] = lo;
                ownedHi[i] = hi;
            }

            var tPtr = new NativeArray<int>(nb + 1, Allocator.Temp, NativeArrayOptions.ClearMemory);
            int nnzb = A.Nnzb;
            var tIdx = new NativeArray<int>(nnzb, Allocator.Temp, NativeArrayOptions.UninitializedMemory);
            {
                var aRowPtr = A.RowPtr; var aColInd = A.ColInd;
                for (int k = 0; k < nnzb; k++) tPtr[aColInd[k] + 1]++;
                for (int c = 0; c < nb; c++) tPtr[c + 1] += tPtr[c];
                var fill = new NativeArray<int>(nb, Allocator.Temp, NativeArrayOptions.ClearMemory);
                for (int r = 0; r < nb; r++)
                {
                    int s = aRowPtr[r], e = aRowPtr[r + 1];
                    for (int k = s; k < e; k++)
                    {
                        int c = aColInd[k];
                        tIdx[tPtr[c] + fill[c]] = r;
                        fill[c]++;
                    }
                }
                fill.Dispose();
            }

            var mark = new NativeArray<int>(nb, Allocator.Temp, NativeArrayOptions.ClearMemory);
            var dist = new NativeArray<int>(nb, Allocator.Temp, NativeArrayOptions.UninitializedMemory);
            var queue = new UnsafeList<int>(math.max(1, blocksPerSub), Allocator.Temp);
            var allMembers = new UnsafeList<int>(math.max(1, nb), Allocator.Temp);

            var aRp = A.RowPtr; var aCi = A.ColInd;
            maxBlocks = 0;
            subStart[0] = 0;
            for (int i = 0; i < K; i++)
            {
                int stamp = i + 1;
                queue.Clear();
                int lo = ownedLo[i], hi = ownedHi[i];
                for (int g = lo; g < hi; g++)
                {
                    mark[g] = stamp;
                    dist[g] = 0;
                    queue.Add(g);
                }

                int head = 0;
                while (head < queue.Length)
                {
                    int r = queue[head++];
                    int d = dist[r];
                    if (d >= delta) continue;

                    int s = aRp[r], e = aRp[r + 1];
                    for (int k = s; k < e; k++)
                    {
                        int j = aCi[k];
                        if (mark[j] != stamp) { mark[j] = stamp; dist[j] = d + 1; queue.Add(j); }
                    }
                    int ts = tPtr[r], te = tPtr[r + 1];
                    for (int k = ts; k < te; k++)
                    {
                        int j = tIdx[k];
                        if (mark[j] != stamp) { mark[j] = stamp; dist[j] = d + 1; queue.Add(j); }
                    }
                }

                int count = 0;
                for (int g = 0; g < nb; g++)
                    if (mark[g] == stamp) { allMembers.Add(g); count++; }

                subStart[i + 1] = subStart[i] + count;
                if (count > maxBlocks) maxBlocks = count;
            }

            subBlocks = new Indices(allMembers.Length, allocator);
            for (int t = 0; t < allMembers.Length; t++) subBlocks[t] = allMembers[t];

            allMembers.Dispose();
            queue.Dispose();
            dist.Dispose();
            mark.Dispose();
            tIdx.Dispose();
            tPtr.Dispose();

            return A;
        }

        /// <summary>Gathers A's (gr,gc) BR x BR block into the dense local matrix M at
        /// (rowOff,colOff), zero-filled when the block is not stored; adds diagShift to the block's
        /// own scalar diagonal when gr==gc. A must be full storage (ascending ColInd per row).</summary>
        internal static void GatherBlock(in floatBSR A, int gr, int gc, ref floatMxN M, int rowOff, int colOff, float diagShift, int BR)
        {
            int s = A.RowPtr[gr], e = A.RowPtr[gr + 1];
            int idx = -1;
            for (int k = s; k < e; k++)
            {
                int col = A.ColInd[k];
                if (col == gc) { idx = k; break; }
                if (col > gc) break;
            }

            if (idx < 0)
            {
                for (int r = 0; r < BR; r++)
                    for (int c = 0; c < BR; c++)
                        M[rowOff + r, colOff + c] = (float)0;
            }
            else
            {
                int off = idx * BR * BR;
                var v = A.Values;
                for (int r = 0; r < BR; r++)
                    for (int c = 0; c < BR; c++)
                        M[rowOff + r, colOff + c] = v[off + r * BR + c];
            }

            if (gr == gc && diagShift != (float)0)
                for (int r = 0; r < BR; r++)
                    M[rowOff + r, colOff + r] += diagShift;
        }

        /// <summary>Largest |scalar diagonal entry| across A's stored diagonal blocks (shift scale);
        /// 1 if none is positive.</summary>
        internal static float DiagMax(in floatBSR A)
        {
            int nb = A.BlockRows, BR = A.BR, blockLen = BR * BR;
            float diagMax = 0;
            for (int i = 0; i < nb; i++)
            {
                int s = A.RowPtr[i], e = A.RowPtr[i + 1];
                for (int k = s; k < e; k++)
                {
                    if (A.ColInd[k] != i) continue;
                    int off = k * blockLen;
                    for (int r = 0; r < BR; r++)
                    {
                        float av = math.abs(A.Values[off + r * BR + r]);
                        if (av > diagMax) diagMax = av;
                    }
                    break;
                }
            }
            if (diagMax <= (float)0) diagMax = (float)1;
            return diagMax;
        }
    }

    /// <summary>
    /// One-level SYMMETRIC additive Schwarz preconditioner over a square SPD BSR:
    /// M^-1 = sum_i R_i^T A_i^-1 R_i, where R_i restricts onto overlapped subdomain i and
    /// A_i = R_i A R_i^T is factored densely (Cholesky) once at build and reused by every Apply.
    /// The overlapped scatter (R_i^T sums each dof over every subdomain that owns it) makes M
    /// symmetric; whenever the build reports Success, M is SPD by construction -- valid for
    /// <see cref="LinearAlgebra.Krylov"/>.cg AND minres.
    ///
    /// Subdomains are contiguous block-row ranges of size opts.subdomainSize (in scalar unknowns,
    /// rounded to whole blocks) extended by opts.overlap adjacency layers. A local Cholesky that
    /// breaks down retries with the IC0-style escalating diagonal shift on just that subdomain
    /// (1e-3*diagMax, x10, up to 6 attempts); the worst shift used is in <see cref="Shift"/>.
    /// Cached-factor memory is O(N * overlapFactor^2 * subdomainSize) -- see
    /// <see cref="SchwarzOptions"/>. Symmetric-storage A is mirrored to full transiently at setup
    /// (A is read only at setup, never at Apply). Built via a ref Arena ctor, every owned buffer is
    /// arena-tracked and the arena owns disposal -- do not call Dispose() on that instance. Built
    /// via an Allocator ctor, this instance owns those buffers standalone and Dispose() must be
    /// called when done. A single instance is not safe for concurrent Apply (the local scratch is
    /// shared).
    /// </summary>
    public readonly struct floatAdditiveSchwarz : IfloatPreconditioner, IDisposable
    {
        /// <summary>Prefix offsets into <see cref="SubBlocks"/> (CSR-of-subdomains), length K+1.</summary>
        public readonly Indices SubStart;
        /// <summary>Each subdomain's overlapped block ids, ascending; concatenated per SubStart.</summary>
        public readonly Indices SubBlocks;
        /// <summary>Owned (non-overlapped) block range [lo,hi) per subdomain, length K each.</summary>
        public readonly Indices OwnedLo;
        public readonly Indices OwnedHi;
        /// <summary>Prefix offsets into <see cref="Factors"/> (entries = sum n_i^2), length K+1.</summary>
        public readonly Indices FactorStart;
        /// <summary>Cached dense lower Cholesky factors L_i, row-major n_i x n_i per subdomain.</summary>
        public readonly floatN Factors;
        /// <summary>Apply-time local vector, length <see cref="MaxLocalN"/> (contents mutate; no
        /// struct field does -- survives an IJob struct-copy).</summary>
        public readonly floatN Scratch;
        /// <summary>Worst per-subdomain diagonal shift that made a local factor succeed; 0 if clean.</summary>
        public readonly float Shift;

        public readonly int BlockRows;
        public readonly int BR;
        public readonly int K;
        public readonly int MaxLocalN;

        public int Rows => BlockRows * BR;

        /// <summary>Builds AS with <see cref="SchwarzOptions.Default"/>. Throws if A is not square or
        /// if a local factor breaks down at every diagonal shift; use the out-info overload for a
        /// non-throwing build.</summary>
        public floatAdditiveSchwarz(in floatBSR a, ref Arena arena)
        {
            this = new floatAdditiveSchwarz(in a, ref arena, out PreconditionerInfo info);
            if (!info.Solved)
                throw new ArgumentException("floatAdditiveSchwarz: a local factor broke down at every diagonal shift — is A symmetric positive definite?");
        }

        /// <summary>Non-throwing build with <see cref="SchwarzOptions.Default"/>.</summary>
        public floatAdditiveSchwarz(in floatBSR a, ref Arena arena, out PreconditionerInfo info)
        {
            this = new floatAdditiveSchwarz(in a, ref arena, SchwarzOptions.Default, out info);
        }

        /// <summary>Builds AS with the given options. Same throw contract as the options-less
        /// overload.</summary>
        public floatAdditiveSchwarz(in floatBSR a, ref Arena arena, in SchwarzOptions opts)
        {
            this = new floatAdditiveSchwarz(in a, ref arena, in opts, out PreconditionerInfo info);
            if (!info.Solved)
                throw new ArgumentException("floatAdditiveSchwarz: a local factor broke down at every diagonal shift — is A symmetric positive definite?");
        }

        /// <summary>
        /// Non-throwing build: info.status is Success, or NotPositiveDefinite when some subdomain's
        /// local Cholesky broke down at every diagonal shift (the preconditioner is then unusable --
        /// do not Apply); info also carries the worst rescuing shift and the worst attempts across
        /// subdomains. A non-square A still throws.
        /// </summary>
        public floatAdditiveSchwarz(in floatBSR a, ref Arena arena, in SchwarzOptions opts, out PreconditionerInfo info)
        {
            // Everything computed into locals; all readonly fields assigned once at the end (avoids
            // reading a not-yet-fully-assigned `this` in the struct ctor).
            floatBSR A = floatSchwarzShared.BuildTopology(in a, ref arena, in opts,
                out Indices subStart, out Indices subBlocks, out Indices ownedLo, out Indices ownedHi,
                out int k, out int maxBlocks);

            int br = A.BR;
            int maxLocalN = maxBlocks * br;

            var factorStart = arena.Indices(k + 1);
            factorStart[0] = 0;
            for (int i = 0; i < k; i++)
            {
                int nn = (subStart[i + 1] - subStart[i]) * br;
                factorStart[i + 1] = factorStart[i] + nn * nn;
            }
            var factors = arena.floatVec(factorStart[k]);
            var scratch = arena.floatVec(math.max(1, maxLocalN), true);

            float diagMax = floatSchwarzShared.DiagMax(in A);

            float worstShift = 0;
            int worstAttempts = 1;
            bool ok = true;

            for (int i = 0; i < k; i++)
            {
                int start = subStart[i];
                int count = subStart[i + 1] - start;
                int n = count * br;
                int fbase = factorStart[i];

                var M = new floatMxN(n, n, Allocator.Temp, true);
                float shift = 0;
                bool subOk = false;
                int subAttempts = 0;

                for (int attempt = 0; attempt < 6; attempt++)
                {
                    subAttempts = attempt + 1;
                    for (int aI = 0; aI < count; aI++)
                    {
                        int gr = subBlocks[start + aI];
                        for (int bI = 0; bI <= aI; bI++)
                        {
                            int gc = subBlocks[start + bI];
                            floatSchwarzShared.GatherBlock(in A, gr, gc, ref M, aI * br, bI * br, aI == bI ? shift : (float)0, br);
                        }
                    }

                    var chInfo = CHO.decompInPlace(ref M);
                    if (chInfo.Solved)
                    {
                        var md = M.Data;
                        for (int t = 0; t < n * n; t++) factors[fbase + t] = md[t];
                        subOk = true;
                        break;
                    }
                    shift = shift == (float)0 ? (float)1e-3 * diagMax : shift * (float)10;
                }

                M.Dispose();

                if (subAttempts > worstAttempts) worstAttempts = subAttempts;
                if (shift > worstShift) worstShift = shift;
                if (!subOk) { ok = false; break; }
            }

            SubStart = subStart;
            SubBlocks = subBlocks;
            OwnedLo = ownedLo;
            OwnedHi = ownedHi;
            FactorStart = factorStart;
            Factors = factors;
            Scratch = scratch;
            Shift = worstShift;
            BlockRows = A.BlockRows;
            BR = br;
            K = k;
            MaxLocalN = maxLocalN;

            info = new PreconditionerInfo
            {
                status = ok ? DirectSolveStatus.Success : DirectSolveStatus.NotPositiveDefinite,
                shift = (double)worstShift,
                attempts = worstAttempts,
            };
        }

        /// <summary>Standalone twin of <see cref="floatAdditiveSchwarz(in floatBSR, ref Arena)"/>,
        /// allocated from <paramref name="allocator"/>. Dispose the result with
        /// <see cref="Dispose"/> -- only call Dispose on an instance built via an Allocator ctor.</summary>
        public unsafe floatAdditiveSchwarz(in floatBSR a, Allocator allocator)
        {
            this = new floatAdditiveSchwarz(in a, allocator, out PreconditionerInfo info);
            if (!info.Solved)
            {
                Dispose();
                throw new ArgumentException("floatAdditiveSchwarz: a local factor broke down at every diagonal shift — is A symmetric positive definite?");
            }
        }

        /// <summary>Standalone twin of <see cref="floatAdditiveSchwarz(in floatBSR, ref Arena, out PreconditionerInfo)"/>.</summary>
        public unsafe floatAdditiveSchwarz(in floatBSR a, Allocator allocator, out PreconditionerInfo info)
        {
            this = new floatAdditiveSchwarz(in a, allocator, SchwarzOptions.Default, out info);
        }

        /// <summary>Standalone twin of <see cref="floatAdditiveSchwarz(in floatBSR, ref Arena, in SchwarzOptions)"/>.</summary>
        public unsafe floatAdditiveSchwarz(in floatBSR a, Allocator allocator, in SchwarzOptions opts)
        {
            this = new floatAdditiveSchwarz(in a, allocator, in opts, out PreconditionerInfo info);
            if (!info.Solved)
            {
                Dispose();
                throw new ArgumentException("floatAdditiveSchwarz: a local factor broke down at every diagonal shift — is A symmetric positive definite?");
            }
        }

        /// <summary>
        /// Standalone twin of <see cref="floatAdditiveSchwarz(in floatBSR, ref Arena, in SchwarzOptions, out PreconditionerInfo)"/>:
        /// allocates every owned buffer from <paramref name="allocator"/> instead of an arena. Same
        /// throw contract (buffers are allocated and left populated with the failed factorization
        /// even on breakdown -- Dispose is still valid). Only call Dispose on an instance built via
        /// an Allocator ctor, never on one built via a ref Arena ctor (that instance is arena-owned).
        /// </summary>
        public unsafe floatAdditiveSchwarz(in floatBSR a, Allocator allocator, in SchwarzOptions opts, out PreconditionerInfo info)
        {
            floatBSR A = floatSchwarzShared.BuildTopology(in a, allocator, in opts,
                out Indices subStart, out Indices subBlocks, out Indices ownedLo, out Indices ownedHi,
                out int k, out int maxBlocks, out bool ownsA);

            int br = A.BR;
            int maxLocalN = maxBlocks * br;

            var factorStart = new Indices(k + 1, allocator);
            factorStart[0] = 0;
            for (int i = 0; i < k; i++)
            {
                int nn = (subStart[i + 1] - subStart[i]) * br;
                factorStart[i + 1] = factorStart[i] + nn * nn;
            }
            var factors = new floatN(factorStart[k], allocator);
            var scratch = new floatN(math.max(1, maxLocalN), allocator, true);

            float diagMax = floatSchwarzShared.DiagMax(in A);

            float worstShift = 0;
            int worstAttempts = 1;
            bool ok = true;

            for (int i = 0; i < k; i++)
            {
                int start = subStart[i];
                int count = subStart[i + 1] - start;
                int n = count * br;
                int fbase = factorStart[i];

                var M = new floatMxN(n, n, Allocator.Temp, true);
                float shift = 0;
                bool subOk = false;
                int subAttempts = 0;

                for (int attempt = 0; attempt < 6; attempt++)
                {
                    subAttempts = attempt + 1;
                    for (int aI = 0; aI < count; aI++)
                    {
                        int gr = subBlocks[start + aI];
                        for (int bI = 0; bI <= aI; bI++)
                        {
                            int gc = subBlocks[start + bI];
                            floatSchwarzShared.GatherBlock(in A, gr, gc, ref M, aI * br, bI * br, aI == bI ? shift : (float)0, br);
                        }
                    }

                    var chInfo = CHO.decompInPlace(ref M);
                    if (chInfo.Solved)
                    {
                        var md = M.Data;
                        for (int t = 0; t < n * n; t++) factors[fbase + t] = md[t];
                        subOk = true;
                        break;
                    }
                    shift = shift == (float)0 ? (float)1e-3 * diagMax : shift * (float)10;
                }

                M.Dispose();

                if (subAttempts > worstAttempts) worstAttempts = subAttempts;
                if (shift > worstShift) worstShift = shift;
                if (!subOk) { ok = false; break; }
            }

            SubStart = subStart;
            SubBlocks = subBlocks;
            OwnedLo = ownedLo;
            OwnedHi = ownedHi;
            FactorStart = factorStart;
            Factors = factors;
            Scratch = scratch;
            Shift = worstShift;
            BlockRows = A.BlockRows;
            BR = br;
            K = k;
            MaxLocalN = maxLocalN;

            if (ownsA) A.Dispose();

            info = new PreconditionerInfo
            {
                status = ok ? DirectSolveStatus.Success : DirectSolveStatus.NotPositiveDefinite,
                shift = (double)worstShift,
                attempts = worstAttempts,
            };
        }

        /// <summary>Disposes SubStart/SubBlocks/OwnedLo/OwnedHi/FactorStart/Factors/Scratch. Only
        /// call on an instance built via an Allocator ctor -- an instance built via a ref Arena ctor
        /// is arena-owned and must not be disposed directly.</summary>
        public unsafe void Dispose()
        {
            SubStart.Dispose();
            SubBlocks.Dispose();
            OwnedLo.Dispose();
            OwnedHi.Dispose();
            FactorStart.Dispose();
            Factors.Dispose();
            Scratch.Dispose();
        }

        /// <summary>z = M^-1 r = sum_i R_i^T A_i^-1 R_i r: zero z, then for each subdomain gather r,
        /// solve against the cached Cholesky factor, and add the local solution back into z over the
        /// overlapped block set. z must not alias r or Scratch.</summary>
        public bool IsIdentity => false;
        public bool IsSpd => true;
        public bool IsConstant => true;

        public unsafe void Apply(in floatN r, ref floatN z)
        {
            int n = Rows;
            if (r.N != n) throw new ArgumentException("floatAdditiveSchwarz.Apply: r.N must equal Rows");
            if (z.N != n) throw new ArgumentException("floatAdditiveSchwarz.Apply: z.N must equal Rows");
            if (z.Data.Ptr == r.Data.Ptr) throw new ArgumentException("floatAdditiveSchwarz.Apply: z must not alias r");
            if (z.Data.Ptr == Scratch.Data.Ptr) throw new ArgumentException("floatAdditiveSchwarz.Apply: z must not alias Scratch");
            if (r.Data.Ptr == Scratch.Data.Ptr) throw new ArgumentException("floatAdditiveSchwarz.Apply: r must not alias Scratch");

            floatN buf = Scratch;
            float* zp = z.Data.Ptr;
            float* rp = r.Data.Ptr;
            float* bufp = buf.Data.Ptr;

            for (int i = 0; i < n; i++) zp[i] = (float)0;

            for (int sub = 0; sub < K; sub++)
            {
                int start = SubStart[sub];
                int count = SubStart[sub + 1] - start;
                int nn = count * BR;
                int fbase = FactorStart[sub];

                for (int l = 0; l < count; l++)
                {
                    int g = SubBlocks[start + l];
                    int lb = l * BR, gb = g * BR;
                    for (int t = 0; t < BR; t++) bufp[lb + t] = rp[gb + t];
                }

                CholSolveInPlace(Factors, fbase, nn, buf);

                for (int l = 0; l < count; l++)
                {
                    int g = SubBlocks[start + l];
                    int lb = l * BR, gb = g * BR;
                    for (int t = 0; t < BR; t++) zp[gb + t] += bufp[lb + t];
                }
            }
        }

        // Solves (L L^T) x = b in place on b[0..nn), L the row-major nn x nn factor at Factors[fbase].
        static unsafe void CholSolveInPlace(floatN factors, int fbase, int nn, floatN b)
        {
            float* f = factors.Data.Ptr;
            float* bp = b.Data.Ptr;
            for (int r = 0; r < nn; r++)
            {
                float s = bp[r];
                int rowOff = fbase + r * nn;
                for (int c = 0; c < r; c++) s -= f[rowOff + c] * bp[c];
                bp[r] = s / f[rowOff + r];
            }
            for (int r = nn - 1; r >= 0; r--)
            {
                float s = bp[r];
                for (int c = r + 1; c < nn; c++) s -= f[fbase + c * nn + r] * bp[c];
                bp[r] = s / f[fbase + r * nn + r];
            }
        }
    }

    /// <summary>
    /// One-level RESTRICTED additive Schwarz (RAS) preconditioner over a square BSR:
    /// M^-1 = sum_i R~_i^T A_i^-1 R_i, where R_i gathers the overlapped subdomain and R~_i^T scatters
    /// back only its OWNED (non-overlapped) cell (Cai &amp; Sarkis 1999). Because the owned cells
    /// partition the index space, every dof is written exactly once -- no overlap summation. This
    /// makes M NON-SYMMETRIC even for SPD A: never use it with cg/minres/CG (there is no such
    /// overload -- the type is the guard); use <see cref="LinearAlgebra.Krylov"/>.biCGStab. The
    /// nonsymmetric sibling of <see cref="floatAdditiveSchwarz"/>, mirroring the IC0/ILU0 split.
    ///
    /// Local matrices A_i are factored densely once (LU with partial pivoting, since the target is
    /// general square A) and reused by every Apply. A numerically singular local block reports
    /// Singular via the out-info twin (no diagonal-shift retry -- RAS targets general A). Cached-
    /// factor memory is O(N * overlapFactor^2 * subdomainSize) -- see <see cref="SchwarzOptions"/>.
    /// Symmetric-storage A is mirrored to full transiently at setup. Built via a ref Arena ctor,
    /// every owned buffer is arena-tracked and the arena owns disposal -- do not call Dispose() on
    /// that instance. Built via an Allocator ctor, this instance owns those buffers standalone and
    /// Dispose() must be called when done. A single instance is not safe for concurrent Apply.
    /// </summary>
    public readonly struct floatRestrictedSchwarz : IfloatPreconditioner, IDisposable
    {
        /// <summary>Prefix offsets into <see cref="SubBlocks"/> (CSR-of-subdomains), length K+1.</summary>
        public readonly Indices SubStart;
        /// <summary>Each subdomain's overlapped block ids, ascending; concatenated per SubStart.</summary>
        public readonly Indices SubBlocks;
        /// <summary>Owned (non-overlapped) block range [lo,hi) per subdomain, length K each; the RAS
        /// scatter restricts to this range.</summary>
        public readonly Indices OwnedLo;
        public readonly Indices OwnedHi;
        /// <summary>Prefix offsets into <see cref="Factors"/> (entries = sum n_i^2), length K+1.</summary>
        public readonly Indices FactorStart;
        /// <summary>Cached compact LU factors in logical (pivoted) row order, row-major per subdomain
        /// (unit-lower L below the diagonal, U on/above it).</summary>
        public readonly floatN Factors;
        /// <summary>Per-subdomain row-permutation P (logical row r reads gathered entry P[r]);
        /// subdomain i occupies [SubStart[i]*BR, SubStart[i+1]*BR).</summary>
        public readonly Indices Piv;
        /// <summary>Apply-time gather buffer, length <see cref="MaxLocalN"/>.</summary>
        public readonly floatN Scratch;
        /// <summary>Apply-time solve buffer (permuted RHS then solution), length <see cref="MaxLocalN"/>.</summary>
        public readonly floatN Scratch2;

        public readonly int BlockRows;
        public readonly int BR;
        public readonly int K;
        public readonly int MaxLocalN;

        public int Rows => BlockRows * BR;

        /// <summary>Builds RAS with <see cref="SchwarzOptions.Default"/>. Throws if A is not square or
        /// if a local LU is singular; use the out-info overload for a non-throwing build.</summary>
        public floatRestrictedSchwarz(in floatBSR a, ref Arena arena)
        {
            this = new floatRestrictedSchwarz(in a, ref arena, out PreconditionerInfo info);
            if (!info.Solved)
                throw new ArgumentException("floatRestrictedSchwarz: a local LU factor is numerically singular");
        }

        /// <summary>Non-throwing build with <see cref="SchwarzOptions.Default"/>.</summary>
        public floatRestrictedSchwarz(in floatBSR a, ref Arena arena, out PreconditionerInfo info)
        {
            this = new floatRestrictedSchwarz(in a, ref arena, SchwarzOptions.Default, out info);
        }

        /// <summary>Builds RAS with the given options. Same throw contract as the options-less
        /// overload.</summary>
        public floatRestrictedSchwarz(in floatBSR a, ref Arena arena, in SchwarzOptions opts)
        {
            this = new floatRestrictedSchwarz(in a, ref arena, in opts, out PreconditionerInfo info);
            if (!info.Solved)
                throw new ArgumentException("floatRestrictedSchwarz: a local LU factor is numerically singular");
        }

        /// <summary>
        /// Non-throwing build: info.status is Success, or Singular when some subdomain's local LU
        /// hits a zero pivot (the preconditioner is then unusable -- do not Apply). shift is always 0
        /// and attempts always 1 (RAS does not retry with a diagonal shift). A non-square A still
        /// throws.
        /// </summary>
        public floatRestrictedSchwarz(in floatBSR a, ref Arena arena, in SchwarzOptions opts, out PreconditionerInfo info)
        {
            // Everything computed into locals; all readonly fields assigned once at the end (avoids
            // reading a not-yet-fully-assigned `this` in the struct ctor).
            floatBSR A = floatSchwarzShared.BuildTopology(in a, ref arena, in opts,
                out Indices subStart, out Indices subBlocks, out Indices ownedLo, out Indices ownedHi,
                out int k, out int maxBlocks);

            int br = A.BR;
            int maxLocalN = maxBlocks * br;

            var factorStart = arena.Indices(k + 1);
            factorStart[0] = 0;
            for (int i = 0; i < k; i++)
            {
                int nn = (subStart[i + 1] - subStart[i]) * br;
                factorStart[i + 1] = factorStart[i] + nn * nn;
            }
            var factors = arena.floatVec(factorStart[k]);
            var piv = arena.Indices(subStart[k] * br);
            var scratch = arena.floatVec(math.max(1, maxLocalN), true);
            var scratch2 = arena.floatVec(math.max(1, maxLocalN), true);

            bool ok = true;
            for (int i = 0; i < k; i++)
            {
                int start = subStart[i];
                int count = subStart[i + 1] - start;
                int n = count * br;
                int fbase = factorStart[i];
                int pbase = start * br;

                var M = new floatMxN(n, n, Allocator.Temp, true);
                for (int aI = 0; aI < count; aI++)
                {
                    int gr = subBlocks[start + aI];
                    for (int bI = 0; bI < count; bI++)
                    {
                        int gc = subBlocks[start + bI];
                        floatSchwarzShared.GatherBlock(in A, gr, gc, ref M, aI * br, bI * br, (float)0, br);
                    }
                }

                var P = new Pivot(n, Allocator.Temp);
                var luInfo = LU.decompInPlace(ref M, ref P);
                if (luInfo.Solved)
                {
                    // Store the compact LU in logical row order: F[r,c] = M[P[r], c].
                    for (int rr = 0; rr < n; rr++)
                    {
                        int pr = P[rr];
                        piv[pbase + rr] = pr;
                        int dst = fbase + rr * n;
                        for (int c = 0; c < n; c++) factors[dst + c] = M[pr, c];
                    }
                }
                else ok = false;

                P.Dispose();
                M.Dispose();
                if (!ok) break;
            }

            SubStart = subStart;
            SubBlocks = subBlocks;
            OwnedLo = ownedLo;
            OwnedHi = ownedHi;
            FactorStart = factorStart;
            Factors = factors;
            Piv = piv;
            Scratch = scratch;
            Scratch2 = scratch2;
            BlockRows = A.BlockRows;
            BR = br;
            K = k;
            MaxLocalN = maxLocalN;

            info = new PreconditionerInfo
            {
                status = ok ? DirectSolveStatus.Success : DirectSolveStatus.Singular,
                shift = 0,
                attempts = 1,
            };
        }

        /// <summary>Standalone twin of <see cref="floatRestrictedSchwarz(in floatBSR, ref Arena)"/>,
        /// allocated from <paramref name="allocator"/>. Dispose the result with
        /// <see cref="Dispose"/> -- only call Dispose on an instance built via an Allocator ctor.</summary>
        public unsafe floatRestrictedSchwarz(in floatBSR a, Allocator allocator)
        {
            this = new floatRestrictedSchwarz(in a, allocator, out PreconditionerInfo info);
            if (!info.Solved)
            {
                Dispose();
                throw new ArgumentException("floatRestrictedSchwarz: a local LU factor is numerically singular");
            }
        }

        /// <summary>Standalone twin of <see cref="floatRestrictedSchwarz(in floatBSR, ref Arena, out PreconditionerInfo)"/>.</summary>
        public unsafe floatRestrictedSchwarz(in floatBSR a, Allocator allocator, out PreconditionerInfo info)
        {
            this = new floatRestrictedSchwarz(in a, allocator, SchwarzOptions.Default, out info);
        }

        /// <summary>Standalone twin of <see cref="floatRestrictedSchwarz(in floatBSR, ref Arena, in SchwarzOptions)"/>.</summary>
        public unsafe floatRestrictedSchwarz(in floatBSR a, Allocator allocator, in SchwarzOptions opts)
        {
            this = new floatRestrictedSchwarz(in a, allocator, in opts, out PreconditionerInfo info);
            if (!info.Solved)
            {
                Dispose();
                throw new ArgumentException("floatRestrictedSchwarz: a local LU factor is numerically singular");
            }
        }

        /// <summary>
        /// Standalone twin of <see cref="floatRestrictedSchwarz(in floatBSR, ref Arena, in SchwarzOptions, out PreconditionerInfo)"/>:
        /// allocates every owned buffer from <paramref name="allocator"/> instead of an arena. Same
        /// throw contract (buffers are allocated and left populated with the failed factorization
        /// even on breakdown -- Dispose is still valid). Only call Dispose on an instance built via
        /// an Allocator ctor, never on one built via a ref Arena ctor (that instance is arena-owned).
        /// </summary>
        public unsafe floatRestrictedSchwarz(in floatBSR a, Allocator allocator, in SchwarzOptions opts, out PreconditionerInfo info)
        {
            floatBSR A = floatSchwarzShared.BuildTopology(in a, allocator, in opts,
                out Indices subStart, out Indices subBlocks, out Indices ownedLo, out Indices ownedHi,
                out int k, out int maxBlocks, out bool ownsA);

            int br = A.BR;
            int maxLocalN = maxBlocks * br;

            var factorStart = new Indices(k + 1, allocator);
            factorStart[0] = 0;
            for (int i = 0; i < k; i++)
            {
                int nn = (subStart[i + 1] - subStart[i]) * br;
                factorStart[i + 1] = factorStart[i] + nn * nn;
            }
            var factors = new floatN(factorStart[k], allocator);
            var piv = new Indices(subStart[k] * br, allocator);
            var scratch = new floatN(math.max(1, maxLocalN), allocator, true);
            var scratch2 = new floatN(math.max(1, maxLocalN), allocator, true);

            bool ok = true;
            for (int i = 0; i < k; i++)
            {
                int start = subStart[i];
                int count = subStart[i + 1] - start;
                int n = count * br;
                int fbase = factorStart[i];
                int pbase = start * br;

                var M = new floatMxN(n, n, Allocator.Temp, true);
                for (int aI = 0; aI < count; aI++)
                {
                    int gr = subBlocks[start + aI];
                    for (int bI = 0; bI < count; bI++)
                    {
                        int gc = subBlocks[start + bI];
                        floatSchwarzShared.GatherBlock(in A, gr, gc, ref M, aI * br, bI * br, (float)0, br);
                    }
                }

                var P = new Pivot(n, Allocator.Temp);
                var luInfo = LU.decompInPlace(ref M, ref P);
                if (luInfo.Solved)
                {
                    for (int rr = 0; rr < n; rr++)
                    {
                        int pr = P[rr];
                        piv[pbase + rr] = pr;
                        int dst = fbase + rr * n;
                        for (int c = 0; c < n; c++) factors[dst + c] = M[pr, c];
                    }
                }
                else ok = false;

                P.Dispose();
                M.Dispose();
                if (!ok) break;
            }

            SubStart = subStart;
            SubBlocks = subBlocks;
            OwnedLo = ownedLo;
            OwnedHi = ownedHi;
            FactorStart = factorStart;
            Factors = factors;
            Piv = piv;
            Scratch = scratch;
            Scratch2 = scratch2;
            BlockRows = A.BlockRows;
            BR = br;
            K = k;
            MaxLocalN = maxLocalN;

            if (ownsA) A.Dispose();

            info = new PreconditionerInfo
            {
                status = ok ? DirectSolveStatus.Success : DirectSolveStatus.Singular,
                shift = 0,
                attempts = 1,
            };
        }

        /// <summary>Disposes SubStart/SubBlocks/OwnedLo/OwnedHi/FactorStart/Factors/Piv/Scratch/
        /// Scratch2. Only call on an instance built via an Allocator ctor -- an instance built via a
        /// ref Arena ctor is arena-owned and must not be disposed directly.</summary>
        public unsafe void Dispose()
        {
            SubStart.Dispose();
            SubBlocks.Dispose();
            OwnedLo.Dispose();
            OwnedHi.Dispose();
            FactorStart.Dispose();
            Factors.Dispose();
            Piv.Dispose();
            Scratch.Dispose();
            Scratch2.Dispose();
        }

        /// <summary>z = M^-1 r = sum_i R~_i^T A_i^-1 R_i r: for each subdomain gather r, solve against
        /// the cached LU factor, and write the owned-cell entries into z (each dof exactly once). z
        /// must not alias r, Scratch, or Scratch2.</summary>
        public bool IsIdentity => false;
        // RAS's owned-cell scatter (no overlap summation) makes M non-symmetric even for SPD A --
        // see the type doc comment. Never a valid cg/minres preconditioner.
        public bool IsSpd => false;
        public bool IsConstant => true;

        public unsafe void Apply(in floatN r, ref floatN z)
        {
            int n = Rows;
            if (r.N != n) throw new ArgumentException("floatRestrictedSchwarz.Apply: r.N must equal Rows");
            if (z.N != n) throw new ArgumentException("floatRestrictedSchwarz.Apply: z.N must equal Rows");
            if (z.Data.Ptr == r.Data.Ptr) throw new ArgumentException("floatRestrictedSchwarz.Apply: z must not alias r");
            if (z.Data.Ptr == Scratch.Data.Ptr || z.Data.Ptr == Scratch2.Data.Ptr) throw new ArgumentException("floatRestrictedSchwarz.Apply: z must not alias Scratch");
            if (r.Data.Ptr == Scratch.Data.Ptr || r.Data.Ptr == Scratch2.Data.Ptr) throw new ArgumentException("floatRestrictedSchwarz.Apply: r must not alias Scratch");

            floatN gatherBuf = Scratch;
            floatN solveBuf = Scratch2;
            float* rp = r.Data.Ptr;
            float* zp = z.Data.Ptr;
            float* gatherp = gatherBuf.Data.Ptr;
            float* solvep = solveBuf.Data.Ptr;

            for (int sub = 0; sub < K; sub++)
            {
                int start = SubStart[sub];
                int count = SubStart[sub + 1] - start;
                int nn = count * BR;
                int fbase = FactorStart[sub];
                int pbase = start * BR;

                for (int l = 0; l < count; l++)
                {
                    int g = SubBlocks[start + l];
                    int lb = l * BR, gb = g * BR;
                    for (int t = 0; t < BR; t++) gatherp[lb + t] = rp[gb + t];
                }

                for (int rr = 0; rr < nn; rr++) solvep[rr] = gatherp[Piv[pbase + rr]];

                LUSolveInPlace(Factors, fbase, nn, solveBuf);

                int lo = OwnedLo[sub], hi = OwnedHi[sub];
                for (int l = 0; l < count; l++)
                {
                    int g = SubBlocks[start + l];
                    if (g < lo || g >= hi) continue;
                    int lb = l * BR, gb = g * BR;
                    for (int t = 0; t < BR; t++) zp[gb + t] = solvep[lb + t];
                }
            }
        }

        // Solves (L U) x = b in place on b[0..nn) (already row-permuted): unit-lower forward sweep,
        // then upper backward sweep. F the row-major compact LU at Factors[fbase].
        static unsafe void LUSolveInPlace(floatN factors, int fbase, int nn, floatN b)
        {
            float* f = factors.Data.Ptr;
            float* bp = b.Data.Ptr;
            for (int r = 0; r < nn; r++)
            {
                float s = bp[r];
                int rowOff = fbase + r * nn;
                for (int c = 0; c < r; c++) s -= f[rowOff + c] * bp[c];
                bp[r] = s;
            }
            for (int r = nn - 1; r >= 0; r--)
            {
                float s = bp[r];
                int rowOff = fbase + r * nn;
                for (int c = r + 1; c < nn; c++) s -= f[rowOff + c] * bp[c];
                bp[r] = s / f[rowOff + r];
            }
        }
    }
}
