// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/ML/KMeansEnums.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
//singularFile//
namespace LinearAlgebra.ML
{
    // Seeding strategy for KMeans.fit.
    // KMeansPlusPlus = D²-weighted seeding (Arthur & Vassilvitskii 2007); O(k·N·D);
    //   improves convergence and solution quality significantly over random init.
    // Uniform = pick k distinct random points via reservoir selection; O(N); fast
    //   for large k or when budget is tight and init quality matters less.
    public enum KMeansInit { KMeansPlusPlus, Uniform }
}
