// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/Statistics/Stats.iProxy.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
#define UNITY_BURST_EXPERIMENTAL_LOOP_INTRINSICS

using System.Runtime.CompilerServices;

namespace LinearAlgebra
{
    // Public statistics surface for the SIGNED integer family (int/short/long -- uint is
    // deliberately excluded: difference/accumulation code is the unsigned-hostile category).
    // Sibling of StatsOP.fProxy.cs's `Stats` facade -- merges into the SAME bare partial class,
    // forwarding to the distinct intStatsCore/shortStatsCore/longStatsCore generic bodies (see
    // StatsCore.short.cs) so the type-identical generic signatures never collide -- the same
    // reason StatsOP.fProxy.cs's facade forwards to floatStatsCore/doubleStatsCore instead of
    // merging the generic bodies directly.
    //
    // RETURN-TYPE WIDENING (locked convention): sum -> long (widened accumulator, avoids
    // overflow); mean/variance/stdDev/varianceSample/stdDevSample/median -> double (need a
    // fractional result regardless of the source integer type, e.g. mean({1,2}) == 1.5);
    // min/max -> same-type (short); argmin/argmax -> int (an index, not a value).
    //
    // Whole-array forms only (vector shortN, or a matrix shortMxN treated as one flat
    // distribution) -- no per-axis row/col reductions, no covariance/correlation, no in-place
    // transforms (standardize/rescale/softmax/... don't fit the widened-return convention and
    // are out of scope for this integer surface).
    public static partial class Stats
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static long sum(in shortN   x) => shortStatsCore.sum(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static long sum(in shortMxN x) => shortStatsCore.sum(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double mean(in shortN   x) => shortStatsCore.mean(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double mean(in shortMxN x) => shortStatsCore.mean(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double variance(in shortN   x) => shortStatsCore.variance(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double variance(in shortMxN x) => shortStatsCore.variance(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double stdDev(in shortN   x) => shortStatsCore.stdDev(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double stdDev(in shortMxN x) => shortStatsCore.stdDev(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double varianceSample(in shortN   x) => shortStatsCore.varianceSample(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double varianceSample(in shortMxN x) => shortStatsCore.varianceSample(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double stdDevSample(in shortN   x) => shortStatsCore.stdDevSample(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double stdDevSample(in shortMxN x) => shortStatsCore.stdDevSample(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double median(in shortN   x) => shortStatsCore.median(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static double median(in shortMxN x) => shortStatsCore.median(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static short min(in shortN   x) => shortStatsCore.min(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static short min(in shortMxN x) => shortStatsCore.min(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static short max(in shortN   x) => shortStatsCore.max(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static short max(in shortMxN x) => shortStatsCore.max(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static int argmin(in shortN   x) => shortStatsCore.argmin(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static int argmin(in shortMxN x) => shortStatsCore.argmin(in x);

        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static int argmax(in shortN   x) => shortStatsCore.argmax(in x);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static int argmax(in shortMxN x) => shortStatsCore.argmax(in x);
    }
}
