// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/iProxy/iProxyN.Indexing.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
using System;
using System.Runtime.CompilerServices;


namespace LinearAlgebra
{

    public partial struct uintN {

        // Direct array accessor (both int and System.Index, from-end supported).
        public ref uint this[int index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => ref Data.ElementAt(index);
        }

        public ref uint this[System.Index index]
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => ref Data.ElementAt(index.IsFromEnd ? Data.Length - index.Value : index.Value);
        }
    }
}