// <auto-generated>
//   Generated from Assets/LinearAlgebra/CodeGen/TemplateSource/bool/boolN.Shortcuts.cs
//   DO NOT EDIT BY HAND - edit the template and run Tools/regen.ps1.
// </auto-generated>
// Generated
// Shortcuts for creating new vectors and matrices
using LinearAlgebra;

namespace LinearAlgebra {

    public partial struct boolN : IArenaShortcuts
    {
        
        public unsafe floatN floatVec(int N, bool uninit = false) => OwnerArena.floatVec(N, uninit);

        public unsafe floatN floatTempVec(int N, bool uninit = false) => OwnerArena.floatTempVec(N, uninit);

        public unsafe floatMxN floatMat(int M_rows, int N_cols, bool uninit = false) => OwnerArena.floatMat(M_rows, N_cols, uninit);

        public unsafe floatMxN floatTempMat(int M_rows, int N_cols, bool uninit = false) => OwnerArena.floatTempMat(M_rows, N_cols, uninit);
        
        public unsafe doubleN doubleVec(int N, bool uninit = false) => OwnerArena.doubleVec(N, uninit);

        public unsafe doubleN doubleTempVec(int N, bool uninit = false) => OwnerArena.doubleTempVec(N, uninit);

        public unsafe doubleMxN doubleMat(int M_rows, int N_cols, bool uninit = false) => OwnerArena.doubleMat(M_rows, N_cols, uninit);

        public unsafe doubleMxN doubleTempMat(int M_rows, int N_cols, bool uninit = false) => OwnerArena.doubleTempMat(M_rows, N_cols, uninit);
        


        public unsafe boolN boolVec(int n, bool uninit = false) => OwnerArena.boolVec(n, uninit);

        public unsafe boolN boolTempVec(int n, bool uninit = false) => OwnerArena.boolTempVec(n, uninit);

        public unsafe boolMxN boolMat(int M_rows, int N_cols, bool uninit = false) => OwnerArena.boolMat(M_rows, N_cols, uninit);

        public unsafe boolMxN boolTempMat(int M_rows, int N_cols, bool uninit = false) => OwnerArena.boolTempMat(M_rows, N_cols, uninit);
    }
}